---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: I file dei registri di controllo vengono salvati nella directory /var/local/log di un nodo di amministrazione. I file di registro di controllo attivi sono denominati audit.log. 
---
= Rotazione del file di registro di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I file dei registri di controllo vengono salvati nel nodo di amministrazione `/var/local/log` elenco. I file di registro di controllo attivi sono denominati `audit.log` .


NOTE: Facoltativamente, è possibile modificare la destinazione dei log di controllo e inviare le informazioni di controllo a un server syslog esterno. I registri locali dei record di controllo continuano a essere generati e archiviati quando viene configurato un server syslog esterno. Vedere link:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e le destinazioni dei registri"] .

Una volta al giorno, l'attivo `audit.log` il file viene salvato e ne viene creato uno nuovo `audit.log` il file è avviato.  Il nome del file salvato indica quando è stato salvato, nel formato `_yyyy-mm-dd.txt_` .  Se in un singolo giorno viene creato più di un registro di controllo, i nomi dei file utilizzano la data di salvataggio del file, seguita da un numero, nel formato `_yyyy-mm-dd.txt.n_` .  Per esempio, `2018-04-15.txt` E `2018-04-15.txt.1` sono il primo e il secondo file di registro creati e salvati il 15 aprile 2018.

Dopo un giorno, il file salvato viene compresso e rinominato, nel formato `_yyyy-mm-dd.txt.gz_` , che conserva la data originale. Nel tempo, ciò si traduce nel consumo dello spazio di archiviazione allocato per i log di controllo sul nodo di amministrazione. Uno script monitora il consumo di spazio del registro di controllo ed elimina i file di registro se necessario per liberare spazio nel `/var/local/log` elenco.  I registri di controllo vengono eliminati in base alla data di creazione, partendo da quelli più vecchi. È possibile monitorare le azioni dello script nel seguente file: `/var/local/log/manage-audit.log` .

Questo esempio mostra l'attivo `audit.log` file, il file del giorno precedente(`2018-04-15.txt` ), e il file compresso del giorno precedente(`2018-04-14.txt.gz` ).

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----