---
permalink: audit/audit-messages-main.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message 
summary: Nelle sezioni seguenti sono elencate descrizioni dettagliate dei messaggi di controllo restituiti dal sistema.  Ogni messaggio di controllo viene prima elencato in una tabella che raggruppa i messaggi correlati in base alla classe di attività che il messaggio rappresenta.  Questi raggruppamenti sono utili sia per comprendere i tipi di attività sottoposte a audit, sia per selezionare il tipo desiderato di filtraggio dei messaggi di audit. 
---
= Descrizioni dei messaggi di audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nelle sezioni seguenti sono elencate descrizioni dettagliate dei messaggi di controllo restituiti dal sistema.  Ogni messaggio di controllo viene prima elencato in una tabella che raggruppa i messaggi correlati in base alla classe di attività che il messaggio rappresenta.  Questi raggruppamenti sono utili sia per comprendere i tipi di attività sottoposte a audit, sia per selezionare il tipo desiderato di filtraggio dei messaggi di audit.

I messaggi di controllo sono inoltre elencati in ordine alfabetico in base ai rispettivi codici di quattro caratteri.  Questo elenco alfabetico consente di trovare informazioni su messaggi specifici.

I codici a quattro caratteri utilizzati in questo capitolo sono i valori ATYP presenti nei messaggi di controllo, come mostrato nel seguente messaggio di esempio:

[listing, subs="specialcharacters,quotes"]
----
2014-07-17T03:50:47.484627
\[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][*ATYP\(FC32\):SYSU*][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Per informazioni sull'impostazione dei livelli dei messaggi di controllo, sulla modifica delle destinazioni dei registri e sull'utilizzo di un server syslog esterno per le informazioni di controllo, vederelink:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e le destinazioni dei registri"]
