---
permalink: audit/cbre-object-receive-end.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBRE, Object Receive End 
summary: 'Quando il trasferimento di un blocco di contenuto da un nodo a un altro è completato, questo messaggio viene emesso dall"entità di destinazione.' 
---
= CBRE: Oggetto Ricevente Fine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando il trasferimento di un blocco di contenuto da un nodo a un altro è completato, questo messaggio viene emesso dall'entità di destinazione.

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
CNID
 a| 
Identificatore di connessione
 a| 
Identificatore univoco della sessione/connessione da nodo a nodo.



 a| 
CBID
 a| 
Identificatore del blocco di contenuto
 a| 
Identificatore univoco del blocco di contenuto trasferito.



 a| 
CTDR
 a| 
Direzione di trasferimento
 a| 
Indica se il trasferimento CBID è stato avviato tramite push o pull:

PUSH: L'operazione di trasferimento è stata richiesta dall'entità mittente.

PULL: L'operazione di trasferimento è stata richiesta dall'entità ricevente.



 a| 
CTSR
 a| 
Entità sorgente
 a| 
ID nodo dell'origine (mittente) del trasferimento CBID.



 a| 
CTDS
 a| 
Entità di destinazione
 a| 
ID del nodo di destinazione (ricevitore) del trasferimento CBID.



 a| 
CTSS
 a| 
Avvia conteggio sequenza
 a| 
Indica il conteggio della sequenza in cui è iniziato il trasferimento.



 a| 
CTAS
 a| 
Conteggio effettivo della sequenza finale
 a| 
Indica l'ultimo conteggio sequenziale trasferito correttamente.  Se il conteggio effettivo della sequenza finale è uguale al conteggio della sequenza iniziale e il risultato del trasferimento non è andato a buon fine, non è stato scambiato alcun dato.



 a| 
RSLT
 a| 
Risultato del trasferimento
 a| 
Il risultato dell'operazione di trasferimento (dal punto di vista dell'entità mittente):

SUCS: trasferimento completato con successo; tutti i conteggi delle sequenze richiesti sono stati inviati.

CONL: connessione persa durante il trasferimento

CTMO: timeout della connessione durante l'avvio o il trasferimento

UNRE: ID nodo di destinazione non raggiungibile

CRPT: trasferimento terminato a causa della ricezione di dati corrotti o non validi

|===
Questo messaggio di controllo indica che è stata completata un'operazione di trasferimento dati da nodo a nodo.  Se il risultato del trasferimento ha avuto esito positivo, l'operazione ha trasferito i dati da "Conteggio sequenza iniziale" a "Conteggio sequenza finale effettivo".  I nodi di invio e ricezione sono identificati dai rispettivi ID nodo.  Queste informazioni possono essere utilizzate per monitorare il flusso di dati del sistema e per individuare, tabulare e analizzare gli errori.  Se abbinato ai messaggi di controllo dell'archiviazione, può essere utilizzato anche per verificare i conteggi delle repliche.
