---
permalink: audit/client-read-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client read, S3SL, SGET, SHEA, WGET, WHEA, S3, swift 
summary: 'I messaggi di controllo di lettura del client vengono registrati quando un"applicazione client S3 effettua una richiesta per recuperare un oggetto.' 
---
= Il cliente ha letto i messaggi di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi di controllo di lettura del client vengono registrati quando un'applicazione client S3 effettua una richiesta per recuperare un oggetto.

[cols="1a,3a,1a,1a"]
|===
| Codice | Descrizione | Utilizzato da | Vedere 


 a| 
S3SL
 a| 
Richiesta S3 Select: registra un completamento dopo che una richiesta S3 Select è stata restituita al client.  Il messaggio S3SL può includere dettagli sul messaggio di errore e sul codice di errore.  La richiesta potrebbe non essere andata a buon fine.
 a| 
Cliente S3
 a| 
link:s3-select-request.html["S3SL: Richiesta di selezione S3"]



 a| 
SGET
 a| 
S3 GET: registra una transazione riuscita per recuperare un oggetto o elencare gli oggetti in un bucket.

*Nota:* se la transazione opera su una sottorisorsa, il messaggio di controllo includerà il campo S3SR.
 a| 
Cliente S3
 a| 
link:sget-s3-get.html["SGET: S3 GET"]



 a| 
KARITÉ
 a| 
S3 HEAD: registra una transazione riuscita per verificare l'esistenza di un oggetto o di un bucket.
 a| 
Cliente S3
 a| 
link:shea-s3-head.html["SHEA: TESTA S3"]



 a| 
WGET
 a| 
Swift GET: registra una transazione riuscita per recuperare un oggetto o elencare gli oggetti in un contenitore.
 a| 
Cliente Swift
 a| 
link:wget-swift-get.html["WGET: GET rapido"]



 a| 
WHEA
 a| 
Swift HEAD: registra una transazione riuscita per verificare l'esistenza di un oggetto o di un contenitore.
 a| 
Cliente Swift
 a| 
link:whea-swift-head.html["WHEA: TESTA Veloce"]

|===