---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: Tutti i messaggi di audit contengono elementi comuni. 
---
= Elementi comuni nei messaggi di audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tutti i messaggi di audit contengono elementi comuni.

[cols="1a,1a,4a"]
|===
| Codice | Tipo | Descrizione 


 a| 
IN MEZZO
 a| 
FC32
 a| 
ID modulo: identificatore di quattro caratteri dell'ID modulo che ha generato il messaggio.  Indica il segmento di codice all'interno del quale è stato generato il messaggio di controllo.



 a| 
ANID
 a| 
UI32
 a| 
ID nodo: ID del nodo della griglia assegnato al servizio che ha generato il messaggio.  A ciascun servizio viene assegnato un identificatore univoco al momento della configurazione e dell'installazione del sistema StorageGRID .  Questo ID non può essere modificato.



 a| 
ASES
 a| 
UI64
 a| 
Identificatore della sessione di audit: nelle versioni precedenti, questo elemento indicava l'ora in cui il sistema di audit veniva inizializzato dopo l'avvio del servizio.  Questo valore temporale è stato misurato in microsecondi a partire dall'epoca del sistema operativo (00:00:00 UTC del 1° gennaio 1970).

*Nota:* questo elemento è obsoleto e non compare più nei messaggi di controllo.



 a| 
ASQN
 a| 
UI64
 a| 
Conteggio sequenza: nelle versioni precedenti, questo contatore veniva incrementato per ogni messaggio di controllo generato sul nodo della griglia (ANID) e reimpostato a zero al riavvio del servizio.

*Nota:* questo elemento è obsoleto e non compare più nei messaggi di controllo.



 a| 
ATID
 a| 
UI64
 a| 
ID traccia: identificatore condiviso dall'insieme dei messaggi attivati da un singolo evento.



 a| 
ATIM
 a| 
UI64
 a| 
Timestamp: ora in cui è stato generato l'evento che ha attivato il messaggio di controllo, misurata in microsecondi a partire dall'epoca del sistema operativo (00:00:00 UTC del 1° gennaio 1970).  Si noti che la maggior parte degli strumenti disponibili per convertire il timestamp in data e ora locali si basano sui millisecondi.

Potrebbe essere necessario arrotondare o troncare il timestamp registrato.  L'ora leggibile dall'uomo che appare all'inizio del messaggio di controllo nel `audit.log` il file è l'attributo ATIM nel formato ISO 8601.  La data e l'ora sono rappresentate come `_YYYY-MMDDTHH:MM:SS.UUUUUU_` , dove il `T` è un carattere stringa letterale che indica l'inizio del segmento temporale della data. `_UUUUUU_` sono microsecondi.



 a| 
ATYP
 a| 
FC32
 a| 
Tipo di evento: identificatore di quattro caratteri dell'evento registrato.  Questo regola il contenuto del "payload" del messaggio: gli attributi che sono inclusi.



 a| 
AVERE
 a| 
UI32
 a| 
Versione: la versione del messaggio di controllo.  Con l'evoluzione del software StorageGRID , le nuove versioni dei servizi potrebbero incorporare nuove funzionalità nei report di audit.  Questo campo consente la compatibilità con le versioni precedenti del servizio AMS per elaborare messaggi provenienti da versioni precedenti dei servizi.



 a| 
RSLT
 a| 
FC32
 a| 
Risultato: il risultato di un evento, di un processo o di una transazione.  Se non è rilevante per un messaggio, viene utilizzato NONE anziché SUCS, in modo che il messaggio non venga filtrato accidentalmente.

|===