---
permalink: audit/etaf-security-authentication-failed.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, ETAF, Security Authentication Failed 
summary: 'Questo messaggio viene generato quando un tentativo di connessione tramite Transport Layer Security \(TLS\) non riesce.' 
---
= ETAF: Autenticazione di sicurezza non riuscita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo messaggio viene generato quando un tentativo di connessione tramite Transport Layer Security (TLS) non riesce.

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
CNID
 a| 
Identificatore di connessione
 a| 
Identificatore di sistema univoco per la connessione TCP/IP su cui l'autenticazione non è riuscita.



 a| 
RUID
 a| 
Identità utente
 a| 
Un identificatore dipendente dal servizio che rappresenta l'identità dell'utente remoto.



 a| 
RSLT
 a| 
Codice motivo
 a| 
Motivo del fallimento:

SCNI: Impossibile stabilire una connessione sicura.

CERM: Certificato mancante.

CERT: Il certificato non è valido.

CERE: Il certificato è scaduto.

CERR: Il certificato è stato revocato.

CSGN: la firma del certificato non è valida.

CSGU: Il firmatario del certificato era sconosciuto.

UCRM: le credenziali utente erano mancanti.

UCRI: Le credenziali utente non erano valide.

UCRU: Le credenziali utente non erano consentite.

TOUT: Autenticazione scaduta.

|===
Quando viene stabilita una connessione a un servizio sicuro che utilizza TLS, le credenziali dell'entità remota vengono verificate utilizzando il profilo TLS e la logica aggiuntiva integrata nel servizio.  Se l'autenticazione fallisce a causa di certificati o credenziali non validi, inattesi o non consentiti, viene registrato un messaggio di controllo.  Ciò consente di effettuare query su tentativi di accesso non autorizzati e altri problemi di connessione correlati alla sicurezza.

Il messaggio potrebbe essere causato da un'entità remota con una configurazione errata o da tentativi di presentare al sistema credenziali non valide o non consentite.  Questo messaggio di controllo deve essere monitorato per rilevare tentativi di accesso non autorizzato al sistema.
