---
permalink: audit/gtst-grid-task-started.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTST, Grid Task Started 
summary: 'Questo messaggio di controllo indica che il servizio CMN ha iniziato a elaborare l"attività di griglia specificata.  Il messaggio di controllo segue immediatamente il messaggio Grid Task Submitted per le attività della griglia avviate dal servizio interno Grid Task Submission e selezionate per l"attivazione automatica.  Per le attività della griglia inviate alla tabella In sospeso, questo messaggio viene generato quando l"utente avvia l"attività della griglia.' 
---
= GTST: Attività di griglia avviata
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo messaggio di controllo indica che il servizio CMN ha iniziato a elaborare l'attività di griglia specificata.  Il messaggio di controllo segue immediatamente il messaggio Grid Task Submitted per le attività della griglia avviate dal servizio interno Grid Task Submission e selezionate per l'attivazione automatica.  Per le attività della griglia inviate alla tabella In sospeso, questo messaggio viene generato quando l'utente avvia l'attività della griglia.

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
TSID
 a| 
ID attività
 a| 
Questo campo identifica in modo univoco un'attività di griglia generata e consente di gestirla durante il suo ciclo di vita.

*Nota:* l'ID attività viene assegnato al momento della generazione di un'attività della griglia, non al momento dell'invio.  È possibile che una determinata attività della griglia venga inviata più volte e, in questo caso, il campo ID attività non è sufficiente per collegare in modo univoco i messaggi di controllo Inviato, Iniziato e Terminato.



 a| 
RSLT
 a| 
Risultato
 a| 
Il risultato.  Questo campo ha un solo valore:

* SUCS: L'attività della griglia è stata avviata correttamente.


|===