---
permalink: audit/index.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, structure, content 
summary: 'Queste istruzioni contengono informazioni sulla struttura e sul contenuto dei messaggi di controllo e dei registri di controllo StorageGRID .  È possibile utilizzare queste informazioni per leggere e analizzare la traccia di controllo dell"attività del sistema.' 
---
= Messaggi e registri di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Queste istruzioni contengono informazioni sulla struttura e sul contenuto dei messaggi di controllo e dei registri di controllo StorageGRID .  È possibile utilizzare queste informazioni per leggere e analizzare la traccia di controllo dell'attività del sistema.

Queste istruzioni sono destinate agli amministratori responsabili della produzione di report sull'attività e l'utilizzo del sistema che richiedono l'analisi dei messaggi di audit del sistema StorageGRID .

Per utilizzare il file di registro di testo, è necessario avere accesso alla condivisione di controllo configurata sul nodo di amministrazione.

Per informazioni sulla configurazione dei livelli dei messaggi di controllo e sull'utilizzo di un server syslog esterno, vederelink:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e le destinazioni dei registri"] .
