---
permalink: audit/lkdm-leaked-object-cleanup.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LKDM, Leaked Object Cleanup 
summary:  
---
= LKDM: Pulizia degli oggetti trapelati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo messaggio viene generato quando un blocco trapelato viene pulito o eliminato.  Un blocco può essere parte di un oggetto replicato o di un oggetto codificato tramite cancellazione.

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
OROLOGIO
 a| 
Posizione del blocco
 a| 
Il percorso del file del frammento trapelato che è stato eliminato.



 a| 
CTYP
 a| 
Tipo di blocco
 a| 
Tipo di pezzo:

`ec: Erasure-coded object chunk`

`repl: Replicated object chunk`



 a| 
LTYP
 a| 
Tipo di perdita
 a| 
I cinque tipi di perdite che possono essere rilevate:

`object_leaked: Object doesn’t exist in the grid`

`location_leaked: Object exists in the grid, but found location doesn’t belong to object`

`mup_seg_leaked: Multipart upload was stopped or not completed, and the segment/part was left out`

`segment_leaked: Parent UUID/CBID (associated container object) is valid but doesn't contain this segment`

`no_parent: Container object is deleted, but object segment was left out and not deleted`



 a| 
CTIM
 a| 
Tempo di creazione del blocco
 a| 
Ora in cui è stato creato il frammento trapelato.



 a| 
UUID
 a| 
Identificatore univoco universale
 a| 
L'identificatore dell'oggetto a cui appartiene il blocco.



 a| 
CBID
 a| 
Identificatore del blocco di contenuto
 a| 
CBID dell'oggetto a cui appartiene il frammento trapelato.



 a| 
CSIZ
 a| 
Dimensione del contenuto
 a| 
La dimensione del blocco in byte.

|===