---
permalink: audit/syst-node-stopping.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYST, Node Stopping 
summary: 'Quando un servizio viene arrestato correttamente, viene generato questo messaggio per indicare che è stato richiesto l"arresto e che il servizio ha avviato la sequenza di arresto.  SYST può essere utilizzato per determinare se l"arresto è stato richiesto, prima che il servizio venga riavviato (a differenza di SYSD, che in genere viene inviato dopo il riavvio del servizio).' 
---
= SYST: Arresto del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando un servizio viene arrestato correttamente, viene generato questo messaggio per indicare che è stato richiesto l'arresto e che il servizio ha avviato la sequenza di arresto.  SYST può essere utilizzato per determinare se l'arresto è stato richiesto prima del riavvio del servizio (a differenza di SYSD, che in genere viene inviato dopo il riavvio del servizio).

[cols="1a,1a,4a"]
|===
| Codice | Campo | Descrizione 


 a| 
RSLT
 a| 
Arresto pulito
 a| 
La natura della chiusura:

SUCS: Il sistema è stato spento correttamente.

|===
Il messaggio non indica se il server host è stato arrestato, ma solo il servizio di reporting.  Il codice RSLT di un messaggio SYST non può indicare uno spegnimento "sporco", perché il messaggio viene generato solo da spegnimenti "puliti".
