---
permalink: audit/system-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, system, ECOC, ETAF, GNRG, GNUR, GTED, GTST, GTSU, LLST, OLST, SADD, SADE, SVRF, SVRU, SYSD, SYST, SYSU, VLST 
summary: 'I messaggi di controllo appartenenti alla categoria di controllo del sistema vengono utilizzati per eventi correlati al sistema di controllo stesso, agli stati dei nodi della griglia, alle attività delle attività a livello di sistema (attività della griglia) e alle operazioni di backup del servizio.' 
---
= Messaggi di controllo del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I messaggi di audit appartenenti alla categoria di audit del sistema vengono utilizzati per eventi correlati al sistema di audit stesso, agli stati dei nodi della griglia, alle attività delle attività a livello di sistema (attività della griglia) e alle operazioni di backup del servizio.

[cols="1a,2a,1a"]
|===
| Codice | Titolo e descrizione del messaggio | Vedere 


 a| 
ECMC
 a| 
Frammento di dati con codice di cancellazione mancante: indica che è stato rilevato un frammento di dati con codice di cancellazione mancante.
 a| 
link:ecmc-missing-erasure-coded-data-fragment.html["ECMC: frammento di dati codificato in modo cancellabile mancante"]



 a| 
ECOC
 a| 
Frammento di dati con codice di cancellazione danneggiato: indica che è stato rilevato un frammento di dati con codice di cancellazione danneggiato.
 a| 
link:ecoc-corrupt-erasure-coded-data-fragment.html["ECOC: Frammento di dati corrotti con codice di cancellazione"]



 a| 
ETAF
 a| 
Autenticazione di sicurezza non riuscita: un tentativo di connessione tramite Transport Layer Security (TLS) non è riuscito.
 a| 
link:etaf-security-authentication-failed.html["ETAF: Autenticazione di sicurezza non riuscita"]



 a| 
GNRG
 a| 
Registrazione GNDS: un servizio che aggiorna o registra informazioni su se stesso nel sistema StorageGRID .
 a| 
link:gnrg-gnds-registration.html["GNRG: Registrazione GNDS"]



 a| 
GNUR
 a| 
Annullamento della registrazione GNDS: un servizio ha annullato la registrazione dal sistema StorageGRID .
 a| 
link:gnur-gnds-unregistration.html["GNUR: Annullamento della registrazione GNDS"]



 a| 
GTED
 a| 
Attività di griglia terminata: il servizio CMN ha terminato l'elaborazione dell'attività di griglia.
 a| 
link:gted-grid-task-ended.html["GTED: attività di griglia terminata"]



 a| 
GTST
 a| 
Attività di griglia avviata: il servizio CMN ha iniziato a elaborare l'attività di griglia.
 a| 
link:gtst-grid-task-started.html["GTST: Attività di griglia avviata"]



 a| 
GTSU
 a| 
Attività di griglia inviata: un'attività di griglia è stata inviata al servizio CMN.
 a| 
link:gtsu-grid-task-submitted.html["GTSU: compito di griglia inviato"]



 a| 
LLST
 a| 
Posizione persa: questo messaggio di controllo viene generato quando una posizione viene persa.
 a| 
link:llst-location-lost.html["LLST: Posizione persa"]



 a| 
OLST
 a| 
Oggetto perso: l'oggetto richiesto non può essere individuato nel sistema StorageGRID .
 a| 
link:olst-system-detected-lost-object.html["OLST: il sistema ha rilevato un oggetto smarrito"]



 a| 
SADD
 a| 
Disattivazione controllo di sicurezza: la registrazione dei messaggi di controllo è stata disattivata.
 a| 
link:sadd-security-audit-disable.html["SADD: Disabilitazione controllo sicurezza"]



 a| 
SADE
 a| 
Abilitazione controllo di sicurezza: la registrazione dei messaggi di controllo è stata ripristinata.
 a| 
link:sade-security-audit-enable.html["SADE: Abilitazione controllo sicurezza"]



 a| 
SVRF
 a| 
Verifica fallita dell'archivio oggetti: un blocco di contenuto non ha superato i controlli di verifica.
 a| 
link:svrf-object-store-verify-fail.html["SVRF: Errore di verifica dell'archivio oggetti"]



 a| 
SVRU
 a| 
Verifica archivio oggetti sconosciuta: rilevati dati oggetto inattesi nell'archivio oggetti.
 a| 
link:svru-object-store-verify-unknown.html["SVRU: Verifica archivio oggetti sconosciuto"]



 a| 
SYSD
 a| 
Arresto del nodo: è stato richiesto un arresto.
 a| 
link:sysd-node-stop.html["SYSD: arresto del nodo"]



 a| 
SISTEMA
 a| 
Arresto del nodo: un servizio ha avviato un arresto regolare.
 a| 
link:syst-node-stopping.html["SYST: Arresto del nodo"]



 a| 
SIST
 a| 
Avvio nodo: un servizio avviato; la natura dell'arresto precedente è indicata nel messaggio.
 a| 
link:sysu-node-start.html["SYSU: Avvio del nodo"]

|===