---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 11.9 utilizza la versione 4 dell"API Tenant Management. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.' 
---
= Modifiche all'API di gestione degli inquilini
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.9 utilizza la versione 4 dell'API Tenant Management. La versione 4 depreca la versione 3; tuttavia, le versioni 1, 2 e 3 sono ancora supportate.


NOTE: È possibile continuare a utilizzare le versioni obsolete dell'API Tenant Management con StorageGRID 11.9; tuttavia, il supporto per queste versioni dell'API verrà rimosso in una futura versione di StorageGRID. Dopo l'aggiornamento a StorageGRID 11.9, è possibile disattivare le API deprecate utilizzando `PUT /grid/config/management` API.

Per saperne di più, vai alink:../tenant/understanding-tenant-management-api.html["Comprendere l'API di gestione degli inquilini"] .



== Nuova API per il limite di capacità del bucket

Puoi usare il `/org/containers/{bucketName}/quota-object-bytes` API con operazioni GET/PUT per ottenere e impostare il limite di capacità di archiviazione per un bucket.
