---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 'Valuta quando effettuare l"aggiornamento, in base al tempo che potrebbe richiedere.  Siate consapevoli delle operazioni che potete e non potete eseguire durante ogni fase dell"aggiornamento.' 
---
= Stimare il tempo necessario per completare un aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Valuta quando effettuare l'aggiornamento, in base al tempo che potrebbe richiedere.  Siate consapevoli delle operazioni che potete e non potete eseguire durante ogni fase dell'aggiornamento.

.Informazioni su questo compito
Il tempo necessario per completare un aggiornamento StorageGRID dipende da diversi fattori, tra cui il carico del client e le prestazioni dell'hardware.

La tabella riassume le principali attività di aggiornamento e indica il tempo approssimativo necessario per ciascuna attività.  I passaggi successivi alla tabella forniscono istruzioni utili per stimare i tempi di aggiornamento del sistema.

[cols="1a,2a,2a,4a"]
|===
| Attività di aggiornamento | Descrizione | Tempo approssimativo richiesto | Durante questo compito 


 a| 
Eseguire controlli preliminari e aggiornare il nodo di amministrazione primario
 a| 
Vengono eseguiti i controlli preliminari all'aggiornamento e il nodo di amministrazione primario viene arrestato, aggiornato e riavviato.
 a| 
Da 30 minuti a 1 ora, con i nodi degli appliance di servizi che richiedono più tempo.

Gli errori di pre-controllo non risolti aumenteranno questa volta.
 a| 
Non è possibile accedere al nodo di amministrazione primario.  Potrebbero essere segnalati errori di connessione, che puoi ignorare.

L'esecuzione dei controlli preliminari all'aggiornamento prima di avviarlo consente di risolvere eventuali errori prima della finestra di manutenzione programmata per l'aggiornamento.



 a| 
Avvia il servizio di aggiornamento
 a| 
Il file software viene distribuito e il servizio di aggiornamento viene avviato.
 a| 
3 minuti per nodo della griglia
 a| 



 a| 
Aggiorna altri nodi della griglia
 a| 
Il software su tutti gli altri nodi della griglia viene aggiornato nell'ordine in cui si approvano i nodi.  Ogni nodo del tuo sistema verrà disattivato uno alla volta.
 a| 
Da 15 minuti a 1 ora per nodo, con i nodi appliance che richiedono più tempo

*Nota*: per i nodi appliance, StorageGRID Appliance Installer viene aggiornato automaticamente all'ultima versione.
 a| 
* Non modificare la configurazione della griglia.
* Non modificare la configurazione del livello di controllo.
* Non aggiornare la configurazione ILM.
* Non è possibile eseguire altre procedure di manutenzione, come hotfix, dismissione o espansione.


*Nota*: se è necessario eseguire un ripristino, contattare l'assistenza tecnica.



 a| 
Abilita funzionalità
 a| 
Le nuove funzionalità della nuova versione sono abilitate.
 a| 
Meno di 5 minuti
 a| 
* Non modificare la configurazione della griglia.
* Non modificare la configurazione del livello di controllo.
* Non aggiornare la configurazione ILM.
* Non è possibile eseguire un'altra procedura di manutenzione.




 a| 
Aggiorna il database
 a| 
Il processo di aggiornamento controlla ogni nodo per verificare che il database Cassandra non debba essere aggiornato.
 a| 
10 secondi per nodo o pochi minuti per l'intera griglia
 a| 
L'aggiornamento da StorageGRID 11.8 a 11.9 non richiede un aggiornamento del database Cassandra; tuttavia, il servizio Cassandra verrà arrestato e riavviato su ciascun nodo di archiviazione.

Per le future versioni delle funzionalità StorageGRID , il completamento della fase di aggiornamento del database Cassandra potrebbe richiedere diversi giorni.



 a| 
Passaggi finali di aggiornamento
 a| 
I file temporanei vengono rimossi e l'aggiornamento alla nuova versione viene completato.
 a| 
5 minuti
 a| 
Una volta completata l'attività *Fasi finali di aggiornamento*, è possibile eseguire tutte le procedure di manutenzione.

|===
.Passi
. Stimare il tempo necessario per aggiornare tutti i nodi della griglia.
+
.. Moltiplica il numero di nodi nel tuo sistema StorageGRID per 1 ora/nodo.
+
Di norma, l'aggiornamento dei nodi appliance richiede più tempo rispetto ai nodi basati su software.

.. Aggiungere 1 ora a questo tempo per tenere conto del tempo necessario per scaricare il `.upgrade` file, eseguire le convalide preliminari e completare i passaggi finali di aggiornamento.


. Se si dispone di nodi Linux, aggiungere 15 minuti per ciascun nodo per tenere conto del tempo necessario per scaricare e installare il pacchetto RPM o DEB.
. Calcolare il tempo totale stimato per l'aggiornamento sommando i risultati dei passaggi 1 e 2.




== Esempio: tempo stimato per l'aggiornamento a StorageGRID 11.9

Supponiamo che il tuo sistema abbia 14 nodi di griglia, di cui 8 sono nodi Linux.

. Moltiplicare 14 per 1 ora/nodo.
. Aggiungere 1 ora per tenere conto del download, del controllo preliminare e dei passaggi finali.
+
Il tempo stimato per l'aggiornamento di tutti i nodi è di 15 ore.

. Moltiplicare 8 per 15 minuti/nodo per tenere conto del tempo necessario per installare il pacchetto RPM o DEB sui nodi Linux.
+
Il tempo stimato per questa fase è di 2 ore.

. Sommare i valori.
+
Per completare l'aggiornamento del sistema a StorageGRID 11.9.0 potrebbero essere necessarie fino a 17 ore.




NOTE: Se necessario, è possibile suddividere la finestra di manutenzione in finestre più piccole approvando sottoinsiemi di nodi della griglia da aggiornare in più sessioni.  Ad esempio, potresti preferire aggiornare i nodi nel sito A in una sessione e poi aggiornare i nodi nel sito B in una sessione successiva.  Se si sceglie di eseguire l'aggiornamento in più sessioni, tenere presente che non sarà possibile iniziare a utilizzare le nuove funzionalità finché tutti i nodi non saranno stati aggiornati.
