---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 'Scopri come l"aggiornamento interesserà il tuo sistema StorageGRID .' 
---
= Come viene influenzato il tuo sistema durante l'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri come l'aggiornamento interesserà il tuo sistema StorageGRID .



== Gli aggiornamenti StorageGRID non sono dirompenti

Il sistema StorageGRID può acquisire e recuperare dati dalle applicazioni client durante l'intero processo di aggiornamento.  Se si approva l'aggiornamento di tutti i nodi dello stesso tipo (ad esempio, nodi di archiviazione), i nodi vengono disattivati ​​uno alla volta, quindi non c'è un momento in cui tutti i nodi della griglia o tutti i nodi della griglia di un certo tipo non sono disponibili.

Per garantire una disponibilità continua, assicurati che la policy ILM contenga regole che specifichino l'archiviazione di più copie di ciascun oggetto.  È inoltre necessario assicurarsi che tutti i client S3 esterni siano configurati per inviare richieste a uno dei seguenti:

* Un indirizzo IP virtuale di gruppo ad alta disponibilità (HA)
* Un bilanciatore di carico di terze parti ad alta disponibilità
* Più nodi gateway per ogni client
* Più nodi di archiviazione per ogni client




== Le applicazioni client potrebbero subire interruzioni a breve termine

Il sistema StorageGRID può acquisire e recuperare dati dalle applicazioni client durante l'intero processo di aggiornamento; tuttavia, le connessioni client ai singoli nodi gateway o nodi di archiviazione potrebbero essere temporaneamente interrotte se l'aggiornamento richiede il riavvio dei servizi su tali nodi.  La connettività verrà ripristinata al termine del processo di aggiornamento e i servizi saranno ripresi sui singoli nodi.

Potrebbe essere necessario pianificare un periodo di inattività per applicare un aggiornamento se la perdita di connettività per un breve periodo non è accettabile.  È possibile utilizzare l'approvazione selettiva per pianificare quando aggiornare determinati nodi.


NOTE: È possibile utilizzare più gateway e gruppi ad alta disponibilità (HA) per garantire il failover automatico durante il processo di aggiornamento. Vedi le istruzioni perlink:../admin/configure-high-availability-group.html["configurazione di gruppi ad alta disponibilità"] .



== Il firmware dell'apparecchio è aggiornato

Durante l'aggiornamento StorageGRID 11.9:

* Tutti i nodi dell'appliance StorageGRID vengono automaticamente aggiornati alla versione 3.9 del firmware StorageGRID Appliance Installer.
* Gli apparecchi SG6060 e SGF6024 vengono automaticamente aggiornati alla versione firmware BIOS 3B08.EX e alla versione firmware BMC 4.00.07.
* Gli apparecchi SG100 e SG1000 vengono automaticamente aggiornati alla versione firmware BIOS 3B13.EC e alla versione firmware BMC 4.74.07.
* Gli apparecchi SGF6112, SG6160, SG110 e SG1100 vengono automaticamente aggiornati alla versione firmware BMC 3.16.07.




== Le politiche ILM vengono gestite in modo diverso a seconda del loro stato

* La policy attiva rimarrà la stessa dopo l'aggiornamento.
* Durante l'aggiornamento vengono conservate solo le ultime 10 policy storiche.
* Se è stata proposta una policy, questa verrà eliminata durante l'aggiornamento.




== Potrebbero essere attivati degli avvisi

Gli avvisi potrebbero essere attivati ​​quando i servizi vengono avviati e arrestati e quando il sistema StorageGRID funziona come ambiente a versione mista (alcuni nodi della griglia eseguono una versione precedente, mentre altri sono stati aggiornati a una versione successiva).  Al termine dell'aggiornamento potrebbero essere attivati ​​altri avvisi.

Ad esempio, potresti visualizzare l'avviso *Impossibile comunicare con il nodo* quando i servizi sono arrestati oppure l'avviso *Errore di comunicazione Cassandra* quando alcuni nodi sono stati aggiornati a StorageGRID 11.9 ma altri nodi eseguono ancora StorageGRID 11.8. In genere, questi avvisi scompariranno al termine dell'aggiornamento.

L'avviso *Posizionamento ILM non realizzabile* potrebbe essere attivato quando i nodi di archiviazione vengono arrestati durante l'aggiornamento a StorageGRID 11.9. Questo avviso potrebbe persistere per 1 giorno dopo il completamento dell'aggiornamento.

Una volta completato l'aggiornamento, puoi rivedere tutti gli avvisi relativi all'aggiornamento selezionando *Avvisi risolti di recente* o *Avvisi correnti* dalla dashboard di Grid Manager.



== Vengono generate molte notifiche SNMP

Tenere presente che potrebbe essere generato un numero elevato di notifiche SNMP quando i nodi della griglia vengono arrestati e riavviati durante l'aggiornamento.  Per evitare notifiche eccessive, deselezionare la casella di controllo *Abilita notifiche agente SNMP* (*CONFIGURAZIONE* > *Monitoraggio* > *Agente SNMP*) per disabilitare le notifiche SNMP prima di avviare l'aggiornamento.  Quindi, riattivare le notifiche una volta completato l'aggiornamento.



== Le modifiche alla configurazione sono limitate


NOTE: Questo elenco si applica specificamente agli aggiornamenti da StorageGRID 11.8 a StorageGRID 11.9. Se si esegue l'aggiornamento a un'altra versione StorageGRID , fare riferimento all'elenco delle modifiche limitate nelle istruzioni di aggiornamento per quella versione.

Fino al completamento dell'attività *Abilita nuova funzionalità*:

* Non apportare modifiche alla configurazione della griglia.
* Non abilitare o disabilitare nuove funzionalità.
* Non aggiornare la configurazione ILM.  In caso contrario, potresti riscontrare un comportamento ILM incoerente e inaspettato.
* Non applicare un hotfix o ripristinare un nodo della griglia.
+

NOTE: Se è necessario ripristinare un nodo durante l'aggiornamento, contattare l'assistenza tecnica.

* Non dovresti gestire gruppi HA, interfacce VLAN o endpoint del bilanciatore del carico durante l'aggiornamento a StorageGRID 11.9.
* Non eliminare alcun gruppo HA finché non sarà completato l'aggiornamento a StorageGRID 11.9. Gli indirizzi IP virtuali in altri gruppi HA potrebbero diventare inaccessibili.


Fino al completamento dell'attività *Passaggi finali di aggiornamento*:

* Non eseguire una procedura di espansione.
* Non eseguire una procedura di disattivazione.




== Non è possibile visualizzare i dettagli del bucket o gestirli dal Tenant Manager

Durante l'aggiornamento a StorageGRID 11.9 (ovvero mentre il sistema funziona come ambiente a versione mista), non è possibile visualizzare i dettagli dei bucket o gestirli tramite Tenant Manager.  Uno dei seguenti errori viene visualizzato nella pagina Bucket in Tenant Manager:

* Non puoi utilizzare questa API durante l'aggiornamento alla versione 11.9.
* Non è possibile visualizzare i dettagli del controllo delle versioni dei bucket in Tenant Manager durante l'aggiornamento alla versione 11.9.


Questo errore verrà risolto una volta completato l'aggiornamento alla versione 11.9.

.Soluzione alternativa
Mentre è in corso l'aggiornamento alla versione 11.9, utilizzare i seguenti strumenti per visualizzare i dettagli dei bucket o gestirli, anziché utilizzare Tenant Manager:

* Per eseguire operazioni S3 standard su un bucket, utilizzarelink:../s3/operations-on-buckets.html["API REST S3"] o illink:../tenant/understanding-tenant-management-api.html["API di gestione degli inquilini"] .
* Per eseguire operazioni personalizzate StorageGRID su un bucket (ad esempio, visualizzare e modificare la coerenza del bucket, abilitare o disabilitare gli aggiornamenti dell'ora dell'ultimo accesso o configurare l'integrazione della ricerca), utilizzare l'API Tenant Management.

