---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: 'Alcune funzionalità e capacità sono state rimosse o deprecate in questa versione.  Esaminare questi elementi per capire se è necessario aggiornare le applicazioni client o modificare la configurazione prima di eseguire l"aggiornamento.' 
---
= Funzionalità e capacità rimosse o deprecate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alcune funzionalità e capacità sono state rimosse o deprecate in questa versione.  Esaminare questi elementi per capire se è necessario aggiornare le applicazioni client o modificare la configurazione prima di eseguire l'aggiornamento.



== Definizioni

Obsoleto:: La funzionalità *non dovrebbe* essere utilizzata nei nuovi ambienti di produzione.  Gli ambienti di produzione esistenti possono continuare a utilizzare la funzionalità.
Fine della vita:: Ultima versione distribuita che supporta la funzionalità.  In alcuni casi, la documentazione relativa alla funzionalità potrebbe essere rimossa in questa fase.
RIMOSSO:: Prima versione che *non* supporta la funzionalità.




== Supporto per la fine delle funzionalità StorageGRID

Le funzionalità deprecate verranno rimosse nelle versioni principali N+2.  Ad esempio, se una funzionalità è obsoleta nella versione N (ad esempio, 6.3), l'ultima versione in cui la funzionalità sarà presente sarà N+1 (ad esempio, 6.4).  La versione N+2 (ad esempio, 6.5) è la prima versione quando la funzionalità non è presente nel prodotto.

Vedi il https://mysupport.netapp.com/site/info/version-support["Pagina di supporto della versione software"^] per ulteriori informazioni.


NOTE: In determinate situazioni, NetApp potrebbe interrompere il supporto per determinate funzionalità prima del previsto.

[cols="2a,1a,1a,1a,3a"]
|===
| Caratteristica | Obsoleto | Fine della vita | RIMOSSO | Link alla documentazione precedente 


 a| 
Allarmi legacy (_non avvisi_)
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["Riferimento allarmi (StorageGRID 11.8)"^]



 a| 
Supporto del nodo di archivio
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["Considerazioni sulla dismissione dei nodi di archivio (StorageGRID 11.8)"^]

*Nota*: prima di iniziare l'aggiornamento, è necessario:

. Disattivare tutti i nodi di archivio. Vedere https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["Dismissione del nodo di rete (sito di documentazione StorageGRID 11.8)"^] .
. Rimuovere tutti i riferimenti al nodo di archivio dai pool di archiviazione e dai criteri ILM. Vedere https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["Base di conoscenza NetApp : guida alla risoluzione dell'aggiornamento del software StorageGRID 11.9"^] .




 a| 
Esportazione di audit tramite CIFS/Samba
 a| 
11,1
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Servizio CLB
 a| 
11,4
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Motore per container Docker
 a| 
11,8
 a| 
11,9
 a| 
Da definire
 a| 
Il supporto per Docker come motore di container per distribuzioni esclusivamente software è deprecato. Docker verrà sostituito con un altro motore di container in una versione futura. Fare riferimento allink:../ubuntu/software-requirements.html#docker-versions-tested["elenco delle versioni di Docker attualmente supportate"] .



 a| 
Esportazione di controllo NFS
 a| 
11,8
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["Configurare l'accesso client di audit per NFS (StorageGRID 11.8)"^]



 a| 
Supporto API Swift
 a| 
11,7
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["Utilizzare Swift REST API (StorageGRID 11.8)"^]



 a| 
RHEL 8.8
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9.0
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9.2
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Ubuntu 18,04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Ubuntu 20,04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Debian 11
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 

|===
Vedere anche:

* link:../upgrade/changes-to-grid-management-api.html["Modifiche all'API di gestione della griglia"]
* link:../upgrade/changes-to-tenant-management-api.html["Modifiche all'API di gestione degli inquilini"]

