---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download ubuntu or debian installation files 
summary: 'È necessario scaricare l"archivio di installazione StorageGRID ed estrarre i file richiesti. Facoltativamente, è possibile verificare manualmente i file nel pacchetto di installazione.' 
---
= Scarica ed estrai i file di installazione StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario scaricare l'archivio di installazione StorageGRID ed estrarre i file richiesti. Facoltativamente, è possibile verificare manualmente i file nel pacchetto di installazione.

.Passi
. Vai al https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Pagina di download di NetApp per StorageGRID"^] .
. Seleziona il pulsante per scaricare l'ultima versione oppure seleziona un'altra versione dal menu a discesa e seleziona *Vai*.
. Sign in con il nome utente e la password del tuo account NetApp .
. Se viene visualizzata una dichiarazione di Attenzione/Lettura obbligatoria, leggerla e selezionare la casella di controllo.
+

CAUTION: Dopo aver installato la versione StorageGRID , è necessario applicare tutti gli hotfix richiesti. Per maggiori informazioni, vedere illink:../maintain/storagegrid-hotfix-procedure.html["procedura di hotfix nelle istruzioni di ripristino e manutenzione"]

. Leggere il Contratto di licenza con l'utente finale, selezionare la casella di controllo, quindi selezionare *Accetta e continua*.
. Nella colonna *Installa StorageGRID*, seleziona l'archivio di installazione .tgz o .zip per Ubuntu o Debian.
+

NOTE: Seleziona il `.zip` file se si utilizza Windows sul portatile di servizio.

. Salvare l'archivio di installazione.
. [[ubuntu-download-verification-package]]Se devi verificare l'archivio di installazione:
+
.. Scarica il pacchetto di verifica della firma del codice StorageGRID .  Il nome del file per questo pacchetto utilizza il formato `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz` , Dove `<version-number>` è la versione del software StorageGRID .
.. Segui i passaggi perlink:../ubuntu/download-files-verify.html["verificare manualmente i file di installazione"] .


. Estrarre i file dall'archivio di installazione.
. Scegli i file di cui hai bisogno.
+
I file necessari dipendono dalla topologia della griglia pianificata e dal modo in cui verrà distribuito il sistema StorageGRID .

+

NOTE: I percorsi elencati nella tabella sono relativi alla directory di livello superiore installata dall'archivio di installazione estratto.



[cols="1a,1a"]
|===
| Percorso e nome del file | Descrizione 


| ./debs/LEGGIMI  a| 
Un file di testo che descrive tutti i file contenuti nel file di download StorageGRID .



| ./debs/NLF000000.txt  a| 
Un file di licenza NetApp non di produzione che puoi utilizzare per test e distribuzioni di prova di concetto.



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
Pacchetto DEB per l'installazione delle immagini dei nodi StorageGRID su host Ubuntu o Debian.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
Checksum MD5 per il file `/debs/storagegrid-webscale-images-version-SHA.deb` .



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
Pacchetto DEB per l'installazione del servizio host StorageGRID su host Ubuntu o Debian.



| Strumento di scripting di distribuzione | Descrizione 


| ./debs/configure-storagegrid.py  a| 
Uno script Python utilizzato per automatizzare la configurazione di un sistema StorageGRID .



| ./debs/configure-sga.py  a| 
Uno script Python utilizzato per automatizzare la configurazione degli appliance StorageGRID .



| ./debs/storagegrid-ssoauth.py  a| 
Uno script Python di esempio che puoi utilizzare per accedere all'API di gestione della griglia quando è abilitato l'accesso singolo.  È possibile utilizzare questo script anche per l'integrazione di Ping Federate.



| ./debs/configure-storagegrid.sample.json  a| 
Un file di configurazione di esempio da utilizzare con `configure-storagegrid.py` sceneggiatura.



| ./debs/configure-storagegrid.blank.json  a| 
Un file di configurazione vuoto da utilizzare con `configure-storagegrid.py` sceneggiatura.



| ./debs/extras/ansible  a| 
Esempio di ruolo e playbook Ansible per la configurazione di host Ubuntu o Debian per la distribuzione di container StorageGRID .  È possibile personalizzare il ruolo o il playbook in base alle proprie esigenze.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Uno script Python di esempio che puoi utilizzare per accedere all'API Grid Management quando è abilitato l'accesso Single Sign-On (SSO) tramite Active Directory o Ping Federate.



| ./debs/storagegrid-ssoauth-azure.js  a| 
Uno script di supporto chiamato dal compagno `storagegrid-ssoauth-azure.py` Script Python per eseguire interazioni SSO con Azure.



| ./debs/extras/api-schemas  a| 
Schemi API per StorageGRID.

*Nota*: prima di eseguire un aggiornamento, puoi utilizzare questi schemi per confermare che il codice scritto per utilizzare le API di gestione StorageGRID sarà compatibile con la nuova versione StorageGRID se non disponi di un ambiente StorageGRID non di produzione per i test di compatibilità dell'aggiornamento.

|===