---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: È necessario installare StorageGRID su tutti gli host grid Ubuntu o Debian. Per un elenco delle versioni supportate, utilizzare lo strumento NetApp Interoperability Matrix. 
---
= Installa Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare StorageGRID su tutti gli host grid Ubuntu o Debian. Per un elenco delle versioni supportate, utilizzare lo strumento NetApp Interoperability Matrix.

.Prima di iniziare
Assicurati che il tuo sistema operativo soddisfi i requisiti minimi di versione del kernel di StorageGRID, come elencato di seguito.  Utilizzare il comando `uname -r` per ottenere la versione del kernel del tuo sistema operativo oppure consulta il fornitore del sistema operativo.

*Nota:* il supporto per le versioni 18.04 e 20.04 di Ubuntu è stato deprecato e verrà rimosso in una versione futura.

[cols="1a,2a,3a"]
|===
| Versione di Ubuntu | Versione minima del kernel | Nome del pacchetto del kernel 


 a| 
18.04.6 (obsoleto)
 a| 
5.4.0-150-generico
 a| 
linux-image-5.4.0-150-generic/bionic-updates,bionic-security,ora 5.4.0-150.167~18.04.1



 a| 
20.04.5 (obsoleto)
 a| 
5.4.0-131-generico
 a| 
linux-image-5.4.0-131-generic/focal-updates, ora 5.4.0-131.147



 a| 
22.04.1
 a| 
5.15.0-47-generico
 a| 
linux-image-5.15.0-47-generic/jammy-updates,jammy-security,ora 5.15.0-47.51



 a| 
24,04
 a| 
6.8.0-31-generico
 a| 
linux-image-6.8.0-31-generic/noble, ora 6.8.0-31.31

|===
*Nota:* il supporto per la versione 11 di Debian è stato deprecato e verrà rimosso in una versione futura.

[cols="1a,2a,2a"]
|===
| versione Debian | Versione minima del kernel | Nome del pacchetto del kernel 


 a| 
11 (obsoleto)
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/stable, ora 5.10.150-1



 a| 
12
 a| 
6.1.0-9-amd64
 a| 
linux-image-6.1.0-9-amd64/stable, ora 6.1.27-1

|===
.Passi
. Installare Linux su tutti gli host fisici o virtuali della griglia secondo le istruzioni del distributore o la procedura standard.
+

NOTE: Non installare alcun ambiente desktop grafico. Quando si installa Ubuntu, è necessario selezionare *utilità di sistema standard*. Si consiglia di selezionare *Server OpenSSH* per abilitare l'accesso SSH agli host Ubuntu. Tutte le altre opzioni possono rimanere deselezionate.

. Assicurarsi che tutti gli host abbiano accesso ai repository dei pacchetti Ubuntu o Debian.
. Se lo swap è abilitato:
+
.. Eseguire il seguente comando: `$ sudo swapoff --all`
.. Rimuovi tutte le voci di swap da `/etc/fstab` per mantenere le impostazioni.
+

NOTE: Se non si disattiva completamente lo swap, le prestazioni possono ridursi notevolmente.




