---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: Per difendersi dagli attacchi, è necessario mantenere aggiornati il ​​sistema StorageGRID e i servizi correlati. 
---
= Linee guida per il rafforzamento degli aggiornamenti software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per difendersi dagli attacchi, è necessario mantenere aggiornati il ​​sistema StorageGRID e i servizi correlati.



== Aggiornamenti al software StorageGRID

Se possibile, è consigliabile aggiornare il software StorageGRID alla versione principale più recente o a quella precedente.  Mantenere StorageGRID aggiornato aiuta a ridurre il tempo di attività delle vulnerabilità note e riduce la superficie complessiva di attacco.  Inoltre, le versioni più recenti di StorageGRID spesso contengono funzionalità di rafforzamento della sicurezza non incluse nelle versioni precedenti.

Consultare il https://imt.netapp.com/matrix/#welcome["Strumento matrice di interoperabilità NetApp"^] (IMT) per determinare quale versione del software StorageGRID dovresti utilizzare.  Quando è necessario un hotfix, NetApp dà priorità alla creazione di aggiornamenti per le versioni più recenti.  Alcune patch potrebbero non essere compatibili con le versioni precedenti.

* Per scaricare le versioni e gli hotfix più recenti StorageGRID , vai a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Download NetApp : StorageGRID"^] .
* Per aggiornare il software StorageGRID , vederelink:../upgrade/performing-upgrade.html["istruzioni per l'aggiornamento"] .
* Per applicare un hotfix, vederelink:../maintain/storagegrid-hotfix-procedure.html["Procedura di hotfix di StorageGRID"] .




== Aggiornamenti ai servizi esterni

I servizi esterni possono presentare vulnerabilità che influiscono indirettamente StorageGRID . È necessario assicurarsi che i servizi da cui dipende StorageGRID siano sempre aggiornati. Questi servizi includono LDAP, KMS (o server KMIP), DNS e NTP.

Per un elenco delle versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Strumento matrice di interoperabilità NetApp"^] .



== Aggiornamenti agli hypervisor

Se i nodi StorageGRID sono in esecuzione su VMware o su un altro hypervisor, è necessario assicurarsi che il software e il firmware dell'hypervisor siano aggiornati.

Per un elenco delle versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Strumento matrice di interoperabilità NetApp"^] .



== *Aggiornamenti ai nodi Linux*

Se i nodi StorageGRID utilizzano piattaforme host Linux, è necessario assicurarsi che gli aggiornamenti di sicurezza e del kernel vengano applicati al sistema operativo host.  Inoltre, è necessario applicare gli aggiornamenti del firmware all'hardware vulnerabile quando questi aggiornamenti diventano disponibili.

Per un elenco delle versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Strumento matrice di interoperabilità NetApp"^] .
