---
permalink: network/external-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, external communications, ports, TCP, UDP, client communications 
summary: I client devono comunicare con i nodi della griglia per acquisire e recuperare i contenuti.  Le porte utilizzate dipendono dai protocolli di archiviazione degli oggetti scelti.  Queste porte devono essere accessibili al client. 
---
= Comunicazioni esterne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I client devono comunicare con i nodi della griglia per acquisire e recuperare i contenuti.  Le porte utilizzate dipendono dai protocolli di archiviazione degli oggetti scelti.  Queste porte devono essere accessibili al client.



== Accesso limitato ai porti

Se i criteri di rete aziendale limitano l'accesso a una qualsiasi delle porte, è possibile procedere in uno dei seguenti modi:

* Utilizzolink:../admin/configuring-load-balancer-endpoints.html["endpoint del bilanciatore del carico"] per consentire l'accesso alle porte definite dall'utente.
* Riassegnare le porte durante la distribuzione dei nodi.  Tuttavia, non dovresti rimappare gli endpoint del bilanciatore del carico.  Consulta le informazioni sulla rimappatura delle porte per il tuo nodo StorageGRID :
+
** link:../rhel/creating-node-configuration-files.html#port-remap-keys["Chiavi di rimappatura delle porte per StorageGRID su Red Hat Enterprise Linux"]
** link:../ubuntu/creating-node-configuration-files.html#port-remap-keys["Chiavi di rimappatura delle porte per StorageGRID su Ubuntu o Debian"]
** link:../vmware/deploying-storagegrid-node-as-virtual-machine.html#vmware-remap-ports["Riassegna le porte per StorageGRID su VMware"]
** https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["Facoltativo: rimappare le porte di rete per l'appliance"^]






== Porte utilizzate per le comunicazioni esterne

La tabella seguente mostra le porte utilizzate per il traffico verso i nodi.


NOTE: Questo elenco non include le porte che potrebbero essere configurate comelink:../admin/configuring-load-balancer-endpoints.html["endpoint del bilanciatore del carico"] .

[cols="1a,1a,1a,1a,1a,4a"]
|===
| Porta | TCP o UDP | Protocollo | Da | A | Dettagli 


 a| 
22
 a| 
TCP
 a| 
SSH
 a| 
Computer portatile di servizio
 a| 
Tutti i nodi
 a| 
Per le procedure con passaggi della console è richiesto l'accesso SSH o alla console.  Facoltativamente, è possibile utilizzare la porta 2022 anziché la 22.



 a| 
25
 a| 
TCP
 a| 
SMTP
 a| 
Nodi amministrativi
 a| 
Server di posta elettronica
 a| 
Utilizzato per avvisi e AutoSupport basato su e-mail.  È possibile ignorare l'impostazione predefinita della porta 25 utilizzando la pagina Server di posta elettronica.



 a| 
53
 a| 
TCP/UDP
 a| 
DNS
 a| 
Tutti i nodi
 a| 
server DNS
 a| 
Utilizzato per DNS.



 a| 
67
 a| 
UDP
 a| 
DHCP
 a| 
Tutti i nodi
 a| 
Servizio DHCP
 a| 
Utilizzato facoltativamente per supportare la configurazione di rete basata su DHCP.  Il servizio dhclient non funziona per le griglie configurate staticamente.



 a| 
68
 a| 
UDP
 a| 
DHCP
 a| 
Servizio DHCP
 a| 
Tutti i nodi
 a| 
Utilizzato facoltativamente per supportare la configurazione di rete basata su DHCP.  Il servizio dhclient non funziona per le griglie che utilizzano indirizzi IP statici.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navigatore
 a| 
Nodi amministrativi
 a| 
La porta 80 reindirizza alla porta 443 per l'interfaccia utente del nodo di amministrazione.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navigatore
 a| 
Elettrodomestici
 a| 
La porta 80 reindirizza alla porta 8443 per StorageGRID Appliance Installer.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nodi di archiviazione con ADC
 a| 
AWS
 a| 
Utilizzato per i messaggi dei servizi di piattaforma inviati ad AWS o ad altri servizi esterni che utilizzano HTTP.  I tenant possono ignorare l'impostazione predefinita della porta HTTP 80 durante la creazione di un endpoint.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nodi di archiviazione
 a| 
AWS
 a| 
Richieste di Cloud Storage Pool inviate a destinazioni AWS che utilizzano HTTP.  Gli amministratori della griglia possono ignorare l'impostazione predefinita della porta HTTP 80 durante la configurazione di un Cloud Storage Pool.



 a| 
111
 a| 
TCP/UDP
 a| 
RPCBind
 a| 
Cliente NFS
 a| 
Nodi amministrativi
 a| 
Utilizzato dall'esportazione di audit basata su NFS (portmap).

*Nota:* questa porta è richiesta solo se è abilitata l'esportazione di audit basata su NFS.

*Nota:* il supporto per NFS è stato deprecato e verrà rimosso in una versione futura.



 a| 
123
 a| 
UDP
 a| 
NTP
 a| 
Nodi NTP primari
 a| 
NTP esterno
 a| 
Servizio di protocollo di tempo di rete.  I nodi selezionati come sorgenti NTP primarie sincronizzano anche gli orari degli orologi con le sorgenti NTP esterne.



 a| 
161
 a| 
TCP/UDP
 a| 
SNMP
 a| 
Cliente SNMP
 a| 
Tutti i nodi
 a| 
Utilizzato per il polling SNMP.  Tutti i nodi forniscono informazioni di base; i nodi amministrativi forniscono anche dati di avviso.  Se configurato, il valore predefinito è la porta UDP 161.

*Nota:* questa porta è obbligatoria e viene aperta sul firewall del nodo solo se è configurato SNMP.  Se si prevede di utilizzare SNMP, è possibile configurare porte alternative.

*Nota:* per informazioni sull'utilizzo di SNMP con StorageGRID, contattare il rappresentante dell'account NetApp .



 a| 
162
 a| 
TCP/UDP
 a| 
Notifiche SNMP
 a| 
Tutti i nodi
 a| 
Destinazioni di notifica
 a| 
Le notifiche e le trap SNMP in uscita vengono impostate per impostazione predefinita sulla porta UDP 162.

*Nota:* questa porta è necessaria solo se SNMP è abilitato e sono configurate le destinazioni di notifica.  Se si prevede di utilizzare SNMP, è possibile configurare porte alternative.

*Nota:* per informazioni sull'utilizzo di SNMP con StorageGRID, contattare il rappresentante dell'account NetApp .



 a| 
389
 a| 
TCP/UDP
 a| 
LDAP
 a| 
Nodi di archiviazione con ADC
 a| 
Directory attiva/LDAP
 a| 
Utilizzato per la connessione a un server Active Directory o LDAP per la federazione delle identità.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigatore
 a| 
Nodi amministrativi
 a| 
Utilizzato dai browser Web e dai client API di gestione per accedere a Grid Manager e Tenant Manager.

*Nota*: se chiudi le porte 443 o 8443 di Grid Manager, tutti gli utenti attualmente connessi su una porta bloccata, incluso te, perderanno l'accesso a Grid Manager, a meno che il loro indirizzo IP non sia stato aggiunto all'elenco degli indirizzi privilegiati. Fare riferimento alink:../admin/configure-firewall-controls.html["Configurare i controlli del firewall"] per configurare indirizzi IP privilegiati.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nodi amministrativi
 a| 
Directory attiva
 a| 
Utilizzato dai nodi di amministrazione che si connettono ad Active Directory se è abilitato l'accesso singolo (SSO).



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nodi di archiviazione con ADC
 a| 
AWS
 a| 
Utilizzato per i messaggi dei servizi di piattaforma inviati ad AWS o ad altri servizi esterni che utilizzano HTTPS.  I tenant possono sovrascrivere l'impostazione predefinita della porta HTTP 443 durante la creazione di un endpoint.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nodi di archiviazione
 a| 
AWS
 a| 
Richieste di Cloud Storage Pool inviate a destinazioni AWS che utilizzano HTTPS.  Gli amministratori della griglia possono ignorare l'impostazione predefinita della porta HTTPS 443 durante la configurazione di un Cloud Storage Pool.



 a| 
903
 a| 
TCP
 a| 
NFS
 a| 
Cliente NFS
 a| 
Nodi amministrativi
 a| 
Utilizzato dall'esportazione di audit basata su NFS(`rpc.mountd` ).

*Nota:* questa porta è richiesta solo se è abilitata l'esportazione di audit basata su NFS.

*Nota:* il supporto per NFS è stato deprecato e verrà rimosso in una versione futura.



 a| 
2022
 a| 
TCP
 a| 
SSH
 a| 
Computer portatile di servizio
 a| 
Tutti i nodi
 a| 
Per le procedure con passaggi della console è richiesto l'accesso SSH o alla console.  Facoltativamente, è possibile utilizzare la porta 22 anziché la 2022.



 a| 
2049
 a| 
TCP
 a| 
NFS
 a| 
Cliente NFS
 a| 
Nodi amministrativi
 a| 
Utilizzato dall'esportazione di audit basata su NFS (nfs).

*Nota:* questa porta è richiesta solo se è abilitata l'esportazione di audit basata su NFS.

*Nota:* il supporto per NFS è stato deprecato e verrà rimosso in una versione futura.



 a| 
5353
 a| 
UDP
 a| 
mDNS
 a| 
Tutti i nodi
 a| 
Tutti i nodi
 a| 
Fornisce il servizio DNS multicast (mDNS) utilizzato per le modifiche IP dell'intera griglia e per l'individuazione del nodo di amministrazione primario durante l'installazione, l'espansione e il ripristino.



 a| 
5696
 a| 
TCP
 a| 
KMIP
 a| 
Apparecchio
 a| 
Chilometri
 a| 
Traffico esterno del protocollo KMIP (Key Management Interoperability Protocol) dagli apparecchi configurati per la crittografia dei nodi al Key Management Server (KMS), a meno che non venga specificata una porta diversa nella pagina di configurazione KMS del programma di installazione dell'apparecchio StorageGRID .



 a| 
8022
 a| 
TCP
 a| 
SSH
 a| 
Computer portatile di servizio
 a| 
Tutti i nodi
 a| 
SSH sulla porta 8022 garantisce l'accesso al sistema operativo di base sulle piattaforme appliance e nodi virtuali per supporto e risoluzione dei problemi.  Questa porta non viene utilizzata per i nodi basati su Linux (bare metal) e non è necessario che sia accessibile tra i nodi della griglia o durante le normali operazioni.



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigatore
 a| 
Nodi amministrativi
 a| 
Opzionale. Utilizzato dai browser Web e dai client API di gestione per accedere a Grid Manager. Può essere utilizzato per separare le comunicazioni tra Grid Manager e Tenant Manager.

*Nota*: se chiudi le porte 443 o 8443 di Grid Manager, tutti gli utenti attualmente connessi su una porta bloccata, incluso te, perderanno l'accesso a Grid Manager, a meno che il loro indirizzo IP non sia stato aggiunto all'elenco degli indirizzi privilegiati. Fare riferimento alink:../admin/configure-firewall-controls.html["Configurare i controlli del firewall"] per configurare indirizzi IP privilegiati.



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigatore
 a| 
Elettrodomestici
 a| 
Utilizzato dai browser Web e dai client API di gestione per accedere al programma di installazione dell'appliance StorageGRID .

*Nota*: la porta 443 reindirizza alla porta 8443 per StorageGRID Appliance Installer.



 a| 
9022
 a| 
TCP
 a| 
SSH
 a| 
Computer portatile di servizio
 a| 
Elettrodomestici
 a| 
Concede l'accesso agli apparecchi StorageGRID in modalità di preconfigurazione per supporto e risoluzione dei problemi.  Non è necessario che questa porta sia accessibile tra i nodi della griglia o durante le normali operazioni.



 a| 
9091
 a| 
TCP
 a| 
HTTPS
 a| 
Servizio Grafana esterno
 a| 
Nodi amministrativi
 a| 
Utilizzato dai servizi Grafana esterni per l'accesso sicuro al servizio StorageGRID Prometheus.

*Nota:* questa porta è richiesta solo se è abilitato l'accesso Prometheus basato su certificato.



 a| 
9092
 a| 
TCP
 a| 
Kafka
 a| 
Nodi di archiviazione con ADC
 a| 
Cluster di Kafka
 a| 
Utilizzato per i messaggi dei servizi di piattaforma inviati a un cluster Kafka.  I tenant possono sovrascrivere l'impostazione predefinita della porta Kafka pari a 9092 durante la creazione di un endpoint.



 a| 
9443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigatore
 a| 
Nodi amministrativi
 a| 
Opzionale. Utilizzato dai browser Web e dai client API di gestione per accedere a Tenant Manager. Può essere utilizzato per separare le comunicazioni tra Grid Manager e Tenant Manager.



 a| 
18082
 a| 
TCP
 a| 
HTTPS
 a| 
Clienti S3
 a| 
Nodi di archiviazione
 a| 
Traffico client S3 direttamente ai nodi di archiviazione (HTTPS).



 a| 
18083
 a| 
TCP
 a| 
HTTPS
 a| 
Clienti rapidi
 a| 
Nodi di archiviazione
 a| 
Traffico client rapido direttamente ai nodi di archiviazione (HTTPS).



 a| 
18084
 a| 
TCP
 a| 
HTTP
 a| 
Clienti S3
 a| 
Nodi di archiviazione
 a| 
Traffico client S3 direttamente ai nodi di archiviazione (HTTP).



 a| 
18085
 a| 
TCP
 a| 
HTTP
 a| 
Clienti rapidi
 a| 
Nodi di archiviazione
 a| 
Traffico client rapido direttamente ai nodi di archiviazione (HTTP).



 a| 
23000-23999
 a| 
TCP
 a| 
HTTPS
 a| 
Tutti i nodi sulla griglia di origine per la replica tra griglie
 a| 
Nodi amministrativi e nodi gateway sulla griglia di destinazione per la replica tra griglie
 a| 
Questo intervallo di porte è riservato alle connessioni della federazione di rete.  Entrambe le griglie in una determinata connessione utilizzano la stessa porta.

|===