---
permalink: network/network-installation-and-provisioning.html 
sidebar: sidebar 
keywords: network install, network provisioning 
summary: È necessario comprendere come vengono utilizzate la rete Grid e le reti Admin e Client opzionali durante la distribuzione dei nodi e la configurazione della griglia. 
---
= Installazione e provisioning della rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario comprendere come vengono utilizzate la rete Grid e le reti Admin e Client opzionali durante la distribuzione dei nodi e la configurazione della griglia.



== Distribuzione iniziale di un nodo

Quando si distribuisce un nodo per la prima volta, è necessario collegarlo alla rete Grid e assicurarsi che abbia accesso al nodo di amministrazione primario.  Se la rete Grid è isolata, è possibile configurare la rete di amministrazione sul nodo di amministrazione primario per l'accesso alla configurazione e all'installazione dall'esterno della rete Grid.

Una rete Grid con un gateway configurato diventa il gateway predefinito per un nodo durante la distribuzione.  Il gateway predefinito consente ai nodi della griglia su subnet separate di comunicare con il nodo di amministrazione primario prima che la griglia sia stata configurata.

Se necessario, anche le subnet contenenti server NTP o che richiedono l'accesso a Grid Manager o all'API possono essere configurate come subnet di griglia.



== Registrazione automatica del nodo con il nodo amministratore primario

Dopo essere stati distribuiti, i nodi si registrano presso il nodo di amministrazione primario tramite la rete Grid.  È quindi possibile utilizzare Grid Manager, il `configure-storagegrid.py` Script Python o API di installazione per configurare la griglia e approvare i nodi registrati.  Durante la configurazione della griglia, è possibile configurare più subnet della griglia.  Una volta completata la configurazione della griglia, su ciascun nodo verranno creati percorsi statici verso queste subnet tramite il gateway Grid Network.



== Disabilitazione della rete amministrativa o della rete client

Se si desidera disabilitare la rete amministrativa o la rete client, è possibile rimuovere la configurazione da esse durante il processo di approvazione del nodo oppure è possibile utilizzare lo strumento Modifica IP al termine dell'installazione (vederelink:../maintain/configuring-ip-addresses.html["Configurare gli indirizzi IP"] ).
