---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords: networking for platform services, networking for cloud storage pools 
summary: Se si prevede di utilizzare i servizi della piattaforma StorageGRID o i pool di archiviazione cloud, è necessario configurare la rete grid e i firewall per garantire che gli endpoint di destinazione siano raggiungibili. 
---
= Networking e porte per servizi di piattaforma e pool di archiviazione cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si prevede di utilizzare i servizi della piattaforma StorageGRID o i pool di archiviazione cloud, è necessario configurare la rete grid e i firewall per garantire che gli endpoint di destinazione siano raggiungibili.



== Networking per servizi di piattaforma

Come descritto inlink:../admin/manage-platform-services-for-tenants.html["Gestire i servizi della piattaforma per gli inquilini"] Elink:../tenant/considerations-for-platform-services.html["Gestire i servizi della piattaforma"] , i servizi della piattaforma includono servizi esterni che forniscono integrazione di ricerca, notifica di eventi e replica CloudMirror.

I servizi della piattaforma richiedono l'accesso dai nodi di archiviazione che ospitano il servizio StorageGRID ADC agli endpoint del servizio esterno.  Esempi di fornitura di accesso includono:

* Sui nodi di archiviazione con servizi ADC, configurare reti amministrative univoche con voci AESL che instradano verso gli endpoint di destinazione.
* Affidati al percorso predefinito fornito da una rete client.  Se si utilizza il percorso predefinito, è possibile utilizzarelink:../admin/manage-firewall-controls.html["funzionalità di rete client non attendibile"] per limitare le connessioni in entrata.




== Networking per pool di archiviazione cloud

I pool di archiviazione cloud richiedono inoltre l'accesso dai nodi di archiviazione agli endpoint forniti dal servizio esterno utilizzato, ad esempio Amazon S3 Glacier o Microsoft Azure Blob Storage. Per informazioni, vederelink:../ilm/what-cloud-storage-pool-is.html["Che cos'è un Cloud Storage Pool"] .



== Porte per servizi di piattaforma e pool di archiviazione cloud

Per impostazione predefinita, i servizi della piattaforma e le comunicazioni del Cloud Storage Pool utilizzano le seguenti porte:

* *80*: Per gli URI degli endpoint che iniziano con `http`
* *443*: Per gli URI degli endpoint che iniziano con `https`


È possibile specificare una porta diversa quando si crea o si modifica l'endpoint. Vedere link:internal-grid-node-communications.html["Riferimento porta di rete"] .

Se si utilizza un server proxy non trasparente, è necessario anchelink:../admin/configuring-storage-proxy-settings.html["configurare le impostazioni del proxy di archiviazione"] per consentire l'invio di messaggi a endpoint esterni, ad esempio un endpoint su Internet.



== VLAN e servizi di piattaforma e pool di archiviazione cloud

Non è possibile utilizzare reti VLAN per servizi di piattaforma o pool di archiviazione cloud.  Gli endpoint di destinazione devono essere raggiungibili tramite la rete Grid, Admin o Client.
