= Trova il nome host per il nodo di archiviazione
:allow-uri-read: 




== Trova il nome host per il nodo di archiviazione

. Accedi al nodo di amministrazione principale:
+
.. Immettere il seguente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.
+
Quando si accede come root, il prompt cambia da `$` A `#` .



. Utilizzare il `/etc/hosts` file per trovare il nome host del nodo di archiviazione per i volumi di archiviazione ripristinati.  Per visualizzare un elenco di tutti i nodi nella griglia, immettere quanto segue: `cat /etc/hosts` .




== Ripara i dati se tutti i volumi sono falliti

Se tutti i volumi di archiviazione sono guasti, riparare l'intero nodo.  Seguire le istruzioni per i *dati replicati*, i *dati con codice di cancellazione (EC)* o entrambi, a seconda che si utilizzino dati replicati, dati con codice di cancellazione (EC) o entrambi.

Se solo alcuni volumi sono falliti, vai a<<Riparare i dati se solo alcuni volumi sono falliti>> .


NOTE: Non puoi correre `repair-data` operazioni per più di un nodo contemporaneamente.  Per recuperare più nodi, contattare l'assistenza tecnica.

[role="tabbed-block"]
====
.Dati replicati
--
Se la griglia include dati replicati, utilizzare `repair-data start-replicated-node-repair` comando con il `--nodes` opzione, dove `--nodes` è il nome host (nome del sistema) per riparare l'intero nodo di archiviazione.

Questo comando ripara i dati replicati su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: Quando i dati degli oggetti vengono ripristinati, viene attivato l'avviso *Oggetti persi* se il sistema StorageGRID non riesce a individuare i dati degli oggetti replicati. Gli avvisi potrebbero essere attivati ​​sui nodi di archiviazione in tutto il sistema. Dovresti determinare la causa della perdita e se è possibile un recupero. Vedere link:../troubleshoot/investigating-lost-objects.html["Indagare sugli oggetti smarriti"] .

--
.Dati con codice di cancellazione (EC)
--
Se la griglia contiene dati con codice di cancellazione, utilizzare `repair-data start-ec-node-repair` comando con il `--nodes` opzione, dove `--nodes` è il nome host (nome del sistema) per riparare l'intero nodo di archiviazione.

Questo comando ripara i dati codificati in modo da essere cancellati su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

L'operazione restituisce un valore univoco `repair ID` che identifica questo `repair_data` operazione.  Usa questo `repair ID` per monitorare i progressi e i risultati del `repair_data` operazione.  Non verrà restituito alcun altro feedback una volta completato il processo di recupero.

Le riparazioni dei dati codificati in modo da essere cancellati possono iniziare mentre alcuni nodi di archiviazione sono offline.  La riparazione verrà completata quando tutti i nodi saranno disponibili.

--
====


== Riparare i dati se solo alcuni volumi sono falliti

Se solo alcuni volumi sono guasti, riparare i volumi interessati.  Seguire le istruzioni per i *dati replicati*, i *dati con codice di cancellazione (EC)* o entrambi, a seconda che si utilizzino dati replicati, dati con codice di cancellazione (EC) o entrambi.

Se tutti i volumi sono falliti, vai a<<Ripara i dati se tutti i volumi sono falliti>> .

Immettere gli ID del volume in formato esadecimale.  Per esempio, `0000` è il primo volume e `000F` è il sedicesimo volume.  È possibile specificare un volume, un intervallo di volumi o più volumi non in sequenza.

Tutti i volumi devono trovarsi sullo stesso nodo di archiviazione.  Se è necessario ripristinare volumi per più di un nodo di archiviazione, contattare l'assistenza tecnica.

[role="tabbed-block"]
====
.Dati replicati
--
Se la griglia contiene dati replicati, utilizzare `start-replicated-volume-repair` comando con il `--nodes` opzione per identificare il nodo (dove `--nodes` è il nome host del nodo).  Quindi aggiungere o il `--volumes` O `--volume-range` opzione, come mostrato negli esempi seguenti.

*Volume singolo*: questo comando ripristina i dati replicati nel volume `0002` su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*Intervallo di volumi*: questo comando ripristina i dati replicati su tutti i volumi nell'intervallo `0003` A `0009` su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*Volumi multipli non in sequenza*: questo comando ripristina i dati replicati nei volumi `0001` , `0005` , E `0008` su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: Quando i dati degli oggetti vengono ripristinati, viene attivato l'avviso *Oggetti persi* se il sistema StorageGRID non riesce a individuare i dati degli oggetti replicati. Gli avvisi potrebbero essere attivati ​​sui nodi di archiviazione in tutto il sistema. Prendere nota della descrizione dell'avviso e delle azioni consigliate per determinare la causa della perdita e se è possibile un recupero.

--
.Dati con codice di cancellazione (EC)
--
Se la griglia contiene dati con codice di cancellazione, utilizzare `start-ec-volume-repair` comando con il `--nodes` opzione per identificare il nodo (dove `--nodes` è il nome host del nodo).  Quindi aggiungere o il `--volumes` O `--volume-range` opzione, come mostrato negli esempi seguenti.

*Volume singolo*: questo comando ripristina i dati codificati in cancellazione nel volume `0007` su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*Intervallo di volumi*: questo comando ripristina i dati codificati in cancellazione su tutti i volumi nell'intervallo `0004` A `0006` su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*Volumi multipli non in sequenza*: questo comando ripristina i dati codificati in cancellazione nei volumi `000A` , `000C` , E `000E` su un nodo di archiviazione denominato SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

IL `repair-data` l'operazione restituisce un valore univoco `repair ID` che identifica questo `repair_data` operazione.  Usa questo `repair ID` per monitorare i progressi e i risultati del `repair_data` operazione.  Non verrà restituito alcun altro feedback una volta completato il processo di recupero.


NOTE: Le riparazioni dei dati codificati in modo da essere cancellati possono iniziare mentre alcuni nodi di archiviazione sono offline.  La riparazione verrà completata quando tutti i nodi saranno disponibili.

--
====