---
permalink: tenant/configuring-event-notifications.html 
sidebar: sidebar 
keywords: how to configure event notifications, bucket notification 
summary: 'È possibile abilitare le notifiche per un bucket creando un XML di configurazione delle notifiche e utilizzando Tenant Manager per applicare l"XML a un bucket.' 
---
= Configurare le notifiche degli eventi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile abilitare le notifiche per un bucket creando un XML di configurazione delle notifiche e utilizzando Tenant Manager per applicare l'XML a un bucket.

.Prima di iniziare
* I servizi della piattaforma sono stati abilitati per il tuo account tenant da un amministratore StorageGRID .
* Hai già creato un bucket che fungerà da fonte di notifiche.
* L'endpoint che intendi utilizzare come destinazione per le notifiche degli eventi esiste già e disponi del relativo URN.
* Appartieni a un gruppo di utenti che ha illink:tenant-management-permissions.html["Gestisci tutti i bucket o l'autorizzazione di accesso Root"] .  Queste autorizzazioni sostituiscono le impostazioni delle autorizzazioni nei criteri di gruppo o di bucket quando si configura il bucket tramite Tenant Manager.


.Informazioni su questo compito
È possibile configurare le notifiche degli eventi associando l'XML di configurazione delle notifiche a un bucket di origine. Il codice XML di configurazione delle notifiche segue le convenzioni S3 per la configurazione delle notifiche dei bucket, con l'argomento di destinazione Kafka o Amazon SNS specificato come URN di un endpoint.

Per informazioni generali sulle notifiche degli eventi e su come configurarle, fare riferimento a https://docs.aws.amazon.com/s3/["Documentazione Amazon"^] .  Per informazioni su come StorageGRID implementa l'API di configurazione delle notifiche del bucket S3, fare riferimento alink:../s3/index.html["istruzioni per l'implementazione di applicazioni client S3"] .

Quando si configurano le notifiche degli eventi per un bucket, tenere presente i seguenti requisiti e caratteristiche:

* Quando si crea e si applica un XML di configurazione delle notifiche valido, è necessario utilizzare l'URN di un endpoint delle notifiche degli eventi per ciascuna destinazione.
* Sebbene la notifica degli eventi possa essere configurata su un bucket con S3 Object Lock abilitato, i metadati di S3 Object Lock (inclusi gli stati Conserva fino alla data e Conservazione legale) degli oggetti non saranno inclusi nei messaggi di notifica.
* Dopo aver configurato le notifiche degli eventi, ogni volta che si verifica un evento specifico per un oggetto nel bucket di origine, viene generata una notifica e inviata all'argomento Amazon SNS o Kafka utilizzato come endpoint di destinazione.
* Se si abilitano le notifiche degli eventi per un bucket che contiene oggetti, le notifiche vengono inviate solo per le azioni eseguite dopo il salvataggio della configurazione delle notifiche.


.Passi
. Abilita le notifiche per il tuo bucket di origine:
+
** Utilizzare un editor di testo per creare il file XML di configurazione delle notifiche necessario per abilitare le notifiche degli eventi, come specificato nell'API di notifica S3.
** Durante la configurazione dell'XML, utilizzare l'URN di un endpoint di notifiche degli eventi come argomento di destinazione.
+
[listing]
----
<NotificationConfiguration>
  <TopicConfiguration>
     <Id>Image-created</Id>
     <Filter>
        <S3Key>
          <FilterRule>
            <Name>prefix</Name>
            <Value>images/</Value>
          </FilterRule>
        </S3Key>
    </Filter>
    <Topic>arn:aws:sns:us-east-1:050340950352:sgws-topic</Topic>
    <Event>s3:ObjectCreated:*</Event>
   </TopicConfiguration>
 </NotificationConfiguration>
----


. In Tenant Manager, seleziona *ARCHIVIAZIONE (S3)* > *Bucket*.
. Selezionare il nome del bucket di origine.
+
Viene visualizzata la pagina dei dettagli del bucket.

. Selezionare *Servizi piattaforma* > *Notifiche eventi*.
. Seleziona la casella di controllo *Abilita notifiche eventi*.
. Incolla il file XML di configurazione delle notifiche nella casella di testo e seleziona *Salva modifiche*.
+

NOTE: I servizi della piattaforma devono essere abilitati per ciascun account tenant da un amministratore StorageGRID tramite Grid Manager o Grid Management API.  Se si verifica un errore durante il salvataggio del file XML di configurazione, contattare l'amministratore StorageGRID .

. Verificare che le notifiche degli eventi siano configurate correttamente:
+
.. Eseguire un'azione su un oggetto nel bucket di origine che soddisfi i requisiti per l'attivazione di una notifica come configurato nell'XML di configurazione.
+
Nell'esempio, una notifica di evento viene inviata ogni volta che un oggetto viene creato con `images/` prefisso.

.. Conferma che una notifica è stata recapitata all'argomento Amazon SNS o Kafka di destinazione.
+
Ad esempio, se l'argomento di destinazione è ospitato su Amazon SNS, puoi configurare il servizio in modo che ti venga inviata un'e-mail quando la notifica viene recapitata.

+
[listing]
----
{
   "Records":[
      {
         "eventVersion":"2.0",
         "eventSource":"sgws:s3",
         "eventTime":"2017-08-08T23:52:38Z",
         "eventName":"ObjectCreated:Put",
         "userIdentity":{
            "principalId":"1111111111111111111"
         },
         "requestParameters":{
            "sourceIPAddress":"193.51.100.20"
         },
         "responseElements":{
            "x-amz-request-id":"122047343"
         },
         "s3":{
            "s3SchemaVersion":"1.0",
            "configurationId":"Image-created",
            "bucket":{
               "name":"test1",
               "ownerIdentity":{
                  "principalId":"1111111111111111111"
               },
               "arn":"arn:sgws:s3:::test1"
            },
            "object":{
               "key":"images/cat.jpg",
               "size":0,
               "eTag":"d41d8cd98f00b204e9800998ecf8427e",
               "sequencer":"14D90402421461C7"
            }
         }
      }
   ]
}
----
+
Se la notifica viene ricevuta nell'argomento di destinazione, il bucket di origine è stato configurato correttamente per le notifiche StorageGRID .





.Informazioni correlate
link:understanding-notifications-for-buckets.html["Comprendere le notifiche per i bucket"]

link:../s3/index.html["Utilizzare l'API REST S3"]

link:creating-platform-services-endpoint.html["Crea endpoint dei servizi della piattaforma"]
