---
permalink: tenant/deleting-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete access key for other user 
summary: 'Se si utilizza un tenant S3 e si dispone delle autorizzazioni appropriate, è possibile eliminare le chiavi di accesso S3 di un altro utente.  Dopo aver eliminato una chiave di accesso, non sarà più possibile utilizzarla per accedere agli oggetti e ai bucket nell"account tenant.' 
---
= Elimina le chiavi di accesso S3 di un altro utente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza un tenant S3 e si dispone delle autorizzazioni appropriate, è possibile eliminare le chiavi di accesso S3 di un altro utente.  Dopo aver eliminato una chiave di accesso, non sarà più possibile utilizzarla per accedere agli oggetti e ai bucket nell'account tenant.

.Prima di iniziare
* Hai effettuato l'accesso al Tenant Manager tramite unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:tenant-management-permissions.html["Permesso di accesso root"] .



CAUTION: È possibile accedere ai bucket e agli oggetti S3 appartenenti a un utente utilizzando l'ID della chiave di accesso e la chiave di accesso segreta visualizzati per quell'utente in Tenant Manager.  Per questo motivo, proteggi le chiavi di accesso come faresti con una password.  Ruotare regolarmente le chiavi di accesso, rimuovere dall'account quelle non utilizzate e non condividerle mai con altri utenti.

.Passi
. Selezionare *GESTIONE ACCESSI* > *Utenti*.
. Dalla pagina Utenti, seleziona l'utente di cui desideri gestire le chiavi di accesso S3.
. Dalla pagina Dettagli utente, seleziona *Chiavi di accesso*, quindi seleziona la casella di controllo per ogni chiave di accesso che desideri eliminare.
. Selezionare *Azioni* > *Elimina chiave selezionata*.
. Nella finestra di dialogo di conferma, seleziona *Elimina chiave*.
+
Nell'angolo in alto a destra della pagina appare un messaggio di conferma.


