---
permalink: tenant/deleting-s3-bucket.html 
sidebar: sidebar 
keywords: how to delete S3 bucket 
summary: È possibile utilizzare Tenant Manager per eliminare un bucket S3 vuoto. 
---
= Elimina bucket S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Tenant Manager per eliminare uno o più bucket S3 vuoti.

.Prima di iniziare
* Hai effettuato l'accesso al Tenant Manager tramite unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Appartieni a un gruppo di utenti che ha illink:tenant-management-permissions.html["Gestisci tutti i bucket o l'autorizzazione di accesso Root"] . Queste autorizzazioni sovrascrivono le impostazioni delle autorizzazioni nei criteri di gruppo o di bucket.
* I bucket che vuoi eliminare sono vuoti.  Se i bucket che vuoi eliminare _non_ sono vuoti,link:../tenant/deleting-s3-bucket-objects.html["elimina gli oggetti dal bucket"] .


.Informazioni su questo compito
Queste istruzioni descrivono come eliminare un bucket S3 utilizzando Tenant Manager.  È anche possibile eliminare i bucket S3 utilizzandolink:understanding-tenant-management-api.html["API di gestione degli inquilini"] o illink:../s3/operations-on-buckets.html["API REST S3"] .

Non è possibile eliminare un bucket S3 se contiene oggetti, versioni di oggetti non correnti o marcatori di eliminazione.  Per informazioni su come vengono eliminati gli oggetti con versione S3, vederelink:../ilm/how-objects-are-deleted.html["Come vengono eliminati gli oggetti"] .

.Passi
. Selezionare *Visualizza bucket* dalla dashboard oppure selezionare *ARCHIVIAZIONE (S3)* > *Bucket*.
+
Viene visualizzata la pagina Bucket, che mostra tutti i bucket S3 esistenti.

. Utilizzare il menu *Azioni* o la pagina dei dettagli per un bucket specifico.
+
[role="tabbed-block"]
====
.Menu Azioni
--
.. Seleziona la casella di controllo per ogni bucket che desideri eliminare.
.. Selezionare *Azioni* > *Elimina bucket*.


--
.Pagina dei dettagli
--
.. Seleziona il nome di un bucket per visualizzarne i dettagli.
.. Seleziona *Elimina bucket*.


--
====
. Quando viene visualizzata la finestra di dialogo di conferma, selezionare *Sì*.
+
StorageGRID conferma che ogni bucket è vuoto e quindi lo elimina.  Questa operazione potrebbe richiedere alcuni minuti.

+
Se un bucket non è vuoto, viene visualizzato un messaggio di errore.  Devilink:../tenant/deleting-s3-bucket-objects.html["elimina tutti gli oggetti e tutti i marcatori di eliminazione nel bucket"] prima di poter eliminare il bucket.


