---
permalink: tenant/managing-s3-access-keys.html 
sidebar: sidebar 
keywords: how to manage s3 access key 
summary: Ogni utente di un account tenant S3 deve disporre di una chiave di accesso per archiviare e recuperare oggetti nel sistema StorageGRID .  Una chiave di accesso è composta da un ID chiave di accesso e da una chiave di accesso segreta. 
---
= Gestisci le chiavi di accesso S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni utente di un account tenant S3 deve disporre di una chiave di accesso per archiviare e recuperare oggetti nel sistema StorageGRID .  Una chiave di accesso è composta da un ID chiave di accesso e da una chiave di accesso segreta.

Le chiavi di accesso S3 possono essere gestite come segue:

* Gli utenti che dispongono dell'autorizzazione *Gestisci le tue credenziali S3* possono creare o rimuovere le proprie chiavi di accesso S3.
* Gli utenti che dispongono dell'autorizzazione *Accesso root* possono gestire le chiavi di accesso per l'account root S3 e per tutti gli altri utenti.  Le chiavi di accesso root forniscono l'accesso completo a tutti i bucket e oggetti per il tenant, a meno che non siano disabilitate esplicitamente da un criterio di bucket.


StorageGRID supporta l'autenticazione Signature Version 2 e Signature Version 4.  L'accesso tra account non è consentito, a meno che non sia esplicitamente abilitato da un criterio bucket.
