---
permalink: tenant/understanding-notifications-for-buckets.html 
sidebar: sidebar 
keywords: s3 bucket event notification, sequencer key 
summary: È possibile abilitare la notifica degli eventi per un bucket S3 se si desidera che StorageGRID invii notifiche su eventi specifici a un cluster Kafka di destinazione o ad Amazon Simple Notification Service. 
---
= Comprendere le notifiche per i bucket
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile abilitare la notifica degli eventi per un bucket S3 se si desidera che StorageGRID invii notifiche su eventi specifici a un cluster Kafka di destinazione o ad Amazon Simple Notification Service.

Ad esempio, è possibile configurare l'invio di avvisi agli amministratori per ogni oggetto aggiunto a un bucket, dove gli oggetti rappresentano file di registro associati a un evento di sistema critico.

Le notifiche degli eventi vengono create nel bucket di origine come specificato nella configurazione delle notifiche e vengono recapitate alla destinazione.  Se un evento associato a un oggetto ha esito positivo, viene creata una notifica relativa a tale evento e messa in coda per la consegna.

L'unicità e l'ordinamento delle notifiche non sono garantiti.  A seguito delle operazioni intraprese per garantire il successo della consegna, potrebbero essere recapitate alla destinazione più notifiche relative a un evento.  Poiché la consegna è asincrona, non è garantito che l'ordinamento temporale delle notifiche a destinazione corrisponda all'ordinamento degli eventi nel bucket di origine, in particolare per le operazioni che hanno origine da siti StorageGRID diversi.  Puoi usare il `sequencer` digitare nel messaggio dell'evento per determinare l'ordine degli eventi per un oggetto specifico, come descritto nella documentazione di Amazon S3.

Le notifiche degli eventi StorageGRID seguono l'API Amazon S3 con alcune limitazioni.

* Sono supportati i seguenti tipi di eventi:
+
** s3:OggettoCreato:
** s3:OggettoCreato:Metti
** s3:OggettoCreato:Post
** s3:OggettoCreato:Copia
** s3:ObjectCreated:CompleteMultipartUpload
** s3:ObjectRemoved:
** s3:ObjectRemoved:Elimina
** s3:ObjectRemoved:DeleteMarkerCreated
** s3:ObjectRestore:Post


* Le notifiche degli eventi inviate da StorageGRID utilizzano il formato JSON standard, ma non includono alcune chiavi e utilizzano valori specifici per altre, come mostrato nella tabella:


[cols="1a,2a"]
|===
| Nome chiave | Valore StorageGRID 


 a| 
origineevento
 a| 
`sgws:s3`



 a| 
Regione aws
 a| 
_non incluso_



 a| 
x-amz-id-2
 a| 
_non incluso_



 a| 
arn
 a| 
`urn:sgws:s3:::bucket_name`

|===