---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Se hai abilitato S3 Object Lock quando hai creato il bucket, puoi modificare il bucket per cambiare le impostazioni di conservazione predefinite.  È possibile abilitare (o disabilitare) la conservazione predefinita e impostare una modalità di conservazione predefinita e un periodo di conservazione.' 
---
= Aggiorna la conservazione predefinita del blocco degli oggetti S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se hai abilitato S3 Object Lock quando hai creato il bucket, puoi modificare il bucket per cambiare le impostazioni di conservazione predefinite.  È possibile abilitare (o disabilitare) la conservazione predefinita e impostare una modalità di conservazione predefinita e un periodo di conservazione.

.Prima di iniziare
* Hai effettuato l'accesso al Tenant Manager tramite unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Appartieni a un gruppo di utenti che ha illink:tenant-management-permissions.html["Gestisci tutti i bucket o l'autorizzazione di accesso Root"] . Queste autorizzazioni sovrascrivono le impostazioni delle autorizzazioni nei criteri di gruppo o di bucket.
* S3 Object Lock è abilitato a livello globale per il sistema StorageGRID e hai abilitato S3 Object Lock quando hai creato il bucket. Vedere link:using-s3-object-lock.html["Utilizzare S3 Object Lock per conservare gli oggetti"] .


.Passi
. Selezionare *Visualizza bucket* dalla dashboard oppure selezionare *ARCHIVIAZIONE (S3)* > *Bucket*.
. Selezionare il nome del bucket dalla tabella.
+
Viene visualizzata la pagina dei dettagli del bucket.

. Dalla scheda *Opzioni bucket*, seleziona la voce accordion *Blocco oggetto S3*.
. Facoltativamente, abilita o disabilita la *Conservazione predefinita* per questo bucket.
+
Le modifiche a questa impostazione non si applicano agli oggetti già presenti nel bucket o a quelli che potrebbero avere periodi di conservazione propri.

. Se è abilitata la *Conservazione predefinita*, specificare una *Modalità di conservazione predefinita* per il bucket.
+
[cols="1a,2a"]
|===
| Modalità di conservazione predefinita | Descrizione 


 a| 
Governance
 a| 
** Utenti con il `s3:BypassGovernanceRetention` il permesso può utilizzare il `x-amz-bypass-governance-retention: true` intestazione della richiesta per ignorare le impostazioni di conservazione.
** Questi utenti possono eliminare una versione di un oggetto prima che venga raggiunta la data di conservazione.
** Questi utenti possono aumentare, diminuire o rimuovere la data di conservazione di un oggetto.




 a| 
Conformità
 a| 
** L'oggetto non può essere eliminato finché non viene raggiunta la data di conservazione.
** La data di conservazione dell'oggetto può essere aumentata, ma non diminuita.
** La data di conservazione dell'oggetto non può essere rimossa finché non viene raggiunta tale data.


*Nota*: l'amministratore della rete deve consentirti di utilizzare la modalità di conformità.

|===
. Se è abilitata l'opzione *Conservazione predefinita*, specificare il *Periodo di conservazione predefinito* per il bucket.
+
Il *Periodo di conservazione predefinito* indica per quanto tempo i nuovi oggetti aggiunti a questo bucket devono essere conservati, a partire dal momento in cui vengono acquisiti. Specificare un valore inferiore o uguale al periodo di conservazione massimo per il tenant, come impostato dall'amministratore della griglia.

+
Un periodo di conservazione _massimo_, che può essere un valore compreso tra 1 giorno e 100 anni, viene impostato quando l'amministratore della griglia crea il tenant.  Quando si imposta un periodo di conservazione _predefinito_, questo non può superare il valore impostato per il periodo di conservazione massimo.  Se necessario, chiedi all'amministratore della rete di aumentare o diminuire il periodo massimo di conservazione.

. Seleziona *Salva modifiche*.

