---
permalink: tenant/use-s3-console.html 
sidebar: sidebar 
keywords: how to use s3 console 
summary: È possibile utilizzare S3 Console per visualizzare e gestire gli oggetti in un bucket S3. 
---
= Utilizzare la console S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare S3 Console per visualizzare e gestire gli oggetti in un bucket S3.

S3 Console ti consente di:

* Carica, scarica, rinomina, copia, sposta ed elimina oggetti
* Visualizza, ripristina, scarica ed elimina le versioni degli oggetti
* Cerca oggetti per prefisso
* Gestisci i tag degli oggetti
* Visualizza i metadati dell'oggetto
* Visualizza, crea, rinomina, copia, sposta ed elimina cartelle


[NOTE]
====
S3 Console offre un'esperienza utente migliorata per i casi più comuni.  Non è progettato per sostituire le operazioni CLI o API in tutte le situazioni.

Se l'utilizzo di S3 Console fa sì che le operazioni richiedano troppo tempo (ad esempio, minuti o ore), prendere in considerazione quanto segue:

* Riduzione del numero di oggetti selezionati
* Utilizzo di metodi non grafici (API o CLI) per accedere ai dati


====
.Prima di iniziare
* Hai effettuato l'accesso al Tenant Manager tramite unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Se vuoi gestire gli oggetti, devi appartenere a un gruppo di utenti che dispone dell'autorizzazione di accesso Root.  In alternativa, puoi appartenere a un gruppo di utenti che dispone dell'autorizzazione Utilizza la scheda Console S3 e dell'autorizzazione Visualizza tutti i bucket o Gestisci tutti i bucket. Vedere link:tenant-management-permissions.html["Autorizzazioni di gestione degli inquilini"] .
* Per l'utente è stato configurato un criterio di gruppo o bucket S3. Vedere link:../s3/bucket-and-group-access-policies.html["Utilizzare criteri di accesso a bucket e gruppi"] .
* Conosci l'ID della chiave di accesso dell'utente e la chiave di accesso segreta.  Facoltativamente, hai un `.csv` file contenente queste informazioni. Vedi illink:creating-your-own-s3-access-keys.html["istruzioni per la creazione delle chiavi di accesso"] .


.Passi
. Selezionare *ARCHIVIAZIONE* > *Bucket* > *_nome bucket_*.
. Selezionare la scheda Console S3.
. Incolla l'ID della chiave di accesso e la chiave di accesso segreta nei campi.  Altrimenti, seleziona *Carica chiavi di accesso* e seleziona il tuo `.csv` file.
. Seleziona * Sign in*.
. Viene visualizzata la tabella degli oggetti bucket.  Puoi gestire gli oggetti in base alle tue esigenze.


.Informazioni aggiuntive
* *Cerca per prefisso*: la funzione di ricerca per prefisso cerca solo gli oggetti che iniziano con una parola specifica relativa alla cartella corrente.  La ricerca non include gli oggetti che contengono la parola altrove.  Questa regola si applica anche agli oggetti all'interno delle cartelle.  Ad esempio, una ricerca per `folder1/folder2/somefile-` restituirebbe oggetti che si trovano all'interno di `folder1/folder2/` cartella e inizia con la parola `somefile-` .
* *Trascinamento della selezione*: puoi trascinare e rilasciare i file dal file manager del tuo computer a S3 Console.  Tuttavia, non è possibile caricare cartelle.
* *Operazioni sulle cartelle*: quando si sposta, si copia o si rinomina una cartella, tutti gli oggetti al suo interno vengono aggiornati uno alla volta, il che potrebbe richiedere del tempo.
* *Eliminazione definitiva quando il controllo delle versioni del bucket è disabilitato*: quando si sovrascrive o si elimina un oggetto in un bucket con il controllo delle versioni disabilitato, l'operazione è definitiva. Vedere link:changing-bucket-versioning.html["Modificare il controllo delle versioni degli oggetti per un bucket"] .

