---
permalink: tenant/using-storagegrid-tenant-account.html 
sidebar: sidebar 
keywords: how to use tenant account 
summary: 'Un account tenant consente di utilizzare l"API REST Simple Storage Service \(S3\) per archiviare e recuperare oggetti in un sistema StorageGRID .' 
---
= Utilizzare l'account tenant StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un account tenant consente di utilizzare l'API REST Simple Storage Service (S3) per archiviare e recuperare oggetti in un sistema StorageGRID .

Ogni account tenant ha i propri gruppi federati o locali, utenti, bucket S3 e oggetti.


TIP: I dettagli su Swift sono stati rimossi da questa versione del sito di documentazione. Vedere https://docs.netapp.com/us-en/storagegrid-118/tenant/using-storagegrid-tenant-account.html["StorageGRID 11.8: utilizzare l'account tenant StorageGRID"^] .

Facoltativamente, è possibile utilizzare gli account tenant per separare gli oggetti archiviati da entità diverse.  Ad esempio, è possibile utilizzare più account tenant per uno qualsiasi di questi casi d'uso:

* *Caso d'uso aziendale:* se il sistema StorageGRID viene utilizzato all'interno di un'azienda, l'archiviazione degli oggetti della griglia potrebbe essere segregata dai diversi reparti dell'organizzazione.  Ad esempio, potrebbero esserci account tenant per il reparto marketing, il reparto assistenza clienti, il reparto risorse umane e così via.
+

NOTE: Se si utilizza il protocollo client S3, è possibile utilizzare anche i bucket S3 e i criteri dei bucket per separare gli oggetti tra i reparti di un'azienda. Non è necessario creare account tenant separati. Vedi le istruzioni per l'implementazionelink:../s3/bucket-and-group-access-policies.html["Bucket S3 e policy dei bucket"] per maggiori informazioni.

* *Caso d'uso del fornitore di servizi:* se il sistema StorageGRID viene utilizzato da un fornitore di servizi, l'archiviazione degli oggetti della griglia potrebbe essere segregata dalle diverse entità che affittano l'archiviazione.  Ad esempio, potrebbero esserci conti inquilino per la Società A, la Società B, la Società C e così via.




== Creare account inquilino

Gli account tenant vengono creati da un amministratore di griglia StorageGRID tramite Grid Manager.  Quando si crea un account tenant, l'amministratore della griglia specifica le seguenti informazioni:

* Nome visualizzato per il tenant (l'ID account del tenant viene assegnato automaticamente e non può essere modificato).
* Se l'account tenant utilizzerà il protocollo S3 o Swift.
* Per gli account tenant S3: se all'account tenant è consentito utilizzare i servizi della piattaforma.  Se è consentito l'uso dei servizi della piattaforma, la griglia deve essere configurata per supportarne l'uso.
* Facoltativamente, una quota di archiviazione per l'account tenant, ovvero il numero massimo di gigabyte, terabyte o petabyte disponibili per gli oggetti del tenant.  La quota di archiviazione di un tenant rappresenta una quantità logica (dimensione dell'oggetto), non una quantità fisica (dimensione su disco).
* Se la federazione delle identità è abilitata per il sistema StorageGRID , quale gruppo federato ha l'autorizzazione di accesso Root per configurare l'account tenant?
* Se per il sistema StorageGRID non è in uso l'accesso Single Sign-On (SSO), se l'account tenant utilizzerà la propria origine identità o condividerà l'origine identità della griglia e la password iniziale per l'utente root locale del tenant.


Inoltre, gli amministratori della griglia possono abilitare l'impostazione S3 Object Lock per il sistema StorageGRID se gli account tenant S3 devono essere conformi ai requisiti normativi.  Quando S3 Object Lock è abilitato, tutti gli account tenant S3 possono creare e gestire bucket conformi.



== Configurare i tenant S3

Dopo aver creato un account tenant S3, è possibile accedere a Tenant Manager per eseguire attività come le seguenti:

* Impostazione della federazione delle identità (a meno che l'origine dell'identità non sia condivisa con la griglia) o creazione di gruppi e utenti locali
* Gestione delle chiavi di accesso S3
* Creazione e gestione di bucket S3, inclusi bucket conformi
* Utilizzo dei servizi della piattaforma (se abilitati)
* Monitoraggio dell'utilizzo dello storage



TIP: Sebbene sia possibile creare e gestire bucket S3 con Tenant Manager, è necessario disporre delle chiavi di accesso S3 e utilizzare l'API REST S3 per acquisire e gestire gli oggetti.

.Informazioni correlate
* link:../admin/index.html["Amministra StorageGRID"]
* link:../s3/index.html["Utilizzare l'API REST S3"]

