---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: È possibile utilizzare VMware OVF Tool per automatizzare la distribuzione dei nodi della griglia.  È anche possibile automatizzare la configurazione di StorageGRID. 
---
= Automatizzare l'installazione (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare VMware OVF Tool per automatizzare la distribuzione dei nodi della griglia.  È anche possibile automatizzare la configurazione di StorageGRID.



== Automatizza la distribuzione dei nodi della griglia

Utilizzare lo strumento VMware OVF per automatizzare la distribuzione dei nodi della griglia.

.Prima di iniziare
* Hai accesso a un sistema Linux/Unix con Bash 3.2 o versione successiva.
* Hai VMware vSphere con vCenter
* VMware OVF Tool 4.1 è installato e configurato correttamente.
* Conosci il nome utente e la password per accedere a VMware vSphere utilizzando lo strumento OVF
* Si dispone delle autorizzazioni sufficienti per distribuire VM dai file OVF e accenderle, nonché delle autorizzazioni per creare volumi aggiuntivi da collegare alle VM.  Vedi il `ovftool` documentazione per i dettagli.
* Conosci l'URL dell'infrastruttura virtuale (VI) per la posizione in vSphere in cui desideri distribuire le macchine virtuali StorageGRID .  In genere questo URL sarà una vApp o un pool di risorse. Ad esempio:  `vi://vcenter.example.com/vi/sgws`
+

NOTE: Puoi usare VMware `ovftool` utilità per determinare questo valore (vedere il `ovftool` documentazione per i dettagli).

+

NOTE: Se si esegue la distribuzione su una vApp, le macchine virtuali non si avvieranno automaticamente la prima volta e sarà necessario accenderle manualmente.

* Hai raccolto tutte le informazioni necessarie per il file di configurazione della distribuzione.  Vederelink:collecting-information-about-your-deployment-environment.html["Raccogli informazioni sul tuo ambiente di distribuzione"] per informazioni.
* È possibile accedere ai seguenti file dall'archivio di installazione VMware per StorageGRID:


[cols="1a,1a"]
|===
| Nome del file | Descrizione 


| NetApp-SG-versione-SHA.vmdk  a| 
File del disco della macchina virtuale utilizzato come modello per la creazione di macchine virtuali con nodi di griglia.

*Nota:* Questo file deve trovarsi nella stessa cartella del `.ovf` E `.mf` file.



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
Il file modello Open Virtualization Format(`.ovf` ) e file manifesto(`.mf` ) per distribuire il nodo di amministrazione primario.



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
Il file modello(`.ovf` ) e file manifesto(`.mf` ) per distribuire nodi amministrativi non primari.



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
Il file modello(`.ovf` ) e file manifesto(`.mf` ) per la distribuzione dei nodi gateway.



| vsphere-storage.ovf vsphere-storage.mf  a| 
Il file modello(`.ovf` ) e file manifesto(`.mf` ) per distribuire nodi di archiviazione basati su macchine virtuali.



| distribuire-vsphere-ovftool.sh  a| 
Lo script shell Bash utilizzato per automatizzare la distribuzione dei nodi della griglia virtuale.



| deploy-vsphere-ovftool-sample.ini  a| 
Il file di configurazione di esempio da utilizzare con `deploy-vsphere-ovftool.sh` sceneggiatura.

|===


=== Definisci il file di configurazione per la tua distribuzione

È possibile specificare le informazioni necessarie per distribuire i nodi della griglia virtuale per StorageGRID in un file di configurazione, utilizzato da `deploy-vsphere-ovftool.sh` Script Bash.  È possibile modificare un file di configurazione di esempio, in modo da non dover creare il file da zero.

.Passi
. Crea una copia del file di configurazione di esempio(`deploy-vsphere-ovftool.sample.ini` ).  Salva il nuovo file come `deploy-vsphere-ovftool.ini` nella stessa directory di `deploy-vsphere-ovftool.sh` .
. Aprire `deploy-vsphere-ovftool.ini` .
. Inserisci tutte le informazioni necessarie per distribuire i nodi della griglia virtuale VMware.
+
Vedere<<configuration-file-settings,Impostazioni del file di configurazione>> per informazioni.

. Dopo aver inserito e verificato tutte le informazioni necessarie, salvare e chiudere il file.




=== Impostazioni del file di configurazione

IL `deploy-vsphere-ovftool.ini` Il file di configurazione contiene le impostazioni necessarie per distribuire i nodi della griglia virtuale.

Il file di configurazione elenca prima i parametri globali, quindi elenca i parametri specifici del nodo nelle sezioni definite dal nome del nodo.  Quando si utilizza il file:

* I _parametri globali_ vengono applicati a tutti i nodi della griglia.
* I parametri specifici del nodo sostituiscono i parametri globali.




==== Parametri globali

I parametri globali vengono applicati a tutti i nodi della griglia, a meno che non vengano sovrascritti dalle impostazioni nelle singole sezioni.  Inserire i parametri che si applicano a più nodi nella sezione dei parametri globali, quindi sovrascrivere queste impostazioni, se necessario, nelle sezioni per i singoli nodi.

* *OVFTOOL_ARGUMENTS*: È possibile specificare OVFTOOL_ARGUMENTS come impostazioni globali oppure applicare argomenti singolarmente a nodi specifici. Per esempio:
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
Puoi usare il `--powerOffTarget` E `--overwrite` opzioni per arrestare e sostituire le macchine virtuali esistenti.

+

CAUTION: Dovresti distribuire i nodi su diversi datastore e specificare OVFTOOL_ARGUMENTS per ogni nodo, anziché globalmente.

* *FONTE*: Il percorso al modello della macchina virtuale StorageGRID(`.vmdk` ) file e il `.ovf` E `.mf` file per singoli nodi della griglia.  Per impostazione predefinita, viene utilizzata la directory corrente.
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* *TARGET*: URL dell'infrastruttura virtuale VMware vSphere (vi) per la posizione in cui verrà distribuito StorageGRID . Per esempio:
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* *GRID_NETWORK_CONFIG*: Metodo utilizzato per acquisire gli indirizzi IP, STATICO o DHCP.  L'impostazione predefinita è STATICO.  Se tutti o la maggior parte dei nodi utilizzano lo stesso metodo per acquisire gli indirizzi IP, è possibile specificare tale metodo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
GRID_NETWORK_CONFIG = STATIC
----
* *GRID_NETWORK_TARGET*: Nome di una rete VMware esistente da utilizzare per la rete Grid.  Se tutti o la maggior parte dei nodi utilizzano lo stesso nome di rete, è possibile specificarlo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
GRID_NETWORK_TARGET = SG Admin Network
----
* *GRID_NETWORK_MASK*: Maschera di rete per la rete Grid.  Se tutti o la maggior parte dei nodi utilizzano la stessa maschera di rete, è possibile specificarla qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* *GRID_NETWORK_GATEWAY*: Gateway di rete per la rete Grid.  Se tutti o la maggior parte dei nodi utilizzano lo stesso gateway di rete, è possibile specificarlo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* *GRID_NETWORK_MTU*: Facoltativo.  L'unità di trasmissione massima (MTU) sulla rete elettrica.  Se specificato, il valore deve essere compreso tra 1280 e 9216. Per esempio:
+
[listing]
----
GRID_NETWORK_MTU = 9000
----
+
Se omesso, viene utilizzato 1400.

+
Se si desidera utilizzare i jumbo frame, impostare l'MTU su un valore adatto ai jumbo frame, ad esempio 9000.  Altrimenti, mantieni il valore predefinito.

+

NOTE: Il valore MTU della rete deve corrispondere al valore configurato sulla porta dello switch virtuale in vSphere a cui è connesso il nodo.  In caso contrario, potrebbero verificarsi problemi di prestazioni di rete o perdita di pacchetti.

+

NOTE: Per ottenere le migliori prestazioni di rete, tutti i nodi devono essere configurati con valori MTU simili sulle loro interfacce Grid Network.  L'avviso *Mancata corrispondenza MTU della rete Grid* viene attivato se si verifica una differenza significativa nelle impostazioni MTU per la rete Grid sui singoli nodi.  I valori MTU non devono essere gli stessi per tutti i tipi di rete.

* *ADMIN_NETWORK_CONFIG*: Metodo utilizzato per acquisire gli indirizzi IP, DISABILITATO, STATICO o DHCP.  L'impostazione predefinita è DISABILITATO.  Se tutti o la maggior parte dei nodi utilizzano lo stesso metodo per acquisire gli indirizzi IP, è possibile specificare tale metodo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* *ADMIN_NETWORK_TARGET*: Nome di una rete VMware esistente da utilizzare per la rete di amministrazione.  Questa impostazione è obbligatoria a meno che la rete di amministrazione non sia disabilitata.  Se tutti o la maggior parte dei nodi utilizzano lo stesso nome di rete, è possibile specificarlo qui.  A differenza della rete Grid, non è necessario che tutti i nodi siano connessi alla stessa rete di amministrazione.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
ADMIN_NETWORK_TARGET = SG Admin Network
----
* *ADMIN_NETWORK_MASK*: Maschera di rete per la rete di amministrazione.  Questa impostazione è obbligatoria se si utilizza l'indirizzamento IP statico.  Se tutti o la maggior parte dei nodi utilizzano la stessa maschera di rete, è possibile specificarla qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* *ADMIN_NETWORK_GATEWAY*: Gateway di rete per la rete di amministrazione.  Questa impostazione è obbligatoria se si utilizza l'indirizzamento IP statico e si specificano subnet esterne nell'impostazione ADMIN_NETWORK_ESL.  (Ciò significa che non è necessario se ADMIN_NETWORK_ESL è vuoto.)  Se tutti o la maggior parte dei nodi utilizzano lo stesso gateway di rete, è possibile specificarlo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* *ADMIN_NETWORK_ESL*: Elenco delle subnet esterne (routes) per la rete di amministrazione, specificato come elenco separato da virgole di destinazioni di route CIDR.  Se tutti o la maggior parte dei nodi utilizzano lo stesso elenco di subnet esterne, è possibile specificarlo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* *ADMIN_NETWORK_MTU*: Facoltativo.  L'unità di trasmissione massima (MTU) sulla rete di amministrazione.  Non specificare se ADMIN_NETWORK_CONFIG = DHCP.  Se specificato, il valore deve essere compreso tra 1280 e 9216.  Se omesso, viene utilizzato 1400.  Se si desidera utilizzare i jumbo frame, impostare l'MTU su un valore adatto ai jumbo frame, ad esempio 9000.  Altrimenti, mantieni il valore predefinito.  Se tutti o la maggior parte dei nodi utilizzano lo stesso MTU per la rete di amministrazione, è possibile specificarlo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* *CLIENT_NETWORK_CONFIG*: metodo utilizzato per acquisire gli indirizzi IP, DISABILITATO, STATICO o DHCP.  L'impostazione predefinita è DISABILITATO.  Se tutti o la maggior parte dei nodi utilizzano lo stesso metodo per acquisire gli indirizzi IP, è possibile specificare tale metodo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* *CLIENT_NETWORK_TARGET*: Nome di una rete VMware esistente da utilizzare per la rete client.  Questa impostazione è obbligatoria a meno che la rete client non sia disabilitata.  Se tutti o la maggior parte dei nodi utilizzano lo stesso nome di rete, è possibile specificarlo qui.  A differenza della rete Grid, non è necessario che tutti i nodi siano connessi alla stessa rete client.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
CLIENT_NETWORK_TARGET = SG Client Network
----
* *CLIENT_NETWORK_MASK*: Maschera di rete per la rete client.  Questa impostazione è obbligatoria se si utilizza l'indirizzamento IP statico.  Se tutti o la maggior parte dei nodi utilizzano la stessa maschera di rete, è possibile specificarla qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* *CLIENT_NETWORK_GATEWAY*: Gateway di rete per la rete client.  Questa impostazione è obbligatoria se si utilizza l'indirizzamento IP statico.  Se tutti o la maggior parte dei nodi utilizzano lo stesso gateway di rete, è possibile specificarlo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* *CLIENT_NETWORK_MTU*: Facoltativo.  L'unità di trasmissione massima (MTU) sulla rete client.  Non specificare se CLIENT_NETWORK_CONFIG = DHCP.  Se specificato, il valore deve essere compreso tra 1280 e 9216.  Se omesso, viene utilizzato 1400.  Se si desidera utilizzare i jumbo frame, impostare l'MTU su un valore adatto ai jumbo frame, ad esempio 9000.  Altrimenti, mantieni il valore predefinito.  Se tutti o la maggior parte dei nodi utilizzano lo stesso MTU per la rete client, è possibile specificarlo qui.  È quindi possibile sovrascrivere l'impostazione globale specificando impostazioni diverse per uno o più nodi individuali. Per esempio:
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* *PORT_REMAP*: Riassegna qualsiasi porta utilizzata da un nodo per le comunicazioni interne del nodo della griglia o per le comunicazioni esterne.  La rimappatura delle porte è necessaria se i criteri di rete aziendale limitano una o più porte utilizzate da StorageGRID.  Per l'elenco delle porte utilizzate da StorageGRID, vedere le comunicazioni interne del nodo della griglia e le comunicazioni esterne inlink:../network/index.html["Linee guida per il networking"] .
+

NOTE: Non rimappare le porte che intendi utilizzare per configurare gli endpoint del bilanciatore del carico.

+

NOTE: Se è impostato solo PORT_REMAP, la mappatura specificata viene utilizzata sia per le comunicazioni in entrata che per quelle in uscita.  Se viene specificato anche PORT_REMAP_INBOUND, PORT_REMAP si applica solo alle comunicazioni in uscita.

+
Il formato utilizzato è: `_network type/protocol/default port used by grid node/new port_` , dove il tipo di rete è grid, admin o client e il protocollo è tcp o udp.

+
Per esempio:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443
----
+
Se utilizzata da sola, questa impostazione di esempio mappa in modo simmetrico le comunicazioni in entrata e in uscita per il nodo della griglia dalla porta 18082 alla porta 443.  Se utilizzata insieme a PORT_REMAP_INBOUND, questa impostazione di esempio mappa le comunicazioni in uscita dalla porta 18082 alla porta 443.

+
È anche possibile rimappare più porte utilizzando un elenco separato da virgole.

+
Per esempio:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80
----
* *PORT_REMAP_INBOUND*: Riassegna le comunicazioni in entrata per la porta specificata.  Se si specifica PORT_REMAP_INBOUND ma non si specifica un valore per PORT_REMAP, le comunicazioni in uscita per la porta rimangono invariate.
+

NOTE: Non rimappare le porte che intendi utilizzare per configurare gli endpoint del bilanciatore del carico.

+
Il formato utilizzato è: `_network type_/_protocol/_default port used by grid node_/_new port_` , dove il tipo di rete è grid, admin o client e il protocollo è tcp o udp.

+
Per esempio:

+
[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
+
Questo esempio prende il traffico inviato alla porta 443 per superare un firewall interno e lo indirizza alla porta 18082, dove il nodo della griglia è in ascolto delle richieste S3.

+
È anche possibile rimappare più porte in ingresso utilizzando un elenco separato da virgole.

+
Per esempio:

+
[listing]
----
PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22
----
* *TEMPORARY_PASSWORD_TYPE*: Tipo di password di installazione temporanea da utilizzare quando si accede alla console della VM o all'API di installazione StorageGRID , oppure tramite SSH, prima che il nodo si unisca alla griglia.
+

TIP: Se tutti o la maggior parte dei nodi utilizzano lo stesso tipo di password di installazione temporanea, specificare il tipo nella sezione dei parametri globali.  Quindi, se lo si desidera, utilizzare un'impostazione diversa per un singolo nodo.  Ad esempio, se selezioni *Usa password personalizzata* a livello globale, puoi usare *CUSTOM_TEMPORARY_PASSWORD=<password>* per impostare la password per ciascun nodo.

+
*TEMPORARY_PASSWORD_TYPE* può essere uno dei seguenti:

+
** *Usa nome nodo*: il nome del nodo viene utilizzato come password di installazione temporanea e fornisce l'accesso alla console della VM, all'API di installazione StorageGRID e a SSH.
** *Disabilita password*: non verrà utilizzata alcuna password di installazione temporanea.  Se è necessario accedere alla macchina virtuale per risolvere i problemi di installazione, vederelink:troubleshooting-installation-issues.html["Risolvere i problemi di installazione"] .
** *Usa password personalizzata*: il valore fornito con *CUSTOM_TEMPORARY_PASSWORD=<password>* viene utilizzato come password di installazione temporanea e fornisce l'accesso alla console della VM, all'API di installazione StorageGRID e a SSH.
+

TIP: Facoltativamente, è possibile omettere il parametro *TEMPORARY_PASSWORD_TYPE* e specificare solo *CUSTOM_TEMPORARY_PASSWORD=<password>*.



* *CUSTOM_TEMPORARY_PASSWORD=<password>* Facoltativo.  Password temporanea da utilizzare durante l'installazione per accedere alla console della VM, all'API di installazione StorageGRID e a SSH.  Ignorato se *TEMPORARY_PASSWORD_TYPE* ​​è impostato su *Usa nome nodo* o *Disabilita password*.




==== Parametri specifici del nodo

Ogni nodo si trova nella propria sezione del file di configurazione.  Ogni nodo richiede le seguenti impostazioni:

* L'intestazione della sezione definisce il nome del nodo che verrà visualizzato in Grid Manager.  È possibile sovrascrivere tale valore specificando il parametro facoltativo NODE_NAME per il nodo.
* *NODE_TYPE*: VM_Admin_Node, VM_Storage_Node o VM_API_Gateway_Node
* *STORAGE_TYPE*: combinato, dati o metadati.  Se non specificato, questo parametro facoltativo per i nodi di archiviazione è impostato di default su combinato (dati e metadati). Per ulteriori informazioni, consultare link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipi di nodi di archiviazione"] .
* *GRID_NETWORK_IP*: l'indirizzo IP del nodo sulla rete Grid.
* *ADMIN_NETWORK_IP*: l'indirizzo IP del nodo sulla rete di amministrazione.  Obbligatorio solo se il nodo è collegato alla rete di amministrazione e ADMIN_NETWORK_CONFIG è impostato su STATIC.
* *CLIENT_NETWORK_IP*: l'indirizzo IP del nodo sulla rete client.  Obbligatorio solo se il nodo è collegato alla rete client e CLIENT_NETWORK_CONFIG per questo nodo è impostato su STATIC.
* *ADMIN_IP*: l'indirizzo IP del nodo di amministrazione primario sulla rete Grid.  Utilizzare il valore specificato come GRID_NETWORK_IP per il nodo di amministrazione primario.  Se si omette questo parametro, il nodo tenta di rilevare l'IP del nodo di amministrazione primario tramite mDNS. Per ulteriori informazioni, consultare link:how-grid-nodes-discover-primary-admin-node.html["Come i nodi della griglia scoprono il nodo di amministrazione primario"] .
+

NOTE: Il parametro ADMIN_IP viene ignorato per il nodo di amministrazione primario.

* Tutti i parametri che non sono stati impostati a livello globale.  Ad esempio, se un nodo è collegato alla rete di amministrazione e non sono stati specificati i parametri ADMIN_NETWORK a livello globale, è necessario specificarli per il nodo.


.Nodo di amministrazione primario
Per il nodo di amministrazione primario sono necessarie le seguenti impostazioni aggiuntive:

* *NODE_TYPE*: VM_Admin_Node
* *ADMIN_ROLE*: Primario


Questa voce di esempio è per un nodo di amministrazione primario presente su tutte e tre le reti:

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node
  TEMPORARY_PASSWORD_TYPE = Use custom password
  CUSTOM_TEMPORARY_PASSWORD = Passw0rd

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
La seguente impostazione aggiuntiva è facoltativa per il nodo di amministrazione primario:

* *DISCO*: Per impostazione predefinita, ai nodi amministrativi vengono assegnati due dischi rigidi aggiuntivi da 200 GB per l'utilizzo di database e audit.  È possibile aumentare queste impostazioni utilizzando il parametro DISK. Per esempio:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Per i nodi di amministrazione, ISTANZA deve sempre essere uguale a 2.

.Nodo di archiviazione
Per i nodi di archiviazione è richiesta la seguente impostazione aggiuntiva:

* *NODE_TYPE*: VM_Storage_Node
+
Questa voce di esempio è per un nodo di archiviazione che si trova sulla rete Grid e sulla rete di amministrazione, ma non sulla rete client.  Questo nodo utilizza l'impostazione ADMIN_IP per specificare l'indirizzo IP del nodo di amministrazione primario sulla rete Grid.

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
Questa seconda voce di esempio riguarda un nodo di archiviazione su una rete client in cui la politica di rete aziendale del cliente stabilisce che un'applicazione client S3 può accedere al nodo di archiviazione solo tramite la porta 80 o 443.  Il file di configurazione di esempio utilizza PORT_REMAP per consentire al nodo di archiviazione di inviare e ricevere messaggi S3 sulla porta 443.

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
L'ultimo esempio crea una rimappatura simmetrica per il traffico ssh dalla porta 22 alla porta 3022, ma imposta esplicitamente i valori sia per il traffico in entrata che per quello in uscita.

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


Le seguenti impostazioni aggiuntive sono facoltative per i nodi di archiviazione:

* *DISCO*: Per impostazione predefinita, ai nodi di archiviazione vengono assegnati tre dischi da 4 TB per l'utilizzo di RangeDB.  È possibile aumentare queste impostazioni con il parametro DISK. Per esempio:
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----
* *STORAGE_TYPE*: Per impostazione predefinita, tutti i nuovi nodi di archiviazione sono configurati per archiviare sia i dati degli oggetti che i metadati, noti come nodi di archiviazione _combinati_.  È possibile modificare il tipo di nodo di archiviazione per archiviare solo dati o metadati con il parametro STORAGE_TYPE. Per esempio:
+
[listing]
----
STORAGE_TYPE = data
----


.Nodo Gateway
Per i nodi gateway è richiesta la seguente impostazione aggiuntiva:

* *NODE_TYPE*: VM_API_Gateway


Questa voce di esempio è per un nodo gateway di esempio su tutte e tre le reti.  In questo esempio, non sono stati specificati parametri di rete client nella sezione globale del file di configurazione, quindi devono essere specificati per il nodo:

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG Client Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
.Nodo amministratore non primario
Per i nodi amministrativi non primari sono necessarie le seguenti impostazioni aggiuntive:

* *NODE_TYPE*: VM_Admin_Node
* *ADMIN_ROLE*: Non primario


Questa voce di esempio è per un nodo di amministrazione non primario che non si trova sulla rete client:

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG Grid Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
La seguente impostazione aggiuntiva è facoltativa per i nodi amministrativi non primari:

* *DISCO*: Per impostazione predefinita, ai nodi amministrativi vengono assegnati due dischi rigidi aggiuntivi da 200 GB per l'utilizzo di database e audit.  È possibile aumentare queste impostazioni utilizzando il parametro DISK. Per esempio:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Per i nodi di amministrazione, ISTANZA deve sempre essere uguale a 2.



== Esegui lo script Bash

Puoi usare il `deploy-vsphere-ovftool.sh` Script Bash e file di configurazione deploy-vsphere-ovftool.ini modificati per automatizzare la distribuzione dei nodi StorageGRID in VMware vSphere.

.Prima di iniziare
Hai creato un file di configurazione deploy-vsphere-ovftool.ini per il tuo ambiente.

È possibile utilizzare la guida disponibile con lo script Bash immettendo i comandi di aiuto(`-h/--help` ). Per esempio:

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
O

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.Passi
. Accedi al computer Linux che stai utilizzando per eseguire lo script Bash.
. Passare alla directory in cui è stato estratto l'archivio di installazione.
+
Per esempio:

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. Per distribuire tutti i nodi della griglia, eseguire lo script Bash con le opzioni appropriate per il proprio ambiente.
+
Per esempio:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. Se la distribuzione di un nodo della griglia non riesce a causa di un errore, risolvere l'errore ed eseguire nuovamente lo script Bash solo per quel nodo.
+
Per esempio:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


La distribuzione è completa quando lo stato di ciascun nodo è "Superato".

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== Automatizza la configurazione di StorageGRID

Dopo aver distribuito i nodi della griglia, è possibile automatizzare la configurazione del sistema StorageGRID .

.Prima di iniziare
* Conosci la posizione dei seguenti file dall'archivio di installazione.
+
[cols="1a,1a"]
|===
| Nome del file | Descrizione 


| configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione



| configure-storagegrid.sample.json  a| 
File di configurazione di esempio da utilizzare con lo script



| configure-storagegrid.blank.json  a| 
File di configurazione vuoto da utilizzare con lo script

|===
* Hai creato un `configure-storagegrid.json` file di configurazione.  Per creare questo file, puoi modificare il file di configurazione di esempio(`configure-storagegrid.sample.json` ) o il file di configurazione vuoto(`configure-storagegrid.blank.json` ).
+
Puoi usare il `configure-storagegrid.py` Script Python e il `configure-storagegrid.json` file di configurazione della griglia per automatizzare la configurazione del sistema StorageGRID .

+

NOTE: È anche possibile configurare il sistema utilizzando Grid Manager o l'API di installazione.



.Passi
. Accedi al computer Linux che stai utilizzando per eseguire lo script Python.
. Passare alla directory in cui è stato estratto l'archivio di installazione.
+
Per esempio:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
Dove `platform` è debs, rpms o vsphere.

. Esegui lo script Python e utilizza il file di configurazione che hai creato.
+
Per esempio:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Risultato
Un pacchetto di recupero `.zip` Il file viene generato durante il processo di configurazione e scaricato nella directory in cui si sta eseguendo il processo di installazione e configurazione.  È necessario eseguire il backup del file del pacchetto di ripristino in modo da poter ripristinare il sistema StorageGRID in caso di guasto di uno o più nodi della griglia.  Ad esempio, copialo in una posizione di rete protetta e sottoposta a backup e in un archivio cloud protetto.


CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .

Se hai specificato che devono essere generate password casuali, apri il `Passwords.txt` file e cerca le password necessarie per accedere al tuo sistema StorageGRID .

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Il sistema StorageGRID è installato e configurato quando viene visualizzato un messaggio di conferma.

[listing]
----
StorageGRID has been configured and installed.
----
.Informazioni correlate
* link:navigating-to-grid-manager.html["Vai al Grid Manager"]
* link:overview-of-installation-rest-api.html["Installazione REST API"]

