---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: how to automate red hat linux installation 
summary: 'È possibile automatizzare l"installazione del servizio host StorageGRID e la configurazione dei nodi della griglia.' 
---
= Automatizza l'installazione StorageGRID su Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile automatizzare l'installazione del servizio host StorageGRID e la configurazione dei nodi della griglia.

L'automazione della distribuzione potrebbe essere utile in uno qualsiasi dei seguenti casi:

* Utilizzi già un framework di orchestrazione standard, come Ansible, Puppet o Chef, per distribuire e configurare host fisici o virtuali.
* Si intende distribuire più istanze StorageGRID .
* Stai distribuendo un'istanza StorageGRID complessa e di grandi dimensioni.


Il servizio host StorageGRID viene installato da un pacchetto e gestito da file di configurazione.  È possibile creare i file di configurazione utilizzando uno di questi metodi:

* link:creating-node-configuration-files.html["Creare i file di configurazione"]interattivamente durante un'installazione manuale.
* Preparare in anticipo i file di configurazione (o a livello di programmazione) per abilitare l'installazione automatizzata utilizzando framework di orchestrazione standard, come descritto in questo articolo.
+
StorageGRID fornisce script Python opzionali per automatizzare la configurazione degli appliance StorageGRID e dell'intero sistema StorageGRID (la "griglia").  È possibile utilizzare questi script direttamente oppure è possibile esaminarli per imparare come utilizzarli.link:overview-of-installation-rest-api.html["API REST di installazione di StorageGRID"] negli strumenti di distribuzione e configurazione della griglia che sviluppi autonomamente.





== Automatizza l'installazione e la configurazione del servizio host StorageGRID

È possibile automatizzare l'installazione del servizio host StorageGRID utilizzando framework di orchestrazione standard quali Ansible, Puppet, Chef, Fabric o SaltStack.

Il servizio host StorageGRID è confezionato in un RPM ed è gestito da file di configurazione che è possibile preparare in anticipo (o a livello di programmazione) per abilitare l'installazione automatica.  Se utilizzi già un framework di orchestrazione standard per installare e configurare RHEL, aggiungere StorageGRID ai tuoi playbook o alle tue ricette dovrebbe essere semplice.

Vedere l'esempio di ruolo e playbook di Ansible in `/extras` cartella fornita con l'archivio di installazione.  Il playbook di Ansible mostra come `storagegrid` il ruolo prepara l'host e installa StorageGRID sui server di destinazione.  È possibile personalizzare il ruolo o il playbook in base alle proprie esigenze.


NOTE: Il playbook di esempio non include i passaggi necessari per creare dispositivi di rete prima di avviare il servizio host StorageGRID .  Aggiungere questi passaggi prima di finalizzare e utilizzare il playbook.

È possibile automatizzare tutti i passaggi per la preparazione degli host e la distribuzione dei nodi della griglia virtuale.



=== Esempio di ruolo e playbook di Ansible

Esempio di ruolo e playbook Ansible sono forniti con l'archivio di installazione in `/extras` cartella.  Il playbook di Ansible mostra come `storagegrid` il ruolo prepara gli host e installa StorageGRID sui server di destinazione.  È possibile personalizzare il ruolo o il playbook in base alle proprie esigenze.

Le attività di installazione fornite `storagegrid` esempio di ruolo usa il `ansible.builtin.dnf` modulo per eseguire l'installazione dai file RPM locali o da un repository Yum remoto. Se il modulo non è disponibile o non è supportato, potrebbe essere necessario modificare le attività Ansible appropriate nei seguenti file per utilizzare il `yum` O `ansible.builtin.yum` modulo:

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`




== Automatizza la configurazione di StorageGRID

Dopo aver distribuito i nodi della griglia, è possibile automatizzare la configurazione del sistema StorageGRID .

.Prima di iniziare
* Conosci la posizione dei seguenti file dall'archivio di installazione.
+
[cols="1a,1a"]
|===
| Nome del file | Descrizione 


| configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione



| configure-storagegrid.sample.json  a| 
File di configurazione di esempio da utilizzare con lo script



| configure-storagegrid.blank.json  a| 
File di configurazione vuoto da utilizzare con lo script

|===
* Hai creato un `configure-storagegrid.json` file di configurazione.  Per creare questo file, puoi modificare il file di configurazione di esempio(`configure-storagegrid.sample.json` ) o il file di configurazione vuoto(`configure-storagegrid.blank.json` ).


.Informazioni su questo compito
Puoi usare il `configure-storagegrid.py` Script Python e il `configure-storagegrid.json` file di configurazione per automatizzare la configurazione del sistema StorageGRID .


NOTE: È anche possibile configurare il sistema utilizzando Grid Manager o l'API di installazione.

.Passi
. Accedi al computer Linux che stai utilizzando per eseguire lo script Python.
. Passare alla directory in cui è stato estratto l'archivio di installazione.
+
Per esempio:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
Dove `platform` È `debs` , `rpms` , O `vsphere` .

. Esegui lo script Python e utilizza il file di configurazione che hai creato.
+
Per esempio:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Risultato
Un pacchetto di recupero `.zip` Il file viene generato durante il processo di configurazione e scaricato nella directory in cui si sta eseguendo il processo di installazione e configurazione.  È necessario eseguire il backup del file del pacchetto di ripristino in modo da poter ripristinare il sistema StorageGRID in caso di guasto di uno o più nodi della griglia.  Ad esempio, copialo in una posizione di rete protetta e sottoposta a backup e in un archivio cloud protetto.


CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .

Se hai specificato che vengano generate password casuali, apri il `Passwords.txt` file e cerca le password necessarie per accedere al tuo sistema StorageGRID .

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Il sistema StorageGRID è installato e configurato quando viene visualizzato un messaggio di conferma.

[listing]
----
StorageGRID has been configured and installed.
----
.Informazioni correlate
link:overview-of-installation-rest-api.html["Installazione REST API"]
