---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: È necessario installare StorageGRID su tutti gli host grid di Red Hat Enterprise Linux. Per un elenco delle versioni supportate, utilizzare lo strumento NetApp Interoperability Matrix. 
---
= Installa Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare StorageGRID su tutti gli host grid di Red Hat Enterprise Linux. Per un elenco delle versioni supportate, utilizzare lo strumento NetApp Interoperability Matrix.

.Prima di iniziare
Assicurati che il tuo sistema operativo soddisfi i requisiti minimi di versione del kernel di StorageGRID, come elencato di seguito.  Utilizzare il comando `uname -r` per ottenere la versione del kernel del tuo sistema operativo oppure consulta il fornitore del sistema operativo.

[cols="1a,2a,2a"]
|===
| Versione di Red Hat Enterprise Linux | Versione minima del kernel | Nome del pacchetto del kernel 


 a| 
8.8 (obsoleto)
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8,10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9.0 (obsoleto)
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9.2 (obsoleto)
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
kernel-5.14.0-284.11.1.el9_2.x86_64



 a| 
9,4
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
kernel-5.14.0-427.18.1.el9_4.x86_64



 a| 
9,6
 a| 
5.14.0-570.18.1.el9_6.x86_64
 a| 
kernel-5.14.0-570.18.1.el9_6.x86_64

|===
.Passi
. Installare Linux su tutti gli host fisici o virtuali della griglia secondo le istruzioni del distributore o la procedura standard.
+

NOTE: Se si utilizza il programma di installazione standard di Linux, selezionare la configurazione software "compute node", se disponibile, oppure l'ambiente di base "minimal install". Non installare alcun ambiente desktop grafico.

. Assicurarsi che tutti gli host abbiano accesso ai repository dei pacchetti, incluso il canale Extras.
+
Potrebbero essere necessari questi pacchetti aggiuntivi più avanti nella procedura di installazione.

. Se lo swap è abilitato:
+
.. Eseguire il seguente comando: `$ sudo swapoff --all`
.. Rimuovi tutte le voci di swap da `/etc/fstab` per mantenere le impostazioni.


+

NOTE: Se non si disattiva completamente lo swap, le prestazioni possono ridursi notevolmente.


