---
permalink: admin/benefits-of-active-idle-and-concurrent-http-connections.html 
sidebar: sidebar 
keywords: active http connection benefits, idle http connection benefits, concurrent http connection benefits 
summary: La modalità di configurazione delle connessioni HTTP può influire sulle prestazioni del sistema StorageGRID .  Le configurazioni variano a seconda che la connessione HTTP sia attiva o inattiva o che ci siano più connessioni simultanee. 
---
= Vantaggi delle connessioni HTTP attive, inattive e simultanee
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La modalità di configurazione delle connessioni HTTP può influire sulle prestazioni del sistema StorageGRID .  Le configurazioni variano a seconda che la connessione HTTP sia attiva o inattiva o che ci siano più connessioni simultanee.

È possibile identificare i vantaggi in termini di prestazioni per i seguenti tipi di connessioni HTTP:

* Connessioni HTTP inattive
* Connessioni HTTP attive
* Connessioni HTTP simultanee




== Vantaggi di mantenere aperte le connessioni HTTP inattive

È opportuno mantenere aperte le connessioni HTTP anche quando le applicazioni client sono inattive, per consentire alle applicazioni client di eseguire transazioni successive sulla connessione aperta.  In base alle misurazioni del sistema e all'esperienza di integrazione, dovresti mantenere aperta una connessione HTTP inattiva per un massimo di 10 minuti.  StorageGRID potrebbe chiudere automaticamente una connessione HTTP mantenuta aperta e inattiva per più di 10 minuti.

Le connessioni HTTP aperte e inattive offrono i seguenti vantaggi:

* Latenza ridotta dal momento in cui il sistema StorageGRID determina di dover eseguire una transazione HTTP al momento in cui il sistema StorageGRID può eseguire la transazione
+
Il vantaggio principale è la latenza ridotta, soprattutto per quanto riguarda il tempo necessario per stabilire connessioni TCP/IP e TLS.

* Aumento della velocità di trasferimento dati mediante l'attivazione dell'algoritmo di avvio lento TCP/IP con trasferimenti eseguiti in precedenza
* Notifica istantanea di diverse classi di condizioni di errore che interrompono la connettività tra l'applicazione client e il sistema StorageGRID


Determinare per quanto tempo mantenere aperta una connessione inattiva è un compromesso tra i vantaggi dell'avvio lento associati alla connessione esistente e l'allocazione ideale della connessione alle risorse di sistema interne.



== Vantaggi delle connessioni HTTP attive

Per le connessioni dirette ai nodi di archiviazione, è opportuno limitare la durata di una connessione HTTP attiva a un massimo di 10 minuti, anche se la connessione HTTP esegue continuamente transazioni.

Determinare la durata massima per cui una connessione deve rimanere aperta è un compromesso tra i vantaggi della persistenza della connessione e l'allocazione ideale della connessione alle risorse del sistema interno.

Per le connessioni client ai nodi di archiviazione, la limitazione delle connessioni HTTP attive offre i seguenti vantaggi:

* Consente un bilanciamento ottimale del carico nel sistema StorageGRID .
+
Nel tempo, una connessione HTTP potrebbe non essere più ottimale poiché cambiano i requisiti di bilanciamento del carico. Il sistema ottiene il miglior bilanciamento del carico quando le applicazioni client stabiliscono una connessione HTTP separata per ogni transazione, ma ciò annulla i vantaggi molto più preziosi associati alle connessioni persistenti.

* Consente alle applicazioni client di indirizzare le transazioni HTTP ai servizi LDR che dispongono di spazio disponibile.
* Consente l'avvio delle procedure di manutenzione.
+
Alcune procedure di manutenzione iniziano solo dopo il completamento di tutte le connessioni HTTP in corso.



Per le connessioni client al servizio Load Balancer, limitare la durata delle connessioni aperte può essere utile per consentire l'avvio tempestivo di alcune procedure di manutenzione.  Se la durata delle connessioni client non è limitata, potrebbero volerci diversi minuti prima che le connessioni attive vengano terminate automaticamente.



== Vantaggi delle connessioni HTTP simultanee

È consigliabile mantenere aperte più connessioni TCP/IP al sistema StorageGRID per consentire il parallelismo, che aumenta le prestazioni.  Il numero ottimale di connessioni parallele dipende da diversi fattori.

Le connessioni HTTP simultanee offrono i seguenti vantaggi:

* Latenza ridotta
+
Le transazioni possono iniziare immediatamente, senza dover attendere il completamento di altre transazioni.

* Aumento della produttività
+
Il sistema StorageGRID può eseguire transazioni parallele e aumentare la produttività complessiva delle transazioni.



Le applicazioni client devono stabilire più connessioni HTTP.  Quando un'applicazione client deve eseguire una transazione, può selezionare e utilizzare immediatamente qualsiasi connessione stabilita che non stia elaborando una transazione.

Ogni topologia del sistema StorageGRID presenta un throughput di picco diverso per transazioni e connessioni simultanee prima che le prestazioni inizino a peggiorare.  La velocità massima di elaborazione dipende da fattori quali risorse di elaborazione, risorse di rete, risorse di archiviazione e collegamenti WAN.  Anche il numero di server e servizi e il numero di applicazioni supportate dal sistema StorageGRID sono fattori da considerare.

I sistemi StorageGRID spesso supportano più applicazioni client. È opportuno tenerlo presente quando si determina il numero massimo di connessioni simultanee utilizzate da un'applicazione client.  Se l'applicazione client è composta da più entità software, ciascuna delle quali stabilisce connessioni al sistema StorageGRID , è necessario sommare tutte le connessioni tra le entità. Potrebbe essere necessario modificare il numero massimo di connessioni simultanee nelle seguenti situazioni:

* La topologia del sistema StorageGRID influisce sul numero massimo di transazioni e connessioni simultanee che il sistema può supportare.
* Le applicazioni client che interagiscono con il sistema StorageGRID su una rete con larghezza di banda limitata potrebbero dover ridurre il grado di concorrenza per garantire che le singole transazioni vengano completate in un tempo ragionevole.
* Quando molte applicazioni client condividono il sistema StorageGRID , potrebbe essere necessario ridurre il grado di concorrenza per evitare di superare i limiti del sistema.




== Separazione dei pool di connessioni HTTP per le operazioni di lettura e scrittura

È possibile utilizzare pool separati di connessioni HTTP per le operazioni di lettura e scrittura e controllare la quantità di pool da utilizzare per ciascuna.  Pool separati di connessioni HTTP consentono di controllare meglio le transazioni e bilanciare i carichi.

Le applicazioni client possono creare carichi che sono dominanti nel recupero (lettura) o dominanti nello stoccaggio (scrittura).  Grazie a pool separati di connessioni HTTP per le transazioni di lettura e scrittura, è possibile definire la quantità di ciascun pool da dedicare alle transazioni di lettura o scrittura.
