---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Ogni nodo della griglia ha una password univoca per la console del nodo, necessaria per accedere al nodo.  Per modificare la password della console del nodo per ciascun nodo nella griglia, attenersi alla seguente procedura.  Le password vengono memorizzate nel pacchetto di ripristino. 
---
= Cambiare le password della console del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni nodo della griglia ha una password univoca per la console del nodo, necessaria per accedere al nodo.  Segui questi passaggi per modificare ogni password univoca della console del nodo per ogni nodo nella tua griglia.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:admin-group-permissions.html["Autorizzazione di accesso alla manutenzione o alla root"] .
* Hai la passphrase di provisioning corrente.


.Informazioni su questo compito
Utilizzare la password della console del nodo per accedere a un nodo come "admin" tramite SSH oppure come utente root su una connessione VM/console fisica.  Il processo di modifica della password della console del nodo crea nuove password per ogni nodo nella griglia e memorizza le password in un file aggiornato `Passwords.txt` file nel pacchetto di ripristino.  Le password sono elencate nella colonna Password del file Passwords.txt.


NOTE: Esistono password di accesso SSH separate per le chiavi SSH utilizzate per la comunicazione tra i nodi.  Questa procedura non modifica le password di accesso SSH.



== Accedi alla procedura guidata

.Passi
. Selezionare *CONFIGURAZIONE* > *Controllo accessi* > *Password griglia*.
. In *Modifica password console nodo*, seleziona *Apporta una modifica*.




== Inserisci la passphrase di provisioning

.Passi
. Inserisci la passphrase di provisioning per la tua griglia.
. Selezionare *Continua*.




== [[download-current]]Scarica il pacchetto di ripristino corrente

Prima di modificare le password della console del nodo, scaricare il pacchetto di ripristino corrente. È possibile utilizzare le password contenute in questo file se il processo di modifica della password non riesce per un nodo.

.Passi
. Seleziona *Scarica pacchetto di ripristino*.
. Copia il file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .

. Selezionare *Continua*.
. Quando viene visualizzata la finestra di dialogo di conferma, seleziona *Sì* se sei pronto a iniziare a modificare le password della console del nodo.
+
Non è possibile annullare questo processo una volta avviato.





== Cambiare le password della console del nodo

Quando si avvia il processo di inserimento della password della console del nodo, viene generato un nuovo pacchetto di ripristino che include le nuove password.  Quindi, le password vengono aggiornate su ciascun nodo.

.Passi
. Attendi che venga generato il nuovo pacchetto di ripristino, operazione che potrebbe richiedere alcuni minuti.
. Seleziona *Scarica nuovo pacchetto di ripristino*.
. Al termine del download:
+
.. Apri il `.zip` file.
.. Conferma di poter accedere ai contenuti, incluso il `Passwords.txt` file, che contiene le nuove password della console del nodo.
.. Copia il nuovo file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Non sovrascrivere il vecchio Recovery Package.

+
Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .



. Seleziona la casella di controllo per indicare che hai scaricato il nuovo pacchetto di ripristino e ne hai verificato il contenuto.
. Selezionare *Modifica password console nodo* e attendere che tutti i nodi vengano aggiornati con le nuove password.  Potrebbero volerci alcuni minuti.
+
Se le password vengono modificate per tutti i nodi, viene visualizzato un banner verde di operazione riuscita.  Vai al passaggio successivo.

+
Se si verifica un errore durante il processo di aggiornamento, un messaggio banner elenca il numero di nodi le cui password non sono state modificate. Il sistema riproverà automaticamente il processo su qualsiasi nodo la cui password non è riuscita a cambiare. Se il processo termina con alcuni nodi che non hanno ancora modificato la password, viene visualizzato il pulsante *Riprova*.

+
Se l'aggiornamento della password non è riuscito per uno o più nodi:

+
.. Esaminare i messaggi di errore elencati nella tabella.
.. Risolvere i problemi.
.. Seleziona *Riprova*.
+

NOTE: Il nuovo tentativo modifica solo le password della console dei nodi che non sono riusciti nei precedenti tentativi di modifica della password.



. Dopo aver modificato le password della console del nodo per tutti i nodi, eliminare il<<download-current,primo pacchetto di ripristino scaricato>> .
. Facoltativamente, utilizzare il collegamento *Pacchetto di ripristino* per scaricare una copia aggiuntiva del nuovo Pacchetto di ripristino.

