---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: La modifica delle password di accesso SSH per i nodi amministrativi aggiorna anche i set univoci di chiavi SSH interne per ciascun nodo nella griglia.  Il nodo di amministrazione primario utilizza queste chiavi SSH per accedere ai nodi tramite autenticazione sicura e senza password. 
---
= Modificare le password di accesso SSH per i nodi amministrativi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La modifica delle password di accesso SSH per i nodi amministrativi aggiorna anche i set univoci di chiavi SSH interne per ciascun nodo nella griglia.  Il nodo di amministrazione primario utilizza queste chiavi SSH per accedere ai nodi tramite autenticazione sicura e senza password.

Utilizzare una chiave SSH per accedere a un nodo come `admin` o all'utente root su una macchina virtuale o su una connessione alla console fisica.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:admin-group-permissions.html["Autorizzazione di accesso alla manutenzione o alla root"] .
* Hai la passphrase di provisioning corrente.


.Informazioni su questo compito
Le nuove password di accesso per i nodi di amministrazione e le nuove chiavi interne per ciascun nodo sono memorizzate nel `Passwords.txt` file nel pacchetto di ripristino. Le chiavi sono elencate nella colonna Password di quel file.

Esistono password di accesso SSH separate per le chiavi SSH utilizzate per la comunicazione tra i nodi.  Questa procedura non li modifica.



== Accedi alla procedura guidata

.Passi
. Selezionare *CONFIGURAZIONE* > *Controllo accessi* > *Password griglia*.
. In *Modifica chiavi SSH*, seleziona *Apporta una modifica*.




== [[download-current]]Scarica il pacchetto di ripristino corrente

Prima di modificare le chiavi di accesso SSH, scaricare il pacchetto di ripristino corrente. È possibile utilizzare le chiavi contenute in questo file se il processo di modifica delle chiavi non riesce per un nodo.

.Passi
. Inserisci la passphrase di provisioning per la tua griglia.
. Seleziona *Scarica pacchetto di ripristino*.
. Copia il file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .

. Selezionare *Continua*.
. Quando viene visualizzata la finestra di dialogo di conferma, seleziona *Sì* se sei pronto a iniziare a modificare le chiavi di accesso SSH.
+

CAUTION: Non è possibile annullare questo processo una volta avviato.





== Cambia le chiavi di accesso SSH

Quando viene avviato il processo di modifica delle chiavi di accesso SSH, viene generato un nuovo pacchetto di ripristino che include le nuove chiavi. Quindi, le chiavi vengono aggiornate su ciascun nodo.

.Passi
. Attendi che venga generato il nuovo pacchetto di ripristino, operazione che potrebbe richiedere alcuni minuti.
. Quando il pulsante Scarica nuovo pacchetto di ripristino è abilitato, seleziona *Scarica nuovo pacchetto di ripristino* e salva il nuovo file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
. Al termine del download:
+
.. Apri il `.zip` file.
.. Conferma di poter accedere ai contenuti, incluso il `Passwords.txt` file, che contiene le nuove chiavi di accesso SSH.
.. Copia il nuovo file del pacchetto di ripristino(`.zip` ) in due luoghi sicuri, protetti e separati.
+

CAUTION: Non sovrascrivere il vecchio Recovery Package.

+
Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID .



. Attendi che le chiavi vengano aggiornate su ciascun nodo, operazione che potrebbe richiedere alcuni minuti.
+
Se le chiavi vengono modificate per tutti i nodi, viene visualizzato un banner verde di successo.

+
Se si verifica un errore durante il processo di aggiornamento, un messaggio banner elenca il numero di nodi le cui chiavi non sono state modificate.  Il sistema riproverà automaticamente il processo su qualsiasi nodo la cui chiave non è riuscita a cambiare.  Se il processo termina con alcuni nodi che non hanno ancora una chiave modificata, viene visualizzato il pulsante *Riprova*.

+
Se l'aggiornamento della chiave non è riuscito per uno o più nodi:

+
.. Esaminare i messaggi di errore elencati nella tabella.
.. Risolvere i problemi.
.. Seleziona *Riprova*.
+
Il nuovo tentativo modifica solo le chiavi di accesso SSH sui nodi che non sono riusciti durante i precedenti tentativi di modifica delle chiavi.



. Dopo aver modificato le chiavi di accesso SSH per tutti i nodi, eliminare<<download-current,primo pacchetto di ripristino scaricato>> .
. Facoltativamente, selezionare *MANUTENZIONE* > *Sistema* > *Pacchetto di ripristino* per scaricare una copia aggiuntiva del nuovo Pacchetto di ripristino.

