---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Se sei un utente locale di Grid Manager, puoi modificare la tua password. 
---
= Cambia la tua password
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se sei un utente locale di Grid Manager, puoi modificare la tua password.

.Prima di iniziare
Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .

.Informazioni su questo compito
Se accedi a StorageGRID come utente federato o se è abilitato l'accesso singolo (SSO), non puoi modificare la password in Grid Manager.  In alternativa, è necessario modificare la password nella fonte di identità esterna, ad esempio Active Directory o OpenLDAP.

.Passi
. Dall'intestazione Grid Manager, seleziona *_il tuo nome_* > *Cambia password*.
. Inserisci la tua password attuale.
. Digita una nuova password.
+
La password deve contenere almeno 8 e non più di 32 caratteri.  Le password sono sensibili alle maiuscole e alle minuscole.

. Reinserisci la nuova password.
. Seleziona *Salva*.

