---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: security, browser inactivity timeout, management API stack track 
summary: 'Le impostazioni di sicurezza dell"interfaccia consentono di controllare se gli utenti vengono disconnessi se rimangono inattivi per un periodo di tempo superiore a quello specificato e se una traccia dello stack viene inclusa nelle risposte di errore dell"API.' 
---
= Modificare le impostazioni di sicurezza dell'interfaccia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le impostazioni di sicurezza dell'interfaccia consentono di controllare se gli utenti vengono disconnessi se rimangono inattivi per un periodo di tempo superiore a quello specificato e se una traccia dello stack viene inclusa nelle risposte di errore dell'API.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Hailink:admin-group-permissions.html["Permesso di accesso root"] .


.Informazioni su questo compito
La pagina *Impostazioni di sicurezza* include le impostazioni *Timeout di inattività del browser* e *Stack trace dell'API di gestione*.

Timeout di inattività del browser:: Indica per quanto tempo il browser di un utente può rimanere inattivo prima che l'utente venga disconnesso.  Il valore predefinito è 15 minuti.
+
--
Il timeout di inattività del browser è controllato anche da quanto segue:

* Un timer StorageGRID separato e non configurabile, incluso per la sicurezza del sistema.  Il token di autenticazione di ciascun utente scade 16 ore dopo l'accesso dell'utente. Quando scade l'autenticazione di un utente, l'utente viene automaticamente disconnesso, anche se il timeout di inattività del browser è disabilitato o il valore per il timeout del browser non è stato raggiunto.  Per rinnovare il token, l'utente deve effettuare nuovamente l'accesso.
* Impostazioni di timeout per il provider di identità, presupponendo che l'accesso Single Sign-On (SSO) sia abilitato per StorageGRID.
+
Se l'SSO è abilitato e il browser di un utente scade, l'utente deve reinserire le proprie credenziali SSO per accedere nuovamente a StorageGRID . Vedere link:configuring-sso.html["Configurare l'accesso singolo"] .



--
Stack trace dell'API di gestione:: Controlla se viene restituita una traccia dello stack nelle risposte di errore dell'API Grid Manager e Tenant Manager.
+
--
Questa opzione è disabilitata per impostazione predefinita, ma potrebbe essere opportuno abilitare questa funzionalità per un ambiente di prova.  In generale, negli ambienti di produzione è consigliabile lasciare la traccia dello stack disabilitata per evitare di rivelare dettagli software interni quando si verificano errori API.

--


.Passi
. Selezionare *CONFIGURAZIONE* > *Sicurezza* > *Impostazioni di sicurezza*.
. Selezionare la scheda *Interfaccia*.
. Per modificare l'impostazione del timeout di inattività del browser:
+
.. Espandi la fisarmonica.
.. Per modificare il periodo di timeout, specificare un valore compreso tra 60 secondi e 7 giorni.  Il timeout predefinito è 15 minuti.
.. Per disattivare questa funzione, deselezionare la casella di controllo.
.. Seleziona *Salva*.
+
La nuova impostazione non ha effetto sugli utenti che hanno effettuato l'accesso. Gli utenti devono effettuare nuovamente l'accesso o aggiornare il browser affinché la nuova impostazione di timeout abbia effetto.



. Per modificare l'impostazione per la traccia dello stack dell'API di gestione:
+
.. Espandi la fisarmonica.
.. Selezionare la casella di controllo per restituire una traccia dello stack nelle risposte di errore dell'API Grid Manager e Tenant Manager.
+

CAUTION: Lasciare la traccia dello stack disabilitata negli ambienti di produzione per evitare di rivelare dettagli software interni quando si verificano errori API.

.. Seleziona *Salva*.



