---
permalink: admin/configuring-storage-proxy-settings.html 
sidebar: sidebar 
keywords: storage proxy, non-transparent proxy, platform service endpoint 
summary: 'Se si utilizzano servizi di piattaforma o pool di archiviazione cloud, è possibile configurare un proxy non trasparente tra i nodi di archiviazione e gli endpoint S3 esterni.  Ad esempio, potrebbe essere necessario un proxy non trasparente per consentire l"invio di messaggi dei servizi della piattaforma a endpoint esterni, come un endpoint su Internet.' 
---
= Configurare il proxy di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizzano servizi di piattaforma o pool di archiviazione cloud, è possibile configurare un proxy non trasparente tra i nodi di archiviazione e gli endpoint S3 esterni.  Ad esempio, potrebbe essere necessario un proxy non trasparente per consentire l'invio di messaggi dei servizi della piattaforma a endpoint esterni, come un endpoint su Internet.


NOTE: Le impostazioni del proxy di archiviazione configurate non si applicano agli endpoint dei servizi della piattaforma Kafka.

.Prima di iniziare
* Hailink:admin-group-permissions.html["autorizzazioni di accesso specifiche"] .
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .


.Informazioni su questo compito
È possibile configurare le impostazioni per un singolo proxy di archiviazione.

.Passi
. Selezionare *CONFIGURAZIONE* > *Sicurezza* > *Impostazioni proxy*.
. Nella scheda *Archiviazione*, seleziona la casella di controllo *Abilita proxy di archiviazione*.
. Selezionare il protocollo per il proxy di archiviazione.
. Inserisci il nome host o l'indirizzo IP del server proxy.
. Facoltativamente, immettere la porta utilizzata per connettersi al server proxy.
+
Lasciare vuoto questo campo per utilizzare la porta predefinita per il protocollo: 80 per HTTP o 1080 per SOCKS5.

. Seleziona *Salva*.
+
Dopo aver salvato il proxy di archiviazione, è possibile configurare e testare nuovi endpoint per i servizi della piattaforma o i pool di archiviazione cloud.

+

NOTE: Le modifiche apportate al proxy potrebbero richiedere fino a 10 minuti per diventare effettive.

. Controllare le impostazioni del server proxy per assicurarsi che i messaggi relativi al servizio della piattaforma provenienti da StorageGRID non vengano bloccati.
. Se è necessario disattivare un proxy di archiviazione, deselezionare la casella di controllo e selezionare *Salva*.

