---
permalink: admin/configuring-storagegrid-certificates-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricpool, ONTAP certificates 
summary: 'Per i client S3 che eseguono la convalida rigorosa del nome host e non supportano la disabilitazione della convalida rigorosa del nome host, come i client ONTAP che utilizzano FabricPool, è possibile generare o caricare un certificato server quando si configura l"endpoint del bilanciatore del carico.' 
---
= Configurare i certificati StorageGRID per FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per i client S3 che eseguono la convalida rigorosa del nome host e non supportano la disabilitazione della convalida rigorosa del nome host, come i client ONTAP che utilizzano FabricPool, è possibile generare o caricare un certificato server quando si configura l'endpoint del bilanciatore del carico.

.Prima di iniziare
* Hailink:admin-group-permissions.html["autorizzazioni di accesso specifiche"] .
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .


.Informazioni su questo compito
Quando si crea un endpoint del bilanciatore del carico, è possibile generare un certificato server autofirmato o caricare un certificato firmato da un'autorità di certificazione (CA) nota.  Negli ambienti di produzione, è consigliabile utilizzare un certificato firmato da una CA nota.  I certificati firmati da una CA possono essere ruotati senza interruzioni.  Sono anche più sicuri perché offrono una migliore protezione contro gli attacchi man-in-the-middle.

I passaggi seguenti forniscono linee guida generali per i client S3 che utilizzano FabricPool.  Per informazioni e procedure più dettagliate, vederelink:../fabricpool/index.html["Configurare StorageGRID per FabricPool"] .

.Passi
. Facoltativamente, configurare un gruppo ad alta disponibilità (HA) da utilizzare per FabricPool .
. Creare un endpoint del bilanciatore del carico S3 da utilizzare per FabricPool .
+
Quando si crea un endpoint del bilanciatore del carico HTTPS, viene richiesto di caricare il certificato del server, la chiave privata del certificato e il bundle CA facoltativo.

. Collegare StorageGRID come livello cloud in ONTAP.
+
Specificare la porta dell'endpoint del bilanciatore del carico e il nome di dominio completo utilizzato nel certificato CA caricato.  Quindi, fornire il certificato CA.

+

NOTE: Se il certificato StorageGRID è stato emesso da una CA intermedia, è necessario fornire il certificato della CA intermedia.  Se il certificato StorageGRID è stato emesso direttamente dalla CA radice, è necessario fornire il certificato della CA radice.


