---
permalink: admin/controlling-storagegrid-access.html 
sidebar: sidebar 
keywords: administrator access, single sign on, sso, users, groups, client certificates, passwords, passphrase 
summary: 'È possibile controllare chi può accedere a StorageGRID e quali attività gli utenti possono eseguire creando o importando gruppi e utenti e assegnando autorizzazioni a ciascun gruppo.  Facoltativamente, è possibile abilitare l"accesso Single Sign-On (SSO), creare certificati client e modificare le password della griglia.' 
---
= Controllo dell'accesso a StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile controllare chi può accedere a StorageGRID e quali attività gli utenti possono eseguire creando o importando gruppi e utenti e assegnando autorizzazioni a ciascun gruppo.  Facoltativamente, è possibile abilitare l'accesso singolo (SSO), creare certificati client e modificare le password della griglia.



== Controlla l'accesso al Grid Manager

È possibile determinare chi può accedere a Grid Manager e all'API Grid Management importando gruppi e utenti da un servizio di federazione delle identità o impostando gruppi e utenti locali.

Utilizzandolink:using-identity-federation.html["federazione di identità"] rende l'impostazionelink:managing-admin-groups.html["gruppi"] Elink:managing-users.html["utenti"] più veloce e consente agli utenti di accedere a StorageGRID utilizzando credenziali familiari.  È possibile configurare la federazione delle identità se si utilizza Active Directory, OpenLDAP o Oracle Directory Server.


NOTE: Se si desidera utilizzare un altro servizio LDAP v3, contattare l'assistenza tecnica.

Si determinano le attività che ciascun utente può svolgere assegnando diverselink:admin-group-permissions.html["permessi"] a ciascun gruppo.  Ad esempio, potresti voler consentire agli utenti di un gruppo di gestire le regole ILM e agli utenti di un altro gruppo di eseguire attività di manutenzione.  Per accedere al sistema, un utente deve appartenere ad almeno un gruppo.

Facoltativamente, è possibile configurare un gruppo in sola lettura.  Gli utenti di un gruppo di sola lettura possono visualizzare solo impostazioni e funzionalità.  Non possono apportare modifiche o eseguire operazioni in Grid Manager o nell'API Grid Management.



== Abilita l'accesso singolo

Il sistema StorageGRID supporta l'accesso Single Sign-On (SSO) utilizzando lo standard Security Assertion Markup Language 2.0 (SAML 2.0). Dopo di telink:configuring-sso.html["configurare e abilitare SSO"] , tutti gli utenti devono essere autenticati da un provider di identità esterno prima di poter accedere a Grid Manager, Tenant Manager, Grid Management API o Tenant Management API. Gli utenti locali non possono accedere a StorageGRID.



== Cambia la passphrase di provisioning

La passphrase di provisioning è necessaria per numerose procedure di installazione e manutenzione e per scaricare il pacchetto di ripristino StorageGRID . La passphrase è necessaria anche per scaricare i backup delle informazioni sulla topologia della griglia e le chiavi di crittografia per il sistema StorageGRID . Puoilink:changing-provisioning-passphrase.html["cambiare la passphrase"] come richiesto.



== Cambiare le password della console del nodo

Ogni nodo nella griglia ha una password univoca per la console del nodo, che è necessaria per accedere al nodo come "admin" tramite SSH oppure come utente root su una connessione alla console fisica/VM. Se necessario, puoilink:change-node-console-password.html["cambiare la password della console del nodo"] per ogni nodo.
