---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords: admin network, client network, grid network, access interface, trunk interface 
summary: StorageGRID supporta fino a tre interfacce di rete per nodo della griglia, consentendo di configurare la rete per ogni singolo nodo della griglia in base ai requisiti di sicurezza e accesso. 
---
= Linee guida per le reti StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Grid Manager per configurare e gestire le reti e le connessioni StorageGRID .

Vederelink:configuring-client-connections.html["Configurare le connessioni client S3"] per imparare a connettere i client S3.



== Reti StorageGRID predefinite

Per impostazione predefinita, StorageGRID supporta tre interfacce di rete per nodo della griglia, consentendo di configurare la rete per ogni singolo nodo della griglia in base ai requisiti di sicurezza e accesso.

Per ulteriori informazioni sulla topologia di rete, vederelink:../network/index.html["Linee guida per il networking"] .



=== Rete a griglia

Necessario.  La rete Grid viene utilizzata per tutto il traffico StorageGRID interno.  Fornisce connettività tra tutti i nodi della griglia, in tutti i siti e le sottoreti.



=== Rete di amministrazione

Opzionale.  La rete di amministrazione viene solitamente utilizzata per l'amministrazione e la manutenzione del sistema.  Può essere utilizzato anche per l'accesso al protocollo client.  La rete di amministrazione è in genere una rete privata e non deve essere instradabile tra i siti.



=== Rete clienti

Opzionale.  La rete client è una rete aperta solitamente utilizzata per fornire accesso alle applicazioni client S3, in modo che la rete Grid possa essere isolata e protetta.  La rete client può comunicare con qualsiasi subnet raggiungibile tramite il gateway locale.



== Linee guida

* Ogni nodo StorageGRID richiede un'interfaccia di rete dedicata, un indirizzo IP, una subnet mask e un gateway per ogni rete a cui è assegnato.
* Un nodo della griglia non può avere più di un'interfaccia su una rete.
* È supportato un singolo gateway per rete, per nodo della griglia, che deve trovarsi sulla stessa subnet del nodo.  Se necessario, è possibile implementare un routing più complesso nel gateway.
* Su ogni nodo, ogni rete è mappata su un'interfaccia di rete specifica.
+
[cols="1a,1a"]
|===
| Rete | Nome dell'interfaccia 


 a| 
Griglia
 a| 
eth0



 a| 
Amministratore (facoltativo)
 a| 
eth1



 a| 
Cliente (facoltativo)
 a| 
eth2

|===
* Se il nodo è connesso a un dispositivo StorageGRID , per ogni rete vengono utilizzate porte specifiche.  Per maggiori dettagli, consultare le istruzioni di installazione dell'elettrodomestico.
* Il percorso predefinito viene generato automaticamente, per nodo.  Se eth2 è abilitato, 0.0.0.0/0 utilizza la rete client su eth2.  Se eth2 non è abilitato, 0.0.0.0/0 utilizza la rete Grid su eth0.
* La rete client non diventa operativa finché il nodo della griglia non si è unito alla griglia
* La rete di amministrazione può essere configurata durante la distribuzione del nodo della griglia per consentire l'accesso all'interfaccia utente di installazione prima che la griglia sia completamente installata.




== Interfacce opzionali

Facoltativamente, è possibile aggiungere interfacce extra a un nodo.  Ad esempio, potresti voler aggiungere un'interfaccia trunk a un nodo di amministrazione o gateway, in modo da poter utilizzarelink:../admin/configure-vlan-interfaces.html["Interfacce VLAN"] per separare il traffico appartenente a diverse applicazioni o tenant.  Oppure, potresti voler aggiungere un'interfaccia di accesso da utilizzare in unlink:../admin/configure-high-availability-group.html["gruppo ad alta disponibilità (HA)"] .

Per aggiungere interfacce trunk o di accesso, vedere quanto segue:

* *VMware (dopo l'installazione del nodo)*:link:../maintain/vmware-adding-trunk-or-access-interfaces-to-node.html["VMware: aggiungi trunk o interfacce di accesso a un nodo"]
+
** *Red Hat Enterprise Linux (prima di installare il nodo)*:link:../rhel/creating-node-configuration-files.html["Creare file di configurazione del nodo"]
** *Ubuntu o Debian (prima di installare il nodo)*:link:../ubuntu/creating-node-configuration-files.html["Creare file di configurazione del nodo"]
** *RHEL, Ubuntu o Debian (dopo aver installato il nodo)*:link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux: aggiungere interfacce trunk o di accesso a un nodo"]



