---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: 'È possibile utilizzare gruppi ad alta disponibilità (HA) per fornire connessioni ad alta disponibilità a StorageGRID per i dati degli oggetti e per uso amministrativo.' 
---
= Come vengono utilizzati i gruppi HA?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare gruppi ad alta disponibilità (HA) per fornire connessioni ad alta disponibilità a StorageGRID per i dati degli oggetti e per uso amministrativo.

* Un gruppo HA può fornire connessioni amministrative ad alta disponibilità al Grid Manager o al Tenant Manager.
* Un gruppo HA può fornire connessioni dati ad alta disponibilità per i client S3.
* Un gruppo HA che contiene una sola interfaccia consente di fornire molti indirizzi VIP e di impostare esplicitamente indirizzi IPv6.


Un gruppo HA può garantire un'elevata disponibilità solo se tutti i nodi inclusi nel gruppo forniscono gli stessi servizi.  Quando si crea un gruppo HA, aggiungere le interfacce dai tipi di nodi che forniscono i servizi richiesti.

* *Nodi amministrativi*: includono il servizio Load Balancer e consentono l'accesso al Grid Manager o al Tenant Manager.
* *Nodi gateway*: includono il servizio Load Balancer.


[cols="1a,2a"]
|===
| Scopo del gruppo HA | Aggiungi nodi di questo tipo al gruppo HA 


 a| 
Accesso a Grid Manager
 a| 
* Nodo amministratore primario (*Primario*)
* Nodi amministrativi non primari


*Nota:* il nodo di amministrazione primario deve essere l'interfaccia primaria.  Alcune procedure di manutenzione possono essere eseguite solo dal nodo di amministrazione primario.



 a| 
Accesso solo al Tenant Manager
 a| 
* Nodi amministrativi primari o non primari




 a| 
Accesso client S3 - Servizio Load Balancer
 a| 
* Nodi amministrativi
* Nodi gateway




 a| 
Accesso client S3 perlink:../admin/manage-s3-select-for-tenant-accounts.html["S3 Seleziona"]
 a| 
* Servizi elettrodomestici
* Nodi software basati su VMware


*Nota*: i gruppi HA sono consigliati quando si utilizza S3 Select, ma non sono obbligatori.

|===


== Limitazioni dell'utilizzo di gruppi HA con Grid Manager o Tenant Manager

Se un servizio Grid Manager o Tenant Manager non funziona, il failover del gruppo HA non viene attivato.

Se hai effettuato l'accesso a Grid Manager o Tenant Manager quando si verifica il failover, verrai disconnesso e dovrai effettuare nuovamente l'accesso per riprendere l'attività.

Alcune procedure di manutenzione non possono essere eseguite quando il nodo di amministrazione primario non è disponibile.  Durante il failover, è possibile utilizzare Grid Manager per monitorare il sistema StorageGRID .
