---
permalink: admin/index.html 
sidebar: sidebar 
keywords: how to administer storagegrid 
summary: Utilizzare queste istruzioni per configurare e amministrare un sistema StorageGRID . 
---
= Amministra StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare queste istruzioni per configurare e amministrare un sistema StorageGRID .



== Informazioni su queste istruzioni

Le attività principali per la configurazione e l'amministrazione StorageGRID consentono di:

* Utilizzare Grid Manager per impostare gruppi e utenti
* Creare account tenant per consentire alle applicazioni client S3 di archiviare e recuperare oggetti
* Configurare e gestire le reti StorageGRID
* Configura AutoSupport
* Gestisci le impostazioni del nodo




== Prima di iniziare

* Hai una conoscenza generale del sistema StorageGRID .
* Hai una conoscenza abbastanza approfondita delle shell dei comandi Linux, delle reti e della configurazione e installazione dell'hardware del server.

