---
permalink: admin/reviewing-storagegrid-encryption-methods.html 
sidebar: sidebar 
keywords: encryption, encrypting data, best practices 
summary: StorageGRID offre diverse opzioni per la crittografia dei dati.  Dovresti esaminare i metodi disponibili per determinare quali metodi soddisfano i tuoi requisiti di protezione dei dati. 
---
= Esaminare i metodi di crittografia StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID offre diverse opzioni per la crittografia dei dati.  Dovresti esaminare i metodi disponibili per determinare quali metodi soddisfano i tuoi requisiti di protezione dei dati.

La tabella fornisce un riepilogo di alto livello dei metodi di crittografia disponibili in StorageGRID.

[cols="1a,1a,1a"]
|===
| Opzione di crittografia | Come funziona | Si applica a 


 a| 
Server di gestione delle chiavi (KMS) in Grid Manager
 a| 
Voilink:kms-configuring.html["configurare un server di gestione delle chiavi"] per il sito StorageGRID e https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html["abilitare la crittografia dei nodi per l'appliance"^] .  Quindi, un nodo appliance si connette al KMS per richiedere una chiave di crittografia (KEK).  Questa chiave crittografa e decrittografa la chiave di crittografia dei dati (DEK) su ciascun volume.
 a| 
Nodi dell'appliance in cui è abilitata la *Crittografia nodo* durante l'installazione.  Tutti i dati presenti sull'appliance sono protetti contro la perdita fisica o la rimozione dal data center.

*Nota*: la gestione delle chiavi di crittografia con un KMS è supportata solo per i nodi di archiviazione e le appliance di servizi.



 a| 
Pagina Crittografia unità nel programma di installazione dell'appliance StorageGRID
 a| 
Se l'appliance contiene unità che supportano la crittografia hardware, è possibile impostare una passphrase dell'unità durante l'installazione.  Quando si imposta una passphrase per l'unità, è impossibile per chiunque recuperare dati validi dalle unità rimosse dal sistema, a meno che non si conosca la passphrase.  Prima di iniziare l'installazione, vai su *Configura hardware* > *Crittografia unità* per impostare una passphrase dell'unità che si applichi a tutte le unità auto-crittografanti gestite da StorageGRID in un nodo.
 a| 
Dispositivi che contengono unità auto-crittografanti.  Tutti i dati presenti sulle unità protette sono protetti contro la perdita fisica o la rimozione dal data center.

La crittografia dell'unità non si applica alle unità gestite SANtricity.  Se si dispone di un dispositivo di archiviazione con unità auto-crittografanti e controller SANtricity , è possibile abilitare la sicurezza delle unità in SANtricity.



 a| 
Sicurezza dell'unità in SANtricity System Manager
 a| 
Se la funzionalità Drive Security è abilitata per l'appliance StorageGRID , è possibile utilizzare https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/accessing-and-configuring-santricity-system-manager.html["Gestore del sistema SANtricity"^] per creare e gestire la chiave di sicurezza.  La chiave è necessaria per accedere ai dati presenti sulle unità protette.
 a| 
Dispositivi di archiviazione dotati di unità FDE (Full Disk Encryption) o unità auto-crittografanti.  Tutti i dati presenti sulle unità protette sono protetti contro la perdita fisica o la rimozione dal data center.  Non può essere utilizzato con alcuni elettrodomestici o con apparecchi di servizio.



 a| 
Crittografia degli oggetti memorizzati
 a| 
Si abilita illink:changing-network-options-object-encryption.html["Crittografia degli oggetti memorizzati"] opzione nel Grid Manager.  Se abilitata, tutti i nuovi oggetti che non sono crittografati a livello di bucket o a livello di oggetto vengono crittografati durante l'acquisizione.
 a| 
Dati di oggetti S3 appena acquisiti.

Gli oggetti archiviati esistenti non sono crittografati.  I metadati degli oggetti e altri dati sensibili non sono crittografati.



 a| 
Crittografia del bucket S3
 a| 
Si invia una richiesta PutBucketEncryption per abilitare la crittografia per il bucket.  Tutti i nuovi oggetti che non sono crittografati a livello di oggetto vengono crittografati durante l'acquisizione.
 a| 
Solo dati di oggetti S3 appena acquisiti.

È necessario specificare la crittografia per il bucket.  Gli oggetti bucket esistenti non sono crittografati.  I metadati degli oggetti e altri dati sensibili non sono crittografati.

link:../s3/operations-on-buckets.html["Operazioni sui bucket"]



 a| 
Crittografia lato server (SSE) degli oggetti S3
 a| 
Si invia una richiesta S3 per memorizzare un oggetto e includere `x-amz-server-side-encryption` intestazione della richiesta.
 a| 
Solo dati di oggetti S3 appena acquisiti.

È necessario specificare la crittografia per l'oggetto.  I metadati degli oggetti e altri dati sensibili non sono crittografati.

StorageGRID gestisce le chiavi.

link:../s3/using-server-side-encryption.html["Utilizzare la crittografia lato server"]



 a| 
Crittografia lato server degli oggetti S3 con chiavi fornite dal cliente (SSE-C)
 a| 
Si invia una richiesta S3 per memorizzare un oggetto e si includono tre intestazioni di richiesta.

* `x-amz-server-side-encryption-customer-algorithm`
* `x-amz-server-side-encryption-customer-key`
* `x-amz-server-side-encryption-customer-key-MD5`

 a| 
Solo dati di oggetti S3 appena acquisiti.

È necessario specificare la crittografia per l'oggetto.  I metadati degli oggetti e altri dati sensibili non sono crittografati.

Le chiavi vengono gestite all'esterno di StorageGRID.

link:../s3/using-server-side-encryption.html["Utilizzare la crittografia lato server"]



 a| 
Crittografia del volume esterno o dell'archivio dati
 a| 
Per crittografare un intero volume o un intero datastore, è possibile utilizzare un metodo di crittografia esterno a StorageGRID , se supportato dalla piattaforma di distribuzione.
 a| 
Tutti i dati degli oggetti, i metadati e i dati di configurazione del sistema, presupponendo che ogni volume o archivio dati sia crittografato.

Un metodo di crittografia esterno garantisce un controllo più rigoroso sugli algoritmi e sulle chiavi di crittografia.  Può essere combinato con gli altri metodi elencati.



 a| 
Crittografia degli oggetti al di fuori di StorageGRID
 a| 
Si utilizza un metodo di crittografia esterno a StorageGRID per crittografare i dati e i metadati degli oggetti prima che vengano acquisiti in StorageGRID.
 a| 
Solo dati e metadati degli oggetti (i dati di configurazione del sistema non sono crittografati).

Un metodo di crittografia esterno garantisce un controllo più rigoroso sugli algoritmi e sulle chiavi di crittografia.  Può essere combinato con gli altri metodi elencati.

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html["Amazon Simple Storage Service - Guida per l'utente: protezione dei dati mediante crittografia lato client"^]

|===


== Utilizzare più metodi di crittografia

A seconda delle esigenze, è possibile utilizzare più di un metodo di crittografia contemporaneamente. Per esempio:

* È possibile utilizzare un KMS per proteggere i nodi degli apparecchi e anche utilizzare la funzionalità di sicurezza dell'unità in SANtricity System Manager per "crittografare due volte" i dati sulle unità auto-crittografanti negli stessi apparecchi.
* È possibile utilizzare un KMS per proteggere i dati sui nodi dell'appliance e utilizzare anche l'opzione di crittografia degli oggetti archiviati per crittografare tutti gli oggetti quando vengono acquisiti.


Se solo una piccola parte dei tuoi oggetti richiede la crittografia, valuta la possibilità di controllare la crittografia a livello di bucket o di singolo oggetto.  L'abilitazione di più livelli di crittografia comporta un costo aggiuntivo in termini di prestazioni.
