---
permalink: admin/supported-ciphers-for-outgoing-tls-connections.html 
sidebar: sidebar 
keywords: tls cipher suites, transport layer security connections 
summary: 'Il sistema StorageGRID supporta un set limitato di suite di crittografia per le connessioni Transport Layer Security \(TLS\) ai sistemi esterni utilizzati per la federazione delle identità e i pool di archiviazione cloud.' 
---
= Cifrature supportate per le connessioni TLS in uscita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema StorageGRID supporta un set limitato di suite di crittografia per le connessioni Transport Layer Security (TLS) ai sistemi esterni utilizzati per la federazione delle identità e i pool di archiviazione cloud.



== Versioni supportate di TLS

StorageGRID supporta TLS 1.2 e TLS 1.3 per le connessioni a sistemi esterni utilizzati per la federazione delle identità e i pool di archiviazione cloud.

I cifrari TLS supportati per l'uso con sistemi esterni sono stati selezionati per garantire la compatibilità con una vasta gamma di sistemi esterni. L'elenco è più lungo dell'elenco dei cifrari supportati per l'uso con le applicazioni client S3. Per configurare i cifrari, vai su *CONFIGURAZIONE* > *Sicurezza* > *Impostazioni di sicurezza* e seleziona *Criteri TLS e SSH*.


NOTE: Le opzioni di configurazione TLS, quali versioni del protocollo, cifrature, algoritmi di scambio di chiavi e algoritmi MAC, non sono configurabili in StorageGRID.  Per richieste specifiche su queste impostazioni, contattare il rappresentante dell'account NetApp .
