---
permalink: s3/configuring-tenant-accounts-and-connections.html 
sidebar: sidebar 
keywords: aws cli, test s3 client connection 
summary: 'È possibile utilizzare l"interfaccia a riga di comando di Amazon Web Services (AWS CLI) per testare la connessione al sistema e verificare di poter leggere e scrivere oggetti.' 
---
= Testare la configurazione dell'API REST S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare l'interfaccia a riga di comando di Amazon Web Services (AWS CLI) per testare la connessione al sistema e verificare di poter leggere e scrivere oggetti.

.Prima di iniziare
* Hai scaricato e installato AWS CLI da https://aws.amazon.com/cli["aws.amazon.com/cli"^] .
* Facoltativamente, hailink:../admin/configuring-load-balancer-endpoints.html["creato un endpoint del bilanciatore del carico"] .  In caso contrario, è necessario conoscere l'indirizzo IP del nodo di archiviazione a cui si desidera connettersi e il numero di porta da utilizzare. Vedere link:../admin/summary-ip-addresses-and-ports-for-client-connections.html["Indirizzi IP e porte per le connessioni client"] .
* Hailink:../admin/creating-tenant-account.html["creato un account tenant S3"] .
* Hai effettuato l'accesso al tenant elink:../tenant/creating-your-own-s3-access-keys.html["ha creato una chiave di accesso"] .


Per i dettagli su questi passaggi, vederelink:../admin/configuring-client-connections.html["Configurare le connessioni client"] .

.Passi
. Configura le impostazioni AWS CLI per utilizzare l'account creato nel sistema StorageGRID :
+
.. Entra nella modalità di configurazione: `aws configure`
.. Inserisci l'ID della chiave di accesso per l'account che hai creato.
.. Inserisci la chiave di accesso segreta per l'account che hai creato.
.. Inserisci la regione predefinita da utilizzare. Ad esempio,  `us-east-1` .
.. Immettere il formato di output predefinito da utilizzare oppure premere *Invio* per selezionare JSON.


. Crea un bucket.
+
In questo esempio si presuppone che sia stato configurato un endpoint del bilanciatore del carico per utilizzare l'indirizzo IP 10.96.101.17 e la porta 10443.

+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443
--no-verify-ssl create-bucket --bucket testbucket
----
+
Se il bucket viene creato correttamente, viene restituita la posizione del bucket, come mostrato nell'esempio seguente:

+
[listing]
----
"Location": "/testbucket"
----
. Carica un oggetto.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
put-object --bucket testbucket --key s3.pdf --body C:\s3-test\upload\s3.pdf
----
+
Se l'oggetto viene caricato correttamente, viene restituito un Etag, ovvero un hash dei dati dell'oggetto.

. Elenca il contenuto del bucket per verificare che l'oggetto sia stato caricato.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
list-objects --bucket testbucket
----
. Elimina l'oggetto.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
delete-object --bucket testbucket --key s3.pdf
----
. Elimina il bucket.
+
[listing]
----
aws s3api --endpoint-url https://10.96.101.17:10443 --no-verify-ssl
delete-bucket --bucket testbucket
----

