---
permalink: s3/deprecated-get-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated GET compliance requests 
summary: La richiesta di conformità del bucket GET è obsoleta.  Tuttavia, puoi continuare a utilizzare questa richiesta per determinare le impostazioni di conformità attualmente in vigore per un bucket Conforme legacy esistente. 
---
= Obsoleto: richiesta di conformità del bucket GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La richiesta di conformità del bucket GET è obsoleta.  Tuttavia, puoi continuare a utilizzare questa richiesta per determinare le impostazioni di conformità attualmente in vigore per un bucket Conforme legacy esistente.

[NOTE]
====
La funzionalità StorageGRID Compliance disponibile nelle precedenti versioni StorageGRID è obsoleta ed è stata sostituita da S3 Object Lock.  Per maggiori dettagli vedere quanto segue:

* link:../s3/use-s3-api-for-s3-object-lock.html["Utilizzare l'API REST S3 per configurare S3 Object Lock"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Knowledge Base di NetApp : come gestire i bucket Compliant legacy in StorageGRID 11.5"^]


====
Per completare questa operazione è necessario disporre dell'autorizzazione s3:GetBucketCompliance oppure essere l'account root.



== Richiedi esempio

Questa richiesta di esempio consente di determinare le impostazioni di conformità per il bucket denominato `mybucket` .

[listing, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Esempio di risposta

Nella risposta XML, `<SGCompliance>` elenca le impostazioni di conformità in vigore per il bucket.  Questa risposta di esempio mostra le impostazioni di conformità per un bucket in cui ogni oggetto verrà conservato per un anno (525.600 minuti), a partire dal momento in cui l'oggetto viene inserito nella griglia.  Al momento non esiste alcun blocco legale su questo bucket.  Ogni oggetto verrà automaticamente eliminato dopo un anno.

[listing, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
[cols="1a,2a"]
|===
| Nome | Descrizione 


 a| 
Periodo di conservazioneMinuti
 a| 
Durata del periodo di conservazione degli oggetti aggiunti a questo bucket, in minuti.  Il periodo di conservazione inizia quando l'oggetto viene inserito nella griglia.



 a| 
LegalHold
 a| 
* Vero: questo bucket è attualmente sottoposto a blocco legale.  Gli oggetti in questo bucket non possono essere eliminati finché non viene revocata la sospensione legale, anche se il periodo di conservazione è scaduto.
* Falso: questo bucket non è attualmente sottoposto a blocco legale.  Gli oggetti in questo bucket possono essere eliminati alla scadenza del periodo di conservazione.




 a| 
Eliminazione automatica
 a| 
* Vero: gli oggetti in questo bucket verranno eliminati automaticamente alla scadenza del periodo di conservazione, a meno che il bucket non sia soggetto a conservazione legale.
* Falso: gli oggetti in questo bucket non verranno eliminati automaticamente alla scadenza del periodo di conservazione.  Se vuoi eliminarli, devi eliminarli manualmente.


|===


== Risposte di errore

Se il bucket non è stato creato per essere conforme, il codice di stato HTTP per la risposta è `404 Not Found` , con un codice di errore S3 di `XNoSuchBucketCompliance` .
