---
permalink: s3/get-bucket-metadata-notification-configuration-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket metadata notification configuration 
summary: 'La richiesta di configurazione della notifica dei metadati del bucket GET consente di recuperare l"XML di configurazione utilizzato per configurare l"integrazione della ricerca per i singoli bucket.' 
---
= Configurazione della notifica dei metadati del bucket GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La richiesta di configurazione della notifica dei metadati del bucket GET consente di recuperare l'XML di configurazione utilizzato per configurare l'integrazione della ricerca per i singoli bucket.

Per completare questa operazione è necessario disporre dell'autorizzazione s3:GetBucketMetadataNotification oppure essere l'account root.



== Richiedi esempio

Questa richiesta recupera la configurazione della notifica dei metadati per il bucket denominato `bucket` .

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Risposta

Il corpo della risposta include la configurazione della notifica dei metadati per il bucket.  La configurazione della notifica dei metadati consente di determinare come configurare il bucket per l'integrazione della ricerca.  Ciò significa che è possibile determinare quali oggetti sono indicizzati e a quali endpoint vengono inviati i metadati degli oggetti.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
Ogni configurazione di notifica dei metadati include una o più regole.  Ogni regola specifica gli oggetti a cui si applica e la destinazione a cui StorageGRID deve inviare i metadati degli oggetti.  Le destinazioni devono essere specificate utilizzando l'URN di un endpoint StorageGRID .

[cols="1a,2a,1a"]
|===
| Nome | Descrizione | Necessario 


 a| 
MetadatiNotificaConfigurazione
 a| 
Tag contenitore per le regole utilizzate per specificare gli oggetti e la destinazione delle notifiche dei metadati.

Contiene uno o più elementi Rule.
 a| 
SÌ



 a| 
Regola
 a| 
Tag contenitore per una regola che identifica gli oggetti i cui metadati devono essere aggiunti a un indice specificato.

Le regole con prefissi sovrapposti vengono rifiutate.

Incluso nell'elemento MetadataNotificationConfiguration.
 a| 
SÌ



 a| 
ID
 a| 
Identificatore univoco per la regola.

Incluso nell'elemento Regola.
 a| 
NO



 a| 
Stato
 a| 
Lo stato può essere "Abilitato" o "Disabilitato".  Non viene intrapresa alcuna azione per le regole disabilitate.

Incluso nell'elemento Regola.
 a| 
SÌ



 a| 
Prefisso
 a| 
Gli oggetti che corrispondono al prefisso sono interessati dalla regola e i loro metadati vengono inviati alla destinazione specificata.

Per trovare la corrispondenza con tutti gli oggetti, specificare un prefisso vuoto.

Incluso nell'elemento Regola.
 a| 
SÌ



 a| 
Destinazione
 a| 
Tag contenitore per la destinazione di una regola.

Incluso nell'elemento Regola.
 a| 
SÌ



 a| 
Urna
 a| 
URN della destinazione a cui vengono inviati i metadati dell'oggetto.  Deve essere l'URN di un endpoint StorageGRID con le seguenti proprietà:

* `es`deve essere il terzo elemento.
* L'URN deve terminare con l'indice e il tipo in cui sono archiviati i metadati, nel formato `domain-name/myindex/mytype` .


Gli endpoint vengono configurati tramite Tenant Manager o Tenant Management API.  Hanno la seguente forma:

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


L'endpoint deve essere configurato prima di inviare il file XML di configurazione, altrimenti la configurazione fallirà con un errore 404.

L'urna è inclusa nell'elemento Destinazione.
 a| 
SÌ

|===


== Esempio di risposta

L'XML incluso tra `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>` tags mostra come l'integrazione con un endpoint di integrazione della ricerca è configurata per il bucket.  In questo esempio, i metadati dell'oggetto vengono inviati a un indice Elasticsearch denominato `current` e digita denominato `2017` che è ospitato in un dominio AWS denominato `records` .

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Informazioni correlate
link:../tenant/index.html["Utilizzare un account tenant"]
