---
permalink: s3/get-storage-usage-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET storage usage request 
summary: 'La richiesta GET Storage Usage indica la quantità totale di spazio di archiviazione utilizzato da un account e per ciascun bucket associato all"account.' 
---
= Richiesta di utilizzo dello spazio di archiviazione GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La richiesta GET Storage Usage indica la quantità totale di spazio di archiviazione utilizzato da un account e per ciascun bucket associato all'account.

La quantità di spazio di archiviazione utilizzata da un account e dai suoi bucket può essere ottenuta tramite una richiesta ListBuckets modificata con `x-ntap-sg-usage` parametro di query.  L'utilizzo dello spazio di archiviazione del bucket viene monitorato separatamente dalle richieste PUT e DELETE elaborate dal sistema.  Potrebbe verificarsi un ritardo prima che i valori di utilizzo corrispondano ai valori previsti in base all'elaborazione delle richieste, in particolare se il sistema è sottoposto a un carico elevato.

Per impostazione predefinita, StorageGRID tenta di recuperare le informazioni sull'utilizzo utilizzando la coerenza globale forte.  Se non è possibile ottenere una coerenza globale forte, StorageGRID tenta di recuperare le informazioni sull'utilizzo con una coerenza del sito forte.

Per completare questa operazione è necessario disporre dell'autorizzazione s3:ListAllMyBuckets oppure essere l'account root.



== Richiedi esempio

[listing, subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Esempio di risposta

Questo esempio mostra un account con quattro oggetti e 12 byte di dati in due bucket.  Ogni bucket contiene due oggetti e sei byte di dati.

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----


== Controllo delle versioni

Ogni versione dell'oggetto memorizzata contribuirà a `ObjectCount` E `DataBytes` valori nella risposta.  I marcatori di eliminazione non vengono aggiunti al `ObjectCount` totale.

.Informazioni correlate
link:consistency-controls.html["Valori di coerenza"]
