---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: 'L"operazione UploadPart carica una parte in un caricamento multiparte per un oggetto.' 
---
= CaricaParte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'operazione UploadPart carica una parte in un caricamento multiparte per un oggetto.



== Intestazioni di richiesta supportate

Sono supportate le seguenti intestazioni di richiesta:

* `x-amz-checksum-sha256`
* `Content-Length`
* `Content-MD5`




== Intestazioni di richiesta per la crittografia lato server

Se hai specificato la crittografia SSE-C per la richiesta CreateMultipartUpload, devi includere anche le seguenti intestazioni di richiesta in ogni richiesta UploadPart:

* `x-amz-server-side-encryption-customer-algorithm`: Specificare `AES256` .
* `x-amz-server-side-encryption-customer-key`: Specificare la stessa chiave di crittografia fornita nella richiesta CreateMultipartUpload.
* `x-amz-server-side-encryption-customer-key-MD5`: Specificare lo stesso digest MD5 fornito nella richiesta CreateMultipartUpload.



CAUTION: Le chiavi di crittografia fornite non vengono mai memorizzate.  Se si perde una chiave di crittografia, si perde anche l'oggetto corrispondente.  Prima di utilizzare le chiavi fornite dal cliente per proteggere i dati degli oggetti, rivedere le considerazioni inlink:using-server-side-encryption.html["Utilizzare la crittografia lato server"] .

Se hai specificato un checksum SHA-256 durante la richiesta CreateMultipartUpload, devi includere anche la seguente intestazione di richiesta in ogni richiesta UploadPart:

* `x-amz-checksum-sha256`: Specificare il checksum SHA-256 per questa parte.




== Intestazioni di richiesta non supportate

Le seguenti intestazioni di richiesta non sono supportate:

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== Controllo delle versioni

Il caricamento multiparte consiste in operazioni separate per avviare il caricamento, elencare i caricamenti, caricare le parti, assemblare le parti caricate e completare il caricamento.  Gli oggetti vengono creati (e sottoposti a controllo di versione, se applicabile) quando viene eseguita l'operazione CompleteMultipartUpload.
