---
permalink: s3/using-server-side-encryption.html 
sidebar: sidebar 
keywords: server side encryption, encryption, operations on objects, objects 
summary: 'La crittografia lato server consente di proteggere i dati degli oggetti quando sono inattivi.  StorageGRID crittografa i dati durante la scrittura dell"oggetto e li decrittografa quando si accede all"oggetto.' 
---
= Utilizzare la crittografia lato server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La crittografia lato server consente di proteggere i dati degli oggetti quando sono inattivi.  StorageGRID crittografa i dati durante la scrittura dell'oggetto e li decrittografa quando si accede all'oggetto.

Se si desidera utilizzare la crittografia lato server, è possibile scegliere una delle due opzioni reciprocamente esclusive, in base al modo in cui vengono gestite le chiavi di crittografia:

* *SSE (crittografia lato server con chiavi gestite StorageGRID)*: quando si invia una richiesta S3 per archiviare un oggetto, StorageGRID crittografa l'oggetto con una chiave univoca.  Quando si invia una richiesta S3 per recuperare l'oggetto, StorageGRID utilizza la chiave memorizzata per decrittografare l'oggetto.
* *SSE-C (crittografia lato server con chiavi fornite dal cliente)*: quando si invia una richiesta S3 per archiviare un oggetto, si fornisce la propria chiave di crittografia.  Quando recuperi un oggetto, fornisci la stessa chiave di crittografia come parte della tua richiesta.  Se le due chiavi di crittografia corrispondono, l'oggetto viene decrittografato e vengono restituiti i dati dell'oggetto.
+
Mentre StorageGRID gestisce tutte le operazioni di crittografia e decrittografia degli oggetti, è necessario gestire le chiavi di crittografia fornite.

+

CAUTION: Le chiavi di crittografia fornite non vengono mai memorizzate.  Se si perde una chiave di crittografia, si perde anche l'oggetto corrispondente.

+

NOTE: Se un oggetto è crittografato con SSE o SSE-C, tutte le impostazioni di crittografia a livello di bucket o di griglia vengono ignorate.





== Utilizzare SSE

Per crittografare un oggetto con una chiave univoca gestita da StorageGRID, utilizzare la seguente intestazione di richiesta:

`x-amz-server-side-encryption`

L'intestazione della richiesta SSE è supportata dalle seguenti operazioni sugli oggetti:

* link:put-object.html["MettiOggetto"]
* link:put-object-copy.html["CopiaOggetto"]
* link:initiate-multipart-upload.html["CreaCaricamentoMultiparte"]




== Utilizzare SSE-C

Per crittografare un oggetto con una chiave univoca gestita da te, puoi utilizzare tre intestazioni di richiesta:

[cols="1a,2a"]
|===
| Intestazione della richiesta | Descrizione 


 a| 
`x-amz-server-side​-encryption​-customer-algorithm`
 a| 
Specificare l'algoritmo di crittografia.  Il valore dell'intestazione deve essere `AES256` .



 a| 
`x-amz-server-side​-encryption​-customer-key`
 a| 
Specificare la chiave di crittografia che verrà utilizzata per crittografare o decrittografare l'oggetto.  Il valore della chiave deve essere a 256 bit, codificato in base64.



 a| 
`x-amz-server-side​-encryption​-customer-key-MD5`
 a| 
Specificare il digest MD5 della chiave di crittografia secondo RFC 1321, utilizzato per garantire che la chiave di crittografia sia stata trasmessa senza errori.  Il valore per il digest MD5 deve essere codificato in base64 a 128 bit.

|===
Le intestazioni delle richieste SSE-C sono supportate dalle seguenti operazioni sugli oggetti:

* link:get-object.html["OttieniOggetto"]
* link:head-object.html["HeadObject"]
* link:put-object.html["MettiOggetto"]
* link:put-object-copy.html["CopiaOggetto"]
* link:initiate-multipart-upload.html["CreaCaricamentoMultiparte"]
* link:upload-part.html["CaricaParte"]
* link:upload-part-copy.html["CaricaParteCopia"]




== Considerazioni sull'utilizzo della crittografia lato server con chiavi fornite dal cliente (SSE-C)

Prima di utilizzare SSE-C, tenere presente quanto segue:

* Devi usare https.
+

CAUTION: StorageGRID rifiuta qualsiasi richiesta effettuata tramite http quando si utilizza SSE-C. Per motivi di sicurezza, è opportuno considerare compromessa qualsiasi chiave inviata accidentalmente tramite http.  Scartare la chiave e ruotarla come appropriato.

* L'ETag nella risposta non è l'MD5 dei dati dell'oggetto.
* È necessario gestire la mappatura delle chiavi di crittografia sugli oggetti.  StorageGRID non memorizza le chiavi di crittografia.  Sei responsabile del monitoraggio della chiave di crittografia fornita per ciascun oggetto.
* Se il bucket è abilitato al controllo delle versioni, ogni versione dell'oggetto dovrebbe avere la propria chiave di crittografia.  Sei responsabile del monitoraggio della chiave di crittografia utilizzata per ogni versione dell'oggetto.
* Poiché le chiavi di crittografia vengono gestite sul lato client, è necessario gestire anche eventuali misure di sicurezza aggiuntive, come la rotazione delle chiavi, sul lato client.
+

CAUTION: Le chiavi di crittografia fornite non vengono mai memorizzate.  Se si perde una chiave di crittografia, si perde anche l'oggetto corrispondente.

* Se per il bucket è configurata la replica tra griglie o la replica CloudMirror, non è possibile acquisire oggetti SSE-C. L'operazione di acquisizione non andrà a buon fine.


.Informazioni correlate
https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html["Guida per l'utente di Amazon S3: utilizzo della crittografia lato server con chiavi fornite dal cliente (SSE-C)"^]
