---
permalink: monitor/about-bycast-log.html 
sidebar: sidebar 
keywords: bycast, log 
summary: 'Il file /var/local/log/bycast.log è il file principale per la risoluzione dei problemi del software StorageGRID .  C"è un `bycast.log` file per ogni nodo della griglia.  Il file contiene messaggi specifici per quel nodo della griglia.' 
---
= Informazioni su bycast.log
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il file `/var/local/log/bycast.log` è il file principale per la risoluzione dei problemi del software StorageGRID .  C'è un `bycast.log` file per ogni nodo della griglia.  Il file contiene messaggi specifici per quel nodo della griglia.

Il file `/var/local/log/bycast-err.log` è un sottoinsieme di `bycast.log` .  Contiene messaggi di gravità ERRORE e CRITICO.

Facoltativamente, è possibile modificare la destinazione dei log di controllo e inviare le informazioni di controllo a un server syslog esterno. I registri locali dei record di controllo continuano a essere generati e archiviati quando viene configurato un server syslog esterno. Vedere link:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e le destinazioni dei registri"] .



== Rotazione dei file per bycast.log

Quando il `bycast.log` Quando il file raggiunge 1 GB, il file esistente viene salvato e viene avviato un nuovo file di registro.

Il file salvato viene rinominato `bycast.log.1` e il nuovo file è denominato `bycast.log` .  Quando il nuovo `bycast.log` raggiunge 1 GB, `bycast.log.1` viene rinominato e compresso per diventare `bycast.log.2.gz` , E `bycast.log` è rinominato `bycast.log.1` .

Il limite di rotazione per `bycast.log` è di 21 file.  Quando la 22a versione del `bycast.log` viene creato un file, il file più vecchio viene eliminato.

Il limite di rotazione per `bycast-err.log` è composto da sette file.


NOTE: Se un file di registro è stato compresso, non è possibile decomprimerlo nella stessa posizione in cui è stato scritto.  La decompressione del file nella stessa posizione può interferire con gli script di rotazione del registro.

Facoltativamente, è possibile modificare la destinazione dei log di controllo e inviare le informazioni di controllo a un server syslog esterno. I registri locali dei record di controllo continuano a essere generati e archiviati quando viene configurato un server syslog esterno. Vedere link:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e le destinazioni dei registri"] .

.Informazioni correlate
link:collecting-log-files-and-system-data.html["Raccogli file di registro e dati di sistema"]



== Messaggi in bycast.log

Messaggi in `bycast.log` sono scritti dall'ADE (Asynchronous Distributed Environment).  ADE è l'ambiente di runtime utilizzato dai servizi di ciascun nodo della griglia.

Esempio di messaggio ADE:

[listing]
----
May 15 14:07:11 um-sec-rg1-agn3 ADE: |12455685    0357819531
SVMR EVHR 2019-05-05T27T17:10:29.784677| ERROR 0906 SVMR: Health
check on volume 3 has failed with reason 'TOUT'
----
I messaggi ADE contengono le seguenti informazioni:

[cols="1a,2a"]
|===
| Segmento del messaggio | Valore nell'esempio 


 a| 
Nodo ID
| 12455685 


 a| 
ID processo ADE
| 0357819531 


 a| 
Nome del modulo
| SVMR 


 a| 
Identificatore del messaggio
| EVHR 


 a| 
Ora di sistema UTC
| 2019-05-05T27T17:10:29.784677 (AAAA-MM-GGTHH:MM:SS.uuuuuu) 


 a| 
Livello di gravità
| ERRORE 


 a| 
Numero di tracciamento interno
| 0906 


 a| 
Messaggio
| SVMR: Il controllo dello stato di salute del volume 3 è fallito con il motivo 'TOUT' 
|===


== Gravità dei messaggi in bycast.log

I messaggi in `bycast.log` vengono assegnati livelli di gravità.

Per esempio:

* *AVVISO* -- Si è verificato un evento che dovrebbe essere registrato.  La maggior parte dei messaggi di registro si trova a questo livello.
* *ATTENZIONE* -- Si è verificata una condizione imprevista.
* *ERRORE* -- Si è verificato un errore grave che avrà ripercussioni sulle operazioni.
* *CRITICO* -- Si è verificata una condizione anomala che ha interrotto le normali operazioni.  È necessario intervenire immediatamente sulla condizione di base.




== Codici di errore in `bycast.log`

La maggior parte dei messaggi di errore in `bycast.log` contengono codici di errore.

La tabella seguente elenca i codici non numerici comuni in `bycast.log` Il significato esatto di un codice non numerico dipende dal contesto in cui viene riportato.

[cols="1a,1a"]
|===
| Codice di errore | Senso 


 a| 
SUCS
 a| 
Nessun errore



 a| 
GERR
 a| 
Sconosciuto



 a| 
CANC
 a| 
Annullato



 a| 
ABRT
 a| 
Abortito



 a| 
TUTTO
 a| 
Tempo scaduto



 a| 
INVL
 a| 
Non valido



 a| 
NFND
 a| 
Non trovato



 a| 
VERSO
 a| 
Versione



 a| 
CONF
 a| 
Configurazione



 a| 
FALLIRE
 a| 
Fallito



 a| 
ICPL
 a| 
Incompleto



 a| 
FATTO
 a| 
Fatto



 a| 
SUNV
 a| 
Servizio non disponibile

|===
La tabella seguente elenca i codici di errore numerici in `bycast.log` .

[cols="1a,2a,3a"]
|===
| Numero di errore | Codice di errore | Senso 


 a| 
001
 a| 
EPERM
 a| 
Operazione non consentita



 a| 
002
 a| 
ENOENTE
 a| 
Nessun file o directory con questo nome



 a| 
003
 a| 
ESRCH
 a| 
Nessun processo del genere



 a| 
004
 a| 
EINTR
 a| 
Chiamata di sistema interrotta



 a| 
005
 a| 
EIO
 a| 
errore di I/O



 a| 
006
 a| 
ENXIO
 a| 
Nessun dispositivo o indirizzo del genere



 a| 
007
 a| 
E2BIG
 a| 
Elenco argomenti troppo lungo



 a| 
008
 a| 
ENOEXEC
 a| 
Errore di formato Exec



 a| 
009
 a| 
EBADF
 a| 
Numero di file errato



 a| 
010
 a| 
BAMBINO
 a| 
Nessun processo figlio



 a| 
011
 a| 
DI NUOVO
 a| 
Riprova



 a| 
012
 a| 
ENOMEM
 a| 
Memoria esaurita



 a| 
013
 a| 
EACCES
 a| 
Permesso negato



 a| 
014
 a| 
ERRORE
 a| 
Indirizzo errato



 a| 
015
 a| 
ENOTBLK
 a| 
Dispositivo di blocco richiesto



 a| 
016
 a| 
EBUSY
 a| 
Dispositivo o risorsa occupati



 a| 
017
 a| 
EESI
 a| 
Il file esiste



 a| 
018
 a| 
EXDEV
 a| 
Collegamento tra dispositivi



 a| 
019
 a| 
ENODEV
 a| 
Nessun dispositivo del genere



 a| 
020
 a| 
ENOTDIR
 a| 
Non una directory



 a| 
021
 a| 
EISDIR
 a| 
È una directory



 a| 
022
 a| 
EINVAL
 a| 
Argomento non valido



 a| 
023
 a| 
ENFILE
 a| 
Overflow della tabella dei file



 a| 
024
 a| 
EMFILE
 a| 
Troppi file aperti



 a| 
025
 a| 
ENOTTY
 a| 
Non una macchina da scrivere



 a| 
026
 a| 
ETXTBSY
 a| 
File di testo occupato



 a| 
027
 a| 
EFBIG
 a| 
File troppo grande



 a| 
028
 a| 
ENOSPC
 a| 
Nessuno spazio rimasto sul dispositivo



 a| 
029
 a| 
ESPIARE
 a| 
Ricerca illegale



 a| 
030
 a| 
EROFS
 a| 
File system di sola lettura



 a| 
031
 a| 
EMLINK
 a| 
Troppi link



 a| 
032
 a| 
EPIPE
 a| 
Tubo rotto



 a| 
033
 a| 
EDOM
 a| 
Argomento matematico fuori dal dominio della funzione



 a| 
034
 a| 
GAMMA
 a| 
Risultato matematico non rappresentabile



 a| 
035
 a| 
EDEADLK
 a| 
Si verificherebbe un blocco delle risorse



 a| 
036
 a| 
Smaltolungo
 a| 
Nome del file troppo lungo



 a| 
037
 a| 
ENOLCK
 a| 
Nessun blocco record disponibile



 a| 
038
 a| 
ENOSYS
 a| 
Funzione non implementata



 a| 
039
 a| 
ENOTEMPTY
 a| 
Directory non vuota



 a| 
040
 a| 
ELOOP
 a| 
Sono stati riscontrati troppi link simbolici



 a| 
041
 a| 
 a| 



 a| 
042
 a| 
ENOMSG
 a| 
Nessun messaggio del tipo desiderato



 a| 
043
 a| 
EIDRM
 a| 
Identificatore rimosso



 a| 
044
 a| 
ECHRNG
 a| 
Numero di canale fuori intervallo



 a| 
045
 a| 
EL2NSYNC
 a| 
Livello 2 non sincronizzato



 a| 
046
 a| 
EL3HLT
 a| 
Livello 3 interrotto



 a| 
047
 a| 
EL3RST
 a| 
Ripristino di livello 3



 a| 
048
 a| 
ELNRNG
 a| 
Numero di collegamento fuori intervallo



 a| 
049
 a| 
EUNATCH
 a| 
Driver del protocollo non collegato



 a| 
050
 a| 
ENOCSI
 a| 
Nessuna struttura CSI disponibile



 a| 
051
 a| 
EL2HLT
 a| 
Livello 2 interrotto



 a| 
052
 a| 
EBADE
 a| 
Scambio non valido



 a| 
053
 a| 
EBADR
 a| 
Descrittore di richiesta non valido



 a| 
054
 a| 
EXFULL
 a| 
Scambio completo



 a| 
055
 a| 
ENOANO
 a| 
Nessun anodo



 a| 
056
 a| 
EBADRQC
 a| 
Codice di richiesta non valido



 a| 
057
 a| 
EBADSLT
 a| 
Slot non valido



 a| 
058
 a| 
 a| 



 a| 
059
 a| 
EBFONT
 a| 
Formato file font non valido



 a| 
060
 a| 
ENOSTR
 a| 
Dispositivo non in streaming



 a| 
061
 a| 
ENODATI
 a| 
Nessun dato disponibile



 a| 
062
 a| 
ETIME
 a| 
Timer scaduto



 a| 
063
 a| 
ENOSR
 a| 
Risorse fuori flusso



 a| 
064
 a| 
ENONET
 a| 
La macchina non è in rete



 a| 
065
 a| 
ENOPKG
 a| 
Pacchetto non installato



 a| 
066
 a| 
EREMOTE
 a| 
L'oggetto è remoto



 a| 
067
 a| 
ENOLINK
 a| 
Il collegamento è stato interrotto



 a| 
068
 a| 
EADV
 a| 
Errore di pubblicità



 a| 
069
 a| 
ESRMNT
 a| 
Errore di srmount



 a| 
070
 a| 
ECOMM
 a| 
Errore di comunicazione durante l'invio



 a| 
071
 a| 
EPROTO
 a| 
Errore di protocollo



 a| 
072
 a| 
EMULTIHOP
 a| 
Tentativo multihop



 a| 
073
 a| 
EDOTDOT
 a| 
Errore specifico RFS



 a| 
074
 a| 
EBADMSG
 a| 
Non è un messaggio di dati



 a| 
075
 a| 
EOVERFLOW
 a| 
Valore troppo grande per il tipo di dati definito



 a| 
076
 a| 
ENOTUNIQ
 a| 
Nome non univoco sulla rete



 a| 
077
 a| 
EBADFD
 a| 
Descrittore di file in stato non valido



 a| 
078
 a| 
EREMCHG
 a| 
Indirizzo remoto modificato



 a| 
079
 a| 
ELIBACC
 a| 
Impossibile accedere a una libreria condivisa necessaria



 a| 
080
 a| 
ELIBBAD
 a| 
Accesso a una libreria condivisa danneggiata



 a| 
081
 a| 
ELIBSCN
 a| 



 a| 
082
 a| 
ELIBMAX
 a| 
Tentativo di collegare troppe librerie condivise



 a| 
083
 a| 
ELIBEXEC
 a| 
Impossibile eseguire direttamente una libreria condivisa



 a| 
084
 a| 
EILSEQ
 a| 
Sequenza di byte non valida



 a| 
085
 a| 
RIAVVIARE
 a| 
La chiamata di sistema interrotta deve essere riavviata



 a| 
086
 a| 
ESTRPIPE
 a| 
Errore del tubo di flusso



 a| 
087
 a| 
EUSERS
 a| 
Troppi utenti



 a| 
088
 a| 
ENOTSOCK
 a| 
Funzionamento della presa su non presa



 a| 
089
 a| 
EDESTADDRREQ
 a| 
Indirizzo di destinazione richiesto



 a| 
090
 a| 
EMSGSIZE
 a| 
Messaggio troppo lungo



 a| 
091
 a| 
EPROTOTIPO
 a| 
Tipo di protocollo errato per il socket



 a| 
092
 a| 
ENOPROTOOPT
 a| 
Protocollo non disponibile



 a| 
093
 a| 
EPROTONOSUPPORT
 a| 
Protocollo non supportato



 a| 
094
 a| 
ESOCKTNOSUPPORT
 a| 
Tipo di socket non supportato



 a| 
095
 a| 
EOPNOTSUPP
 a| 
Operazione non supportata sull'endpoint di trasporto



 a| 
096
 a| 
EPFNOSUPPORT
 a| 
Famiglia di protocolli non supportata



 a| 
097
 a| 
EAFNOSUPPORT
 a| 
Indirizzo famiglia non supportato dal protocollo



 a| 
098
 a| 
EADDRINUSE
 a| 
Indirizzo già in uso



 a| 
099
 a| 
EADDRNOTAVAIL
 a| 
Impossibile assegnare l'indirizzo richiesto



 a| 
100
 a| 
ENETDOWN
 a| 
La rete è inattiva



 a| 
101
 a| 
ENETUNREACH
 a| 
La rete non è raggiungibile



 a| 
102
 a| 
ENETRESET
 a| 
Connessione di rete interrotta a causa del ripristino



 a| 
103
 a| 
ECONNABORTED
 a| 
Il software ha causato la terminazione della connessione



 a| 
104
 a| 
ECONNRESET
 a| 
Connessione ripristinata dal peer



 a| 
105
 a| 
ENOBUFS
 a| 
Nessuno spazio buffer disponibile



 a| 
106
 a| 
EISCONN
 a| 
L'endpoint di trasporto è già connesso



 a| 
107
 a| 
ENOTCONN
 a| 
L'endpoint di trasporto non è connesso



 a| 
108
 a| 
SPEGNIMENTO
 a| 
Impossibile inviare dopo l'arresto dell'endpoint di trasporto



 a| 
109
 a| 
ETOOMANYREFS
 a| 
Troppi riferimenti: impossibile unire



 a| 
110
 a| 
ETIMEDOUT
 a| 
Connessione scaduta



 a| 
111
 a| 
ECONNRIFIUTATO
 a| 
Connessione rifiutata



 a| 
112
 a| 
EHOSTDOWN
 a| 
L'host è inattivo



 a| 
113
 a| 
EHOSTUNREACH
 a| 
Nessun percorso per l'host



 a| 
114
 a| 
GIÀ
 a| 
Operazione già in corso



 a| 
115
 a| 
EINPROGRESS
 a| 
Operazione in corso



 a| 
116
 a| 
 a| 



 a| 
117
 a| 
EUCLEAN
 a| 
La struttura necessita di pulizia



 a| 
118
 a| 
ENOTNAM
 a| 
Non è un file di tipo denominato XENIX



 a| 
119
 a| 
DISPONIBILE
 a| 
Nessun semaforo XENIX disponibile



 a| 
120
 a| 
EISNAM
 a| 
È un file di tipo denominato



 a| 
121
 a| 
EREMOTEIO
 a| 
Errore di I/O remoto



 a| 
122
 a| 
EDQUOT
 a| 
Quota superata



 a| 
123
 a| 
ENOMEDIO
 a| 
Nessun mezzo trovato



 a| 
124
 a| 
TIPOMEDIO
 a| 
Tipo di mezzo sbagliato



 a| 
125
 a| 
ECANCELED
 a| 
Operazione annullata



 a| 
126
 a| 
ENOKEY
 a| 
Chiave richiesta non disponibile



 a| 
127
 a| 
EKEYEXPIRED
 a| 
La chiave è scaduta



 a| 
128
 a| 
EKEYREVOKED
 a| 
La chiave è stata revocata



 a| 
129
 a| 
EKEYREJECTED
 a| 
La chiave è stata rifiutata dal servizio



 a| 
130
 a| 
PROPRIETARIOMORTO
 a| 
Per mutex robusti: il proprietario è morto



 a| 
131
 a| 
NON RECUPERABILI
 a| 
Per mutex robusti: Stato non recuperabile

|===