---
permalink: monitor/information-you-should-monitor-regularly.html 
sidebar: sidebar 
keywords: when to monitor, what to monitor 
summary: 'Anche se il sistema StorageGRID può continuare a funzionare quando si verificano errori o parti della rete non sono disponibili, è opportuno monitorare e risolvere i potenziali problemi prima che influiscano sull"efficienza o sulla disponibilità della rete.' 
---
= Cosa e quando monitorare
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Anche se il sistema StorageGRID può continuare a funzionare quando si verificano errori o parti della rete non sono disponibili, è opportuno monitorare e risolvere i potenziali problemi prima che influiscano sull'efficienza o sulla disponibilità della rete.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Hailink:../admin/admin-group-permissions.html["autorizzazioni di accesso specifiche"] .


.Informazioni sulle attività di monitoraggio
Un sistema occupato genera grandi quantità di informazioni.  L'elenco seguente fornisce indicazioni sulle informazioni più importanti da monitorare costantemente.

[cols="1a,1a"]
|===
| Cosa monitorare | Frequenza 


 a| 
link:monitoring-system-health.html["Stato di salute del sistema"]
 a| 
Quotidiano



 a| 
Tasso a cuilink:monitoring-storage-capacity.html["Capacità degli oggetti e dei metadati del nodo di archiviazione"] viene consumato
 a| 
Settimanale



 a| 
link:monitoring-information-lifecycle-management.html["Operazioni di gestione del ciclo di vita delle informazioni"]
 a| 
Settimanale



 a| 
link:monitoring-network-connections-and-performance.html["Risorse di rete e di sistema"]
 a| 
Settimanale



 a| 
link:monitoring-tenant-activity.html["Attività degli inquilini"]
 a| 
Settimanale



 a| 
link:monitoring-object-ingest-and-retrieval-rates.html["Operazioni client S3"]
 a| 
Settimanale



 a| 
link:monitoring-load-balancing-operations.html["Operazioni di bilanciamento del carico"]
 a| 
Dopo la configurazione iniziale e dopo eventuali modifiche alla configurazione



 a| 
link:grid-federation-monitor-connections.html["Connessioni di federazione della rete"]
 a| 
Settimanale

|===