---
permalink: monitor/monitoring-put-and-get-performance.html 
sidebar: sidebar 
keywords: put, get, performance 
summary: 'È possibile monitorare le prestazioni di determinate operazioni, come l"archiviazione e il recupero di oggetti, per identificare modifiche che potrebbero richiedere ulteriori indagini.' 
---
= Monitorare le prestazioni PUT e GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile monitorare le prestazioni di determinate operazioni, come l'archiviazione e il recupero di oggetti, per identificare modifiche che potrebbero richiedere ulteriori indagini.

.Informazioni su questo compito
Per monitorare le prestazioni PUT e GET, è possibile eseguire i comandi S3 direttamente da una workstation oppure utilizzando l'applicazione open source S3tester.  Utilizzando questi metodi è possibile valutare le prestazioni indipendentemente da fattori esterni a StorageGRID, come problemi con un'applicazione client o problemi con una rete esterna.

Quando si eseguono test sulle operazioni PUT e GET, attenersi alle seguenti linee guida:

* Utilizza dimensioni degli oggetti paragonabili a quelle degli oggetti che solitamente inserisci nella tua griglia.
* Eseguire operazioni sia su siti locali che remoti.


Messaggi nellink:../audit/index.html["registro di controllo"] indicano il tempo totale necessario per eseguire determinate operazioni.  Ad esempio, per determinare il tempo di elaborazione totale per una richiesta S3 GET, è possibile esaminare il valore dell'attributo TIME nel messaggio di controllo SGET.  È inoltre possibile trovare l'attributo TIME nei messaggi di controllo per le seguenti operazioni S3: DELETE, GET, HEAD, Metadati aggiornati, POST, PUT

Quando si analizzano i risultati, bisogna considerare il tempo medio necessario per soddisfare una richiesta, nonché la produttività complessiva che è possibile ottenere.  Ripeti regolarmente gli stessi test e registra i risultati, in modo da poter identificare le tendenze che potrebbero richiedere indagini.

* Puoi https://github.com/s3tester["scarica S3tester da github"^] .

