---
permalink: monitor/removing-custom-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: È possibile rimuovere una regola di avviso personalizzata se non si desidera più utilizzarla. 
---
= Rimuovi regole di avviso personalizzate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere una regola di avviso personalizzata se non si desidera più utilizzarla.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:../admin/admin-group-permissions.html["Gestisci avvisi o autorizzazione di accesso root"] .


.Passi
. Selezionare *AVVISI* > *Regole*.
+
Viene visualizzata la pagina Regole di avviso.

. Seleziona il pulsante di opzione per la regola di avviso personalizzata che desideri rimuovere.
+
Non è possibile rimuovere una regola di avviso predefinita.

. Seleziona *Rimuovi regola personalizzata*.
+
Viene visualizzata una finestra di dialogo di conferma.

. Selezionare *OK* per rimuovere la regola di avviso.
+
Eventuali istanze attive dell'avviso verranno risolte entro 10 minuti.


