---
permalink: monitor/snmp-alert-notifications.html 
sidebar: sidebar 
keywords: how to use snmp notifications for alerts 
summary: 'Se si desidera che StorageGRID invii notifiche SNMP quando si verificano avvisi, è necessario abilitare l"agente SNMP StorageGRID e configurare una o più destinazioni trap.' 
---
= Imposta le notifiche SNMP per gli avvisi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera che StorageGRID invii notifiche SNMP quando si verificano avvisi, è necessario abilitare l'agente SNMP StorageGRID e configurare una o più destinazioni trap.

È possibile utilizzare l'opzione *CONFIGURAZIONE* > *Monitoraggio* > *Agente SNMP* in Grid Manager o gli endpoint SNMP per l'API di gestione della griglia per abilitare e configurare l'agente SNMP StorageGRID . L'agente SNMP supporta tutte e tre le versioni del protocollo SNMP.

Per informazioni su come configurare l'agente SNMP, vederelink:using-snmp-monitoring.html["Utilizzare il monitoraggio SNMP"] .

Dopo aver configurato l'agente SNMP StorageGRID , è possibile inviare due tipi di notifiche basate sugli eventi:

* Le trappole sono notifiche inviate dall'agente SNMP che non richiedono la conferma da parte del sistema di gestione.  Le trappole servono a notificare al sistema di gestione che si è verificato un evento all'interno StorageGRID, ad esempio l'attivazione di un avviso.  Le trappole sono supportate in tutte e tre le versioni di SNMP.
* Le informazioni sono simili alle trappole, ma richiedono il riconoscimento da parte del sistema di gestione.  Se l'agente SNMP non riceve una conferma entro un certo lasso di tempo, invia nuovamente l'informazione finché non riceve una conferma o finché non viene raggiunto il valore massimo di tentativi.  Le informazioni sono supportate in SNMPv2c e SNMPv3.


Le notifiche Trap and Inform vengono inviate quando viene attivato un avviso predefinito o personalizzato a qualsiasi livello di gravità.  Per sopprimere le notifiche SNMP per un avviso, è necessario configurare il silenzio per l'avviso. Vedere link:silencing-alert-notifications.html["Disattiva le notifiche di avviso"] .

Se la distribuzione StorageGRID include più nodi amministrativi, il nodo amministrativo primario è il mittente preferito per le notifiche di avviso, i pacchetti AutoSupport , le trap e le informazioni SNMP.  Se il nodo di amministrazione primario non è disponibile, le notifiche vengono inviate temporaneamente da altri nodi di amministrazione. Vedere link:../primer/what-admin-node-is.html["Che cos'è un nodo amministrativo?"] .
