---
permalink: monitor/viewing-manage-drives-tab.html 
sidebar: sidebar 
keywords: Manage drives tab, hardware diagnostics, fail drive, logically replace drive 
summary: La scheda Gestisci unità consente di accedere ai dettagli ed eseguire attività di risoluzione dei problemi e manutenzione sulle unità negli apparecchi che supportano questa funzionalità. 
---
= Visualizza la scheda Gestisci unità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La scheda Gestisci unità consente di accedere ai dettagli ed eseguire attività di risoluzione dei problemi e manutenzione sulle unità negli apparecchi che supportano questa funzionalità.

Utilizzando la scheda Gestisci unità, puoi effettuare le seguenti operazioni:

* Visualizza un layout delle unità di archiviazione dati nell'appliance
* Visualizza una tabella che elenca ciascuna posizione dell'unità, tipo, stato, versione del firmware e numero di serie
* Eseguire funzioni di risoluzione dei problemi e manutenzione su ciascuna unità


Per accedere alla scheda Gestisci unità, è necessario disporre dilink:../admin/admin-group-permissions.html["Amministratore dell'appliance di archiviazione o autorizzazione di accesso root"] .

Per informazioni sull'utilizzo della scheda Gestisci unità, vedere https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/manage-drives-tab.html["Utilizzare la scheda Gestisci unità"^] .
