---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: È possibile eseguire la configurazione di rete configurando gli indirizzi IP per i nodi della griglia tramite lo strumento Modifica IP. 
---
= Linee guida per l'indirizzo IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire la configurazione di rete configurando gli indirizzi IP per i nodi della griglia tramite lo strumento Modifica IP.

È necessario utilizzare lo strumento Modifica IP per apportare la maggior parte delle modifiche alla configurazione di rete inizialmente impostata durante la distribuzione della griglia.  Le modifiche manuali effettuate tramite comandi e file di rete Linux standard potrebbero non propagarsi a tutti i servizi StorageGRID e potrebbero non essere mantenute durante gli aggiornamenti, i riavvii o le procedure di ripristino dei nodi.


NOTE: La procedura di modifica dell'IP può rivelarsi una procedura dirompente.  Alcune parti della griglia potrebbero non essere disponibili finché non verrà applicata la nuova configurazione.


NOTE: Se si apportano modifiche solo all'elenco delle subnet della rete Grid, utilizzare Grid Manager per aggiungere o modificare la configurazione di rete.  In caso contrario, utilizzare lo strumento Modifica IP se Grid Manager non è accessibile a causa di un problema di configurazione di rete o se si sta eseguendo contemporaneamente una modifica del routing della rete Grid e altre modifiche di rete.


TIP: Se si desidera modificare l'indirizzo IP della rete Grid per tutti i nodi nella griglia, utilizzarelink:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["procedura speciale per modifiche a livello di griglia"] .



== Interfacce Ethernet

L'indirizzo IP assegnato a eth0 è sempre l'indirizzo IP della rete Grid del nodo della griglia.  L'indirizzo IP assegnato a eth1 è sempre l'indirizzo IP della rete di amministrazione del nodo della griglia.  L'indirizzo IP assegnato a eth2 è sempre l'indirizzo IP della rete client del nodo della griglia.

Si noti che su alcune piattaforme, come gli appliance StorageGRID , eth0, eth1 ed eth2 potrebbero essere interfacce aggregate composte da bridge subordinati o legami di interfacce fisiche o VLAN.  Su queste piattaforme, la scheda *SSM* > *Risorse* potrebbe mostrare l'indirizzo IP di rete Grid, Admin e Client assegnato ad altre interfacce oltre a eth0, eth1 o eth2.



== DHCP

È possibile configurare DHCP solo durante la fase di distribuzione.  Non è possibile impostare DHCP durante la configurazione.  Se si desidera modificare gli indirizzi IP, le maschere di sottorete e i gateway predefiniti per un nodo della griglia, è necessario utilizzare le procedure di modifica dell'indirizzo IP.  Utilizzando lo strumento Modifica IP, gli indirizzi DHCP diventeranno statici.



== Gruppi ad alta disponibilità (HA)

* Se un'interfaccia di rete client è contenuta in un gruppo HA, non è possibile modificare l'indirizzo IP di rete client per tale interfaccia in un indirizzo esterno alla subnet configurata per il gruppo HA.
* Non è possibile modificare l'indirizzo IP della rete client con il valore di un indirizzo IP virtuale esistente assegnato a un gruppo HA configurato sull'interfaccia della rete client.
* Se un'interfaccia di rete Grid è contenuta in un gruppo HA, non è possibile modificare l'indirizzo IP della rete Grid per tale interfaccia in un indirizzo esterno alla subnet configurata per il gruppo HA.
* Non è possibile modificare l'indirizzo IP di Grid Network con il valore di un indirizzo IP virtuale esistente assegnato a un gruppo HA configurato sull'interfaccia di Grid Network.

