---
permalink: maintain/gathering-required-materials-site-decom.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: Prima di smantellare un sito, è necessario procurarsi i seguenti materiali. 
---
= Raccogli i materiali richiesti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di smantellare un sito, è necessario procurarsi i seguenti materiali.

[cols="1a,2a"]
|===
| Articolo | Note 


 a| 
Pacchetto di recupero `.zip` file
 a| 
Devi scaricare il pacchetto di ripristino più recente `.zip` file(`sgws-recovery-package-id-revision.zip` ).  È possibile utilizzare il file Recovery Package per ripristinare il sistema in caso di errore.

link:downloading-recovery-package.html["Scarica il pacchetto di ripristino"]



 a| 
`Passwords.txt`file
 a| 
Questo file contiene le password necessarie per accedere ai nodi della griglia sulla riga di comando ed è incluso nel pacchetto di ripristino.



 a| 
Frase segreta di provisioning
 a| 
La passphrase viene creata e documentata quando il sistema StorageGRID viene installato per la prima volta.  La passphrase di provisioning non è presente nel `Passwords.txt` file.



 a| 
Descrizione della topologia del sistema StorageGRID prima della dismissione
 a| 
Se disponibile, procurarsi la documentazione che descrive la topologia attuale del sistema.

|===
.Informazioni correlate
link:../admin/web-browser-requirements.html["Requisiti del browser web"]
