---
permalink: maintain/linux-migrating-grid-node-to-new-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, migrate node, migrating node, new host for node 
summary: 'È possibile migrare uno o più nodi StorageGRID da un host Linux a un altro host Linux per eseguire la manutenzione dell"host senza compromettere la funzionalità o la disponibilità della griglia.' 
---
= Linux: Migrazione del nodo della griglia al nuovo host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile migrare uno o più nodi StorageGRID da un host Linux (l'_host di origine_) a un altro host Linux (l'_host di destinazione_) per eseguire la manutenzione dell'host senza compromettere la funzionalità o la disponibilità della griglia.

Ad esempio, potresti voler migrare un nodo per eseguire l'applicazione di patch al sistema operativo e il riavvio.

.Prima di iniziare
* Hai pianificato la distribuzione StorageGRID in modo da includere il supporto per la migrazione.
+
** link:../rhel/node-container-migration-requirements.html["Requisiti di migrazione dei container Node per Red Hat Enterprise Linux"]
** link:../ubuntu/node-container-migration-requirements.html["Requisiti di migrazione dei container Node per Ubuntu o Debian"]


* L'host di destinazione è già preparato per l'utilizzo StorageGRID .
* L'archiviazione condivisa viene utilizzata per tutti i volumi di archiviazione per nodo
* Le interfacce di rete hanno nomi coerenti tra gli host.


[NOTE]
====
In una distribuzione di produzione, non eseguire più di un nodo di archiviazione su un singolo host.  Utilizzando un host dedicato per ogni nodo di archiviazione si ottiene un dominio di errore isolato.

Altri tipi di nodi, come i nodi amministrativi o i nodi gateway, possono essere distribuiti sullo stesso host.  Tuttavia, se si dispone di più nodi dello stesso tipo (ad esempio due nodi gateway), non installare tutte le istanze sullo stesso host.

====


== Esporta nodo dall'host di origine

Come primo passo, arresta il nodo della griglia ed esportalo dall'host Linux di origine.

Eseguire i seguenti comandi sull'host sorgente.

.Passi
. Ottieni lo stato di tutti i nodi attualmente in esecuzione sull'host di origine.
+
`sudo storagegrid node status all`

+
Esempio di output:

+
[listing]
----
Name Config-State Run-State
DC1-ADM1 Configured Running
DC1-ARC1 Configured Running
DC1-GW1 Configured Running
DC1-S1 Configured Running
DC1-S2 Configured Running
DC1-S3 Configured Running
----
. Identificare il nome del nodo che si desidera migrare e arrestarlo se il suo stato di esecuzione è In esecuzione.
+
`sudo storagegrid node stop DC1-S3`

+
Esempio di output:

+
[listing]
----
Stopping node DC1-S3
Waiting up to 630 seconds for node shutdown
----
. Esportare il nodo dall'host di origine.
+
`sudo storagegrid node export DC1-S3`

+
Esempio di output:

+
[listing]
----
Finished exporting node DC1-S3 to /dev/mapper/sgws-dc1-s3-var-local.
Use 'storagegrid node import /dev/mapper/sgws-dc1-s3-var-local' if you
want to import it again.
----
. Prendi nota del `import` comando suggerito nell'output.
+
Nel passaggio successivo, eseguiremo questo comando sull'host di destinazione.





== Importa nodo sull'host di destinazione

Dopo aver esportato il nodo dall'host di origine, è necessario importare e convalidare il nodo sull'host di destinazione.  La convalida conferma che il nodo ha accesso agli stessi dispositivi di archiviazione a blocchi e di interfaccia di rete che aveva sull'host di origine.

Eseguire i seguenti comandi sull'host di destinazione.

.Passi
. Importare il nodo sull'host di destinazione.
+
`sudo storagegrid node import /dev/mapper/sgws-dc1-s3-var-local`

+
Esempio di output:

+
[listing]
----
Finished importing node DC1-S3 from /dev/mapper/sgws-dc1-s3-var-local.
You should run 'storagegrid node validate DC1-S3'
----
. Convalidare la configurazione del nodo sul nuovo host.
+
`sudo storagegrid node validate DC1-S3`

+
Esempio di output:

+
[listing]
----
Confirming existence of node DC1-S3... PASSED
Checking configuration file /etc/storagegrid/nodes/DC1-S3.conf for node DC1-S3... PASSED
Checking for duplication of unique values... PASSED
----
. Se si verificano errori di convalida, risolverli prima di avviare il nodo migrato.
+
Per informazioni sulla risoluzione dei problemi, consultare le istruzioni di installazione di StorageGRID per il sistema operativo Linux in uso.

+
** link:../rhel/index.html["Installa StorageGRID su Red Hat Enterprise Linux"]
** link:../ubuntu/index.html["Installa StorageGRID su Ubuntu o Debian"]






== Avvia il nodo migrato

Dopo aver convalidato il nodo migrato, è possibile avviarlo eseguendo un comando sull'host di destinazione.

.Passi
. Avviare il nodo sul nuovo host.
+
`sudo storagegrid node start DC1-S3`

. Sign in a Grid Manager e verifica che lo stato del nodo sia verde e senza avvisi.
+

CAUTION: La verifica che lo stato del nodo sia verde garantisce che il nodo migrato sia stato completamente riavviato e reinserito nella griglia.  Se lo stato non è verde, non migrare altri nodi in modo da non avere più di un nodo fuori servizio.

. Se non riesci ad accedere a Grid Manager, attendi 10 minuti, quindi esegui il seguente comando:
+
`sudo storagegrid node status _node-name`

+
Verificare che il nodo migrato abbia uno stato di esecuzione impostato su In esecuzione.


