---
permalink: maintain/modifying-dns-configuration-for-single-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, dns, modify dns 
summary: 'Invece di configurare il DNS globalmente per l"intera distribuzione, è possibile eseguire uno script per configurare il DNS in modo diverso per ciascun nodo della griglia.' 
---
= Modifica la configurazione DNS per un singolo nodo della griglia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Invece di configurare il DNS globalmente per l'intera distribuzione, è possibile eseguire uno script per configurare il DNS in modo diverso per ciascun nodo della griglia.

In generale, dovresti usare l'opzione *MANUTENZIONE* > *Rete* > *Server DNS* su Grid Manager per configurare i server DNS. Utilizzare lo script seguente solo se è necessario utilizzare server DNS diversi per nodi di griglia diversi.

.Passi
. Accedi al nodo di amministrazione principale:
+
.. Immettere il seguente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.
+
Quando si accede come root, il prompt cambia da `$` A `#` .

.. Aggiungere la chiave privata SSH all'agente SSH.  Inserisci: `ssh-add`
.. Immettere la password di accesso SSH elencata nel `Passwords.txt` file.


. [[log_in_to_node]]Accedi al nodo che desideri aggiornare con una configurazione DNS personalizzata: `ssh _node_IP_address_`
. Eseguire lo script di configurazione DNS: `setup_resolv.rb.`
+
Lo script risponde con l'elenco dei comandi supportati.

+
[listing]
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [`add search <domain>|remove search <domain>|add nameserver <ip>`]
              [`remove nameserver <ip>|remove nameserver all|save|abort|help`]
----
. Aggiungi l'indirizzo IPv4 di un server che fornisce il servizio di nomi di dominio per la tua rete: `add <nameserver IP_address>`
. Ripeti il `add nameserver` comando per aggiungere server dei nomi.
. Seguire le istruzioni richieste per gli altri comandi.
. Salva le modifiche e esci dall'applicazione: `save`
. [[close_cmd_shell]]Chiudere la shell dei comandi sul server: `exit`
. Per ogni nodo della griglia, ripetere i passaggi da<<log_in_to_node,accesso al nodo>> Attraverso<<close_cmd_shell,chiusura della shell dei comandi>> .
. Quando non è più necessario l'accesso senza password ad altri server, rimuovere la chiave privata dall'agente SSH.  Inserisci: `ssh-add -D`

