---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: 'Quando si ripristina un nodo della griglia ospitato su un"appliance di servizi, è necessario innanzitutto preparare l"appliance per la reinstallazione del software StorageGRID .' 
---
= Preparare l'apparecchio per la reinstallazione (solo sostituzione della piattaforma)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si ripristina un nodo della griglia ospitato su un'appliance di servizi, è necessario innanzitutto preparare l'appliance per la reinstallazione del software StorageGRID .

Eseguire questa procedura solo se si sta sostituendo un nodo non riuscito ospitato su un'appliance di servizi.  Non seguire questi passaggi se il nodo non riuscito era originariamente ospitato su VMware o su un host Linux.

.Passi
. Accedi al nodo della griglia non riuscito:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.


+
Quando si accede come root, il prompt cambia da `$` A `#` .

. Preparare l'appliance per l'installazione del software StorageGRID .  Inserisci: `sgareinstall`
. Quando ti viene chiesto di continuare, inserisci: `y`
+
L'appliance si riavvia e la sessione SSH termina.  In genere occorrono circa 5 minuti prima che StorageGRID Appliance Installer diventi disponibile, anche se in alcuni casi potrebbe essere necessario attendere fino a 30 minuti.

+
L'appliance dei servizi viene reimpostata e i dati sul nodo della griglia non sono più accessibili.  Gli indirizzi IP configurati durante il processo di installazione originale dovrebbero rimanere intatti; tuttavia, si consiglia di confermarlo al termine della procedura.

+
Dopo aver eseguito il `sgareinstall` comando, tutti gli account, le password e le chiavi SSH forniti StorageGRID vengono rimossi e vengono generate nuove chiavi host.


