---
permalink: maintain/rebooting-grid-node-from-command-shell.html 
sidebar: sidebar 
keywords: storagegrid, recover, reboot node, command shell reboot 
summary: 'Se è necessario monitorare più attentamente l"operazione di riavvio o se non è possibile accedere a Grid Manager, è possibile accedere al nodo della griglia ed eseguire il comando di riavvio di Server Manager dalla shell dei comandi.' 
---
= Riavviare il nodo della griglia dalla shell dei comandi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è necessario monitorare più attentamente l'operazione di riavvio o se non è possibile accedere a Grid Manager, è possibile accedere al nodo della griglia ed eseguire il comando di riavvio di Server Manager dalla shell dei comandi.

.Prima di iniziare
Tu hai il `Passwords.txt` file.

.Passi
. Accedi al nodo della griglia:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.


+
Quando si accede come root, il prompt cambia da `$` A `#` .

. Facoltativamente, interrompere i servizi: `service servermanager stop`
+
L'interruzione dei servizi è un passaggio facoltativo, ma consigliato.  L'arresto dei servizi può richiedere fino a 15 minuti; potrebbe essere opportuno accedere al sistema da remoto per monitorare il processo di arresto prima di riavviare il nodo nel passaggio successivo.

. Riavviare il nodo della griglia: `reboot`
. Disconnettersi dalla shell dei comandi: `exit`

