---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: 'È necessario completare una serie di attività per ripristinare un nodo di archiviazione basato su software in cui uno o più volumi di archiviazione sul nodo di archiviazione sono guasti, ma l"unità di sistema è intatta.  Se solo i volumi di archiviazione sono guasti, il nodo di archiviazione è ancora disponibile per il sistema StorageGRID .' 
---
= Ripristinare da un errore del volume di archiviazione in cui l'unità di sistema è intatta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario completare una serie di attività per ripristinare un nodo di archiviazione basato su software in cui uno o più volumi di archiviazione sul nodo di archiviazione sono guasti, ma l'unità di sistema è intatta.  Se solo i volumi di archiviazione sono guasti, il nodo di archiviazione è ancora disponibile per il sistema StorageGRID .


NOTE: Questa procedura di ripristino si applica solo ai nodi di archiviazione basati su software.  Se i volumi di archiviazione si sono guastati su un nodo di archiviazione dell'appliance, utilizzare invece la procedura dell'appliance:link:recovering-storagegrid-appliance-storage-node.html["Ripristina il nodo di archiviazione dell'appliance"] .

Questa procedura di recupero comprende le seguenti attività:

* link:reviewing-warnings-about-storage-volume-recovery.html["Rivedere gli avvisi per il ripristino del volume di archiviazione"]
* link:identifying-and-unmounting-failed-storage-volumes.html["Identificare e smontare i volumi di archiviazione non riusciti"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Recupera i volumi e ricostruisci il database Cassandra"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Ripristina i dati dell'oggetto"]
* link:checking-storage-state-after-recovering-storage-volumes.html["Controllare lo stato di archiviazione"]

