---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: recover, storage node failure, Reaper 
summary: La procedura per il ripristino di un nodo di archiviazione non riuscito dipende dal tipo di errore e dal tipo di nodo di archiviazione che ha subito il guasto. 
---
= Ripristino da guasti del nodo di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procedura per il ripristino di un nodo di archiviazione non riuscito dipende dal tipo di errore e dal tipo di nodo di archiviazione che ha subito il guasto.

Utilizzare questa tabella per selezionare la procedura di ripristino per un nodo di archiviazione non riuscito.

[cols="1a,1a,1a"]
|===
| Problema | Azione | Note 


 a| 
* Più di un nodo di archiviazione è guasto.
* Un secondo nodo di archiviazione ha subito un guasto meno di 15 giorni dopo un guasto o un ripristino del nodo di archiviazione.
+
Ciò include il caso in cui un nodo di archiviazione si guasta mentre è ancora in corso il ripristino di un altro nodo di archiviazione.


 a| 
Contattare l'assistenza tecnica.
 a| 
Il ripristino di più di un nodo di archiviazione (o di più di un nodo di archiviazione nell'arco di 15 giorni) potrebbe compromettere l'integrità del database Cassandra, causando la perdita di dati.

Il supporto tecnico può stabilire quando è sicuro iniziare il ripristino di un secondo nodo di archiviazione.

*Nota*: se più di un nodo di archiviazione contenente il servizio ADC si guasta in un sito, si perdono tutte le richieste di servizio della piattaforma in sospeso per quel sito.



 a| 
Si è verificato un errore in più di un nodo di archiviazione in un sito oppure in un intero sito.
 a| 
Contattare l'assistenza tecnica. Potrebbe essere necessario eseguire una procedura di ripristino del sito.
 a| 
Il supporto tecnico valuterà la tua situazione e svilupperà un piano di ripristino. Vedere link:how-site-recovery-is-performed-by-technical-support.html["Come il supporto tecnico recupera un sito"] .



 a| 
Si è verificato un errore nel nodo di archiviazione di un'appliance.
 a| 
link:recovering-storagegrid-appliance-storage-node.html["Ripristina il nodo di archiviazione dell'appliance"]
 a| 
La procedura di ripristino per i nodi di archiviazione dell'appliance è la stessa per tutti i guasti.



 a| 
Uno o più volumi di archiviazione sono guasti, ma l'unità di sistema è intatta
 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["Ripristinare da un errore del volume di archiviazione in cui l'unità di sistema è intatta"]
 a| 
Questa procedura viene utilizzata per i nodi di archiviazione basati su software.



 a| 
L'unità di sistema è guasta.
 a| 
link:reviewing-warnings-for-system-drive-recovery.html["Ripristino da un errore dell'unità di sistema"]
 a| 
La procedura di sostituzione del nodo dipende dalla piattaforma di distribuzione e dal fatto che anche altri volumi di archiviazione siano guasti.

|===

NOTE: Alcune procedure di ripristino StorageGRID utilizzano Reaper per gestire le riparazioni di Cassandra.  Le riparazioni vengono eseguite automaticamente non appena vengono avviati i servizi correlati o richiesti.  Potresti notare che nell'output dello script viene menzionato "reaper" o "Cassandra repair".  Se viene visualizzato un messaggio di errore che indica che la riparazione non è riuscita, eseguire il comando indicato nel messaggio di errore.
