---
permalink: maintain/replacing-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace primary admin node, replacing primary admin node, primary admin node 
summary: 'Per ripristinare un nodo amministrativo primario, è necessario prima sostituire l"hardware fisico o virtuale.' 
---
= Sostituisci il nodo di amministrazione primario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ripristinare un nodo amministrativo primario, è necessario prima sostituire l'hardware fisico o virtuale.

È possibile sostituire un nodo amministrativo primario non riuscito con un nodo amministrativo primario in esecuzione sulla stessa piattaforma oppure è possibile sostituire un nodo amministrativo primario in esecuzione su VMware o un host Linux con un nodo amministrativo primario ospitato su un'appliance di servizi.

Utilizzare la procedura corrispondente alla piattaforma sostitutiva selezionata per il nodo.  Dopo aver completato la procedura di sostituzione del nodo (adatta a tutti i tipi di nodo), la procedura indirizzerà al passaggio successivo per il ripristino del nodo di amministrazione primario.

[cols="1a,2a"]
|===
| Piattaforma sostitutiva | Procedura 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Sostituisci un nodo VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Sostituisci un nodo Linux"]



 a| 
Servizi elettrodomestici
 a| 
link:replacing-failed-node-with-services-appliance.html["Sostituire un apparecchio di servizio"]



 a| 
OpenStack
 a| 
I file del disco della macchina virtuale e gli script forniti da NetApp per OpenStack non sono più supportati per le operazioni di ripristino.  Se devi ripristinare un nodo in esecuzione in una distribuzione OpenStack, scarica i file per il tuo sistema operativo Linux.  Quindi, seguire la procedura perlink:all-node-types-replacing-linux-node.html["sostituzione di un nodo Linux"] .

|===