---
permalink: maintain/replacing-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace storage node, replacing storage node 
summary: 'Se l"unità di sistema è guasta, è necessario prima sostituire il nodo di archiviazione.' 
---
= Sostituisci il nodo di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'unità di sistema è guasta, è necessario prima sostituire il nodo di archiviazione.

È necessario selezionare la procedura di sostituzione dei nodi per la propria piattaforma.  I passaggi per sostituire un nodo sono gli stessi per tutti i tipi di nodi della griglia.


NOTE: Questa procedura si applica solo ai nodi di archiviazione basati su software.  È necessario seguire una procedura diversa perlink:recovering-storagegrid-appliance-storage-node.html["ripristinare un nodo di archiviazione dell'appliance"] .

*Linux:* Se non sei sicuro che l'unità di sistema sia guasta, segui le istruzioni per sostituire il nodo e determinare quali passaggi di ripristino sono necessari.

[cols="1a,2a"]
|===
| Piattaforma | Procedura 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Sostituisci un nodo VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Sostituisci un nodo Linux"]



 a| 
OpenStack
 a| 
I file del disco della macchina virtuale e gli script forniti da NetApp per OpenStack non sono più supportati per le operazioni di ripristino.  Se devi ripristinare un nodo in esecuzione in una distribuzione OpenStack, scarica i file per il tuo sistema operativo Linux.  Quindi, seguire la procedura perlink:all-node-types-replacing-linux-node.html["sostituzione di un nodo Linux"] .

|===