---
permalink: maintain/replacing-gateway-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace gateway node, replacing gateway node 
summary: 'È possibile sostituire un Gateway Node non riuscito con un Gateway Node in esecuzione sullo stesso hardware fisico o virtuale, oppure è possibile sostituire un Gateway Node in esecuzione su VMware o un host Linux con un Gateway Node ospitato su un"appliance di servizi.' 
---
= Sostituisci nodo gateway
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire un Gateway Node non riuscito con un Gateway Node in esecuzione sullo stesso hardware fisico o virtuale, oppure è possibile sostituire un Gateway Node in esecuzione su VMware o un host Linux con un Gateway Node ospitato su un'appliance di servizi.

La procedura di sostituzione del nodo da seguire dipende dalla piattaforma che verrà utilizzata dal nodo sostitutivo.  Dopo aver completato la procedura di sostituzione del nodo (adatta a tutti i tipi di nodo), la procedura indirizzerà al passaggio successivo per il ripristino del nodo gateway.

[cols="1a,2a"]
|===
| Piattaforma sostitutiva | Procedura 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Sostituisci un nodo VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Sostituisci un nodo Linux"]



 a| 
Servizi elettrodomestici
 a| 
link:replacing-failed-node-with-services-appliance.html["Sostituire un apparecchio di servizio"]



 a| 
OpenStack
 a| 
I file del disco della macchina virtuale e gli script forniti da NetApp per OpenStack non sono più supportati per le operazioni di ripristino.  Se devi ripristinare un nodo in esecuzione in una distribuzione OpenStack, scarica i file per il tuo sistema operativo Linux.  Quindi, seguire la procedura perlink:all-node-types-replacing-linux-node.html["sostituzione di un nodo Linux"] .

|===