---
permalink: maintain/restarting-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, restart server manager 
summary: Potrebbe essere necessario riavviare il gestore del server e tutti i servizi in esecuzione su un nodo della griglia. 
---
= Riavviare Server Manager e tutti i servizi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario riavviare il gestore del server e tutti i servizi in esecuzione su un nodo della griglia.

.Prima di iniziare
Tu hai il `Passwords.txt` file.

.Passi
. Accedi al nodo della griglia:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.


+
Quando si accede come root, il prompt cambia da `$` A `#` .

. Riavviare Server Manager e tutti i servizi sul nodo della griglia: `service servermanager restart`
+
Server Manager e tutti i servizi sul nodo della griglia vengono arrestati e quindi riavviati.

+

NOTE: Utilizzando il `restart` il comando è lo stesso dell'utilizzo del `stop` comando seguito dal `start` comando.

. Disconnettersi dalla shell dei comandi: `exit`

