---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: Se si desidera conservare le informazioni cronologiche sugli attributi e sugli avvisi su un nodo di amministrazione non primario che ha subito un errore, è possibile ripristinare il database del nodo di amministrazione dal nodo di amministrazione primario. 
---
= Ripristina il database del nodo amministrativo durante il ripristino del nodo amministrativo non primario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera conservare le informazioni cronologiche sugli attributi e sugli avvisi su un nodo di amministrazione non primario che ha subito un errore, è possibile ripristinare il database del nodo di amministrazione dal nodo di amministrazione primario.

.Prima di iniziare
* Il nodo amministrativo recuperato è installato e funzionante.
* Il sistema StorageGRID include almeno due nodi amministrativi.
* Tu hai il `Passwords.txt` file.
* Hai la passphrase di provisioning.


.Informazioni su questo compito
Se un nodo di amministrazione si guasta, le informazioni storiche memorizzate nel suo database vanno perse.  Questo database include le seguenti informazioni:

* Cronologia degli avvisi
* Dati degli attributi storici, utilizzati nei grafici in stile legacy nella pagina Nodi


Quando si ripristina un nodo di amministrazione, il processo di installazione del software crea un database del nodo di amministrazione vuoto sul nodo ripristinato.  Tuttavia, il nuovo database include solo informazioni sui server e sui servizi che fanno attualmente parte del sistema o che saranno aggiunti in seguito.

Se hai ripristinato un nodo amministrativo non primario, puoi ripristinare le informazioni cronologiche copiando il database del nodo amministrativo dal nodo amministrativo primario (il _nodo amministrativo di origine_) al nodo ripristinato.


NOTE: La copia del database del nodo di amministrazione potrebbe richiedere diverse ore.  Alcune funzionalità di Grid Manager non saranno disponibili mentre i servizi sono interrotti sul nodo sorgente.

.Passi
. Accedi al nodo di amministrazione di origine:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.


. Eseguire il seguente comando dal nodo di amministrazione di origine.  Quindi, se richiesto, immettere la passphrase di provisioning. `recover-access-points`
. Dal nodo di amministrazione di origine, arrestare il servizio MI: `service mi stop`
. Dal nodo di amministrazione di origine, arrestare il servizio Management Application Program Interface (mgmt-api): `service mgmt-api stop`
. Completare i seguenti passaggi sul nodo di amministrazione recuperato:
+
.. Accedi al nodo di amministrazione recuperato:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Inserisci la password elencata nel `Passwords.txt` file.
... Immettere il seguente comando per passare alla root: `su -`
... Inserisci la password elencata nel `Passwords.txt` file.


.. Arrestare il servizio MI: `service mi stop`
.. Arrestare il servizio mgmt-api: `service mgmt-api stop`
.. Aggiungere la chiave privata SSH all'agente SSH.  Inserisci:``ssh-add``
.. Immettere la password di accesso SSH elencata nel `Passwords.txt` file.
.. Copiare il database dal nodo amministrativo di origine al nodo amministrativo recuperato: `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. Quando richiesto, confermare che si desidera sovrascrivere il database MI sul nodo di amministrazione recuperato.
+
Il database e i suoi dati storici vengono copiati nel nodo di amministrazione recuperato.  Una volta completata l'operazione di copia, lo script avvia il nodo di amministrazione recuperato.

.. Quando non è più necessario l'accesso senza password ad altri server, rimuovere la chiave privata dall'agente SSH.  Inserisci:``ssh-add -D``


. Riavviare i servizi sul nodo di amministrazione di origine: `service servermanager start`

