---
permalink: maintain/restoring-prometheus-metrics-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore metrics, restore prometheus, primary admin node 
summary: Facoltativamente, è possibile conservare le metriche storiche gestite da Prometheus su un nodo di amministrazione primario che ha subito un errore.  Le metriche Prometheus possono essere ripristinate solo se il sistema StorageGRID include un altro nodo di amministrazione. 
---
= Ripristina le metriche di Prometheus durante il ripristino del nodo di amministrazione primario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Facoltativamente, è possibile conservare le metriche storiche gestite da Prometheus su un nodo di amministrazione primario che ha subito un errore.  Le metriche Prometheus possono essere ripristinate solo se il sistema StorageGRID include un altro nodo di amministrazione.

.Prima di iniziare
* Il nodo amministrativo recuperato è installato e funzionante.
* Il sistema StorageGRID include almeno due nodi amministrativi.
* Tu hai il `Passwords.txt` file.
* Hai la passphrase di provisioning.


.Informazioni su questo compito
Se un nodo di amministrazione fallisce, le metriche mantenute nel database Prometheus sul nodo di amministrazione vanno perse.  Quando si ripristina il nodo di amministrazione, il processo di installazione del software crea un nuovo database Prometheus.  Dopo l'avvio del nodo amministrativo ripristinato, le metriche vengono registrate come se fosse stata eseguita una nuova installazione del sistema StorageGRID .

Se hai ripristinato un nodo amministrativo primario e il tuo sistema StorageGRID ha un altro nodo amministrativo, puoi ripristinare le metriche storiche copiando il database Prometheus da un nodo amministrativo non primario (il _nodo amministrativo di origine_) al nodo amministrativo primario ripristinato.  Se il sistema ha solo un nodo di amministrazione primario, non è possibile ripristinare il database Prometheus.


NOTE: La copia del database Prometheus potrebbe richiedere un'ora o più.  Alcune funzionalità di Grid Manager non saranno disponibili mentre i servizi sono interrotti sul nodo di amministrazione di origine.

.Passi
. Accedi al nodo di amministrazione di origine:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.


. Dal nodo di amministrazione di origine, arrestare il servizio Prometheus: `service prometheus stop`
. Completare i seguenti passaggi sul nodo di amministrazione recuperato:
+
.. Accedi al nodo di amministrazione recuperato:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Inserisci la password elencata nel `Passwords.txt` file.
... Immettere il seguente comando per passare alla root: `su -`
... Inserisci la password elencata nel `Passwords.txt` file.


.. Interrompere il servizio Prometheus: `service prometheus stop`
.. Aggiungere la chiave privata SSH all'agente SSH.  Inserisci:``ssh-add``
.. Immettere la password di accesso SSH elencata nel `Passwords.txt` file.
.. Copiare il database Prometheus dal nodo amministrativo di origine al nodo amministrativo recuperato: `/usr/local/prometheus/bin/prometheus-clone-db.sh Source_Admin_Node_IP`
.. Quando richiesto, premere *Invio* per confermare che si desidera eliminare il nuovo database Prometheus sul nodo di amministrazione recuperato.
+
Il database Prometheus originale e i suoi dati storici vengono copiati nel nodo di amministrazione recuperato.  Una volta completata l'operazione di copia, lo script avvia il nodo di amministrazione recuperato.  Viene visualizzato il seguente stato:

+
Database clonato, avvio dei servizi

.. Quando non è più necessario l'accesso senza password ad altri server, rimuovere la chiave privata dall'agente SSH.  Inserisci:``ssh-add -D``


. Riavviare il servizio Prometheus sul nodo di amministrazione di origine.`service prometheus start`

