---
permalink: maintain/viewing-server-manager-status-and-version.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, status, version 
summary: Per ogni nodo della griglia è possibile visualizzare lo stato corrente e la versione di Server Manager in esecuzione su quel nodo della griglia.  È anche possibile ottenere lo stato attuale di tutti i servizi in esecuzione su quel nodo della griglia. 
---
= Visualizza lo stato e la versione di Server Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ogni nodo della griglia è possibile visualizzare lo stato corrente e la versione di Server Manager in esecuzione su quel nodo della griglia.  È anche possibile ottenere lo stato attuale di tutti i servizi in esecuzione su quel nodo della griglia.

.Prima di iniziare
Tu hai il `Passwords.txt` file.

.Passi
. Accedi al nodo della griglia:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.


+
Quando si accede come root, il prompt cambia da `$` A `#` .

. Visualizza lo stato corrente di Server Manager in esecuzione sul nodo della griglia: `*service servermanager status*`
+
Viene segnalato lo stato corrente di Server Manager in esecuzione sul nodo della griglia (in esecuzione o meno).  Se lo stato di Server Manager è `running` , viene indicato il tempo trascorso dall'ultimo avvio. Per esempio:

+
[listing]
----
servermanager running for 1d, 13h, 0m, 30s
----
. Visualizza la versione corrente di Server Manager in esecuzione su un nodo della griglia: `*service servermanager version*`
+
È elencata la versione attuale. Per esempio:

+
[listing]
----
11.1.0-20180425.1905.39c9493
----
. Disconnettersi dalla shell dei comandi: `*exit*`

