---
permalink: maintain/viewing-current-status-of-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, status 
summary: È possibile visualizzare in qualsiasi momento lo stato corrente di un servizio in esecuzione su un nodo della griglia. 
---
= Visualizza lo stato attuale del servizio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare in qualsiasi momento lo stato corrente di un servizio in esecuzione su un nodo della griglia.

.Prima di iniziare
Tu hai il `Passwords.txt` file.

.Passi
. Accedi al nodo della griglia:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Inserisci la password elencata nel `Passwords.txt` file.
.. Immettere il seguente comando per passare alla root: `su -`
.. Inserisci la password elencata nel `Passwords.txt` file.


+
Quando si accede come root, il prompt cambia da `$` A `#` .

. Visualizza lo stato corrente di un servizio in esecuzione su un nodo della griglia: `*service _servicename_ status* Viene segnalato lo stato corrente del servizio richiesto in esecuzione sul nodo della griglia (in esecuzione o meno). Per esempio:
+
[listing]
----
cmn running for 1d, 14h, 21m, 2s
----
. Disconnettersi dalla shell dei comandi: `*exit*`

