---
permalink: maintain/whats-next-performing-additional-recovery-steps-if-required.html 
sidebar: sidebar 
keywords: storagegrid, recover, corrective action, additional recovery 
summary: 'A seconda delle azioni specifiche intraprese per far funzionare i nodi StorageGRID sull"host sostitutivo, potrebbe essere necessario eseguire ulteriori passaggi di ripristino per ciascun nodo.' 
---
= Prossimi passi: eseguire ulteriori passaggi di ripristino, se necessario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seconda delle azioni specifiche intraprese per far funzionare i nodi StorageGRID sull'host sostitutivo, potrebbe essere necessario eseguire ulteriori passaggi di ripristino per ciascun nodo.

Il ripristino del nodo è completo se non è stato necessario intraprendere alcuna azione correttiva durante la sostituzione dell'host Linux o il ripristino del nodo grid non riuscito sul nuovo host.



== Azioni correttive e prossimi passi

Durante la sostituzione del nodo, potrebbe essere stato necessario adottare una delle seguenti misure correttive:

* Dovevi usare il `--force` flag per importare il nodo.
* Per qualsiasi `<PURPOSE>` , il valore del `BLOCK_DEVICE_<PURPOSE>` La variabile del file di configurazione si riferisce a un dispositivo a blocchi che non contiene gli stessi dati che conteneva prima del guasto dell'host.
* Hai emesso `storagegrid node force-recovery _node-name_` per il nodo.
* Hai aggiunto un nuovo dispositivo a blocchi.


Se hai adottato *una* di queste azioni correttive, devi eseguire ulteriori passaggi di ripristino.

[cols="2a,1a"]
|===
| Tipo di recupero | Passo successivo 


 a| 
Nodo di amministrazione primario
 a| 
link:configuring-replacement-primary-admin-node.html["Configura il nodo di amministrazione primario sostitutivo"]



 a| 
Nodo amministratore non primario
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Selezionare Avvia ripristino per configurare il nodo di amministrazione non primario"]



 a| 
Nodo Gateway
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["Selezionare Avvia ripristino per configurare il nodo gateway"]



 a| 
Nodo di archiviazione (basato su software):

* Se dovessi usare il `--force` flag per importare il nodo, oppure hai emesso `storagegrid node force-recovery _node-name_`
* Se hai dovuto eseguire una reinstallazione completa del nodo o hai dovuto ripristinare /var/local

 a| 
link:selecting-start-recovery-to-configure-storage-node.html["Selezionare Avvia ripristino per configurare il nodo di archiviazione"]



 a| 
Nodo di archiviazione (basato su software):

* Se hai aggiunto un nuovo dispositivo a blocchi.
* Se, per qualsiasi `<PURPOSE>` , il valore del `BLOCK_DEVICE_<PURPOSE>` La variabile del file di configurazione si riferisce a un dispositivo a blocchi che non contiene gli stessi dati che conteneva prima del guasto dell'host.

 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["Ripristinare da un errore del volume di archiviazione in cui l'unità di sistema è intatta"]

|===