---
permalink: primer/hybrid-clouds-with-storagegrid.html 
sidebar: sidebar 
keywords: hybrid cloud, cloud storage pool, platform services, fabricpool, ontap 
summary: Utilizza StorageGRID in una configurazione cloud ibrida implementando la gestione dei dati basata su policy per archiviare oggetti in Cloud Storage Pool, sfruttando i servizi della piattaforma StorageGRID e suddividendo i dati da ONTAP a StorageGRID con NetApp FabricPool. 
---
= Cloud ibridi con StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizza StorageGRID in una configurazione cloud ibrida implementando la gestione dei dati basata su policy per archiviare oggetti in Cloud Storage Pool, sfruttando i servizi della piattaforma StorageGRID e suddividendo i dati da ONTAP a StorageGRID con NetApp FabricPool.



== Pool di archiviazione cloud

I pool di archiviazione cloud consentono di archiviare oggetti al di fuori del sistema StorageGRID .  Ad esempio, potresti voler spostare gli oggetti a cui si accede raramente su un archivio cloud più economico, come Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud o il livello di accesso Archive nell'archivio BLOB di Microsoft Azure.  In alternativa, potresti voler mantenere un backup cloud degli oggetti StorageGRID , che può essere utilizzato per recuperare i dati persi a causa di un errore del volume di archiviazione o del nodo di archiviazione.

È supportato anche lo storage di partner terzi, inclusi storage su disco e nastro.


NOTE: L'utilizzo di Cloud Storage Pool con FabricPool non è supportato a causa della latenza aggiuntiva necessaria per recuperare un oggetto dalla destinazione di Cloud Storage Pool.



== Servizi della piattaforma S3

I servizi della piattaforma S3 offrono la possibilità di utilizzare servizi remoti come endpoint per la replicazione di oggetti, le notifiche di eventi o l'integrazione della ricerca.  I servizi della piattaforma operano indipendentemente dalle regole ILM della griglia e sono abilitati per singoli bucket S3.  Sono supportati i seguenti servizi:

* Il servizio di replica CloudMirror esegue automaticamente il mirroring degli oggetti specificati su un bucket S3 di destinazione, che può trovarsi su Amazon S3 o su un secondo sistema StorageGRID .
* Il servizio di notifica eventi invia messaggi sulle azioni specificate a un endpoint esterno che supporta la ricezione di eventi Simple Notification Service (Amazon SNS).
* Il servizio di integrazione della ricerca invia i metadati degli oggetti a un servizio Elasticsearch esterno, consentendo la ricerca, la visualizzazione e l'analisi dei metadati tramite strumenti di terze parti.


Ad esempio, potresti utilizzare la replica di CloudMirror per eseguire il mirroring di record specifici dei clienti in Amazon S3 e quindi sfruttare i servizi AWS per eseguire analisi sui tuoi dati.



== Livelli di dati ONTAP tramite FabricPool

È possibile ridurre i costi di archiviazione ONTAP suddividendo i dati in livelli su StorageGRID tramite FabricPool.  FabricPool consente il tiering automatico dei dati su livelli di archiviazione di oggetti a basso costo, sia in sede che fuori sede.

A differenza delle soluzioni di suddivisione in livelli manuale, FabricPool riduce il costo totale di proprietà automatizzando la suddivisione in livelli dei dati per abbassare i costi di archiviazione. Offre i vantaggi dell'economia del cloud tramite la suddivisione in livelli tra cloud pubblici e privati, tra cui StorageGRID.

.Informazioni correlate
* link:../ilm/what-cloud-storage-pool-is.html["Che cos'è Cloud Storage Pool?"]
* link:../tenant/what-platform-services-are.html["Gestire i servizi della piattaforma"]
* link:../fabricpool/index.html["Configurare StorageGRID per FabricPool"]

