---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: I nodi di archiviazione gestiscono e archiviano dati e metadati degli oggetti.  I nodi di archiviazione includono i servizi e i processi necessari per archiviare, spostare, verificare e recuperare dati e metadati degli oggetti su disco. 
---
= Che cos'è un nodo di archiviazione?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I nodi di archiviazione gestiscono e archiviano dati e metadati degli oggetti.  I nodi di archiviazione includono i servizi e i processi necessari per archiviare, spostare, verificare e recuperare dati e metadati degli oggetti su disco.

Ogni sito nel sistema StorageGRID deve avere almeno tre nodi di archiviazione.



== Tipi di nodi di archiviazione

Durante l'installazione, è possibile selezionare il tipo di nodo di archiviazione che si desidera installare.  Questi tipi sono disponibili per i nodi di archiviazione basati su software e per i nodi di archiviazione basati su appliance che supportano la funzionalità:

* Nodo di archiviazione di dati e metadati combinati
* Nodo di archiviazione solo metadati
* Nodo di archiviazione solo dati


È possibile selezionare il tipo di nodo di archiviazione nelle seguenti situazioni:

* Quando si installa inizialmente un nodo di archiviazione
* Quando si aggiunge un nodo di archiviazione durante l'espansione del sistema StorageGRID



NOTE: Non è possibile modificare il tipo una volta completata l'installazione del nodo di archiviazione.

Nodo di archiviazione dati e metadati (combinato):: Per impostazione predefinita, tutti i nuovi nodi di archiviazione memorizzeranno sia i dati degli oggetti che i metadati.  Questo tipo di nodo di archiviazione è chiamato nodo di archiviazione _combinato_.
Nodo di archiviazione solo metadati:: Utilizzare un nodo di archiviazione esclusivamente per i metadati può avere senso se la griglia memorizza un numero molto elevato di piccoli oggetti.  L'installazione di una capacità dedicata per i metadati garantisce un migliore equilibrio tra lo spazio necessario per un numero molto elevato di piccoli oggetti e lo spazio necessario per i metadati di tali oggetti.  Inoltre, i nodi di archiviazione basati solo su metadati ospitati su appliance ad alte prestazioni possono aumentare le prestazioni.


I nodi di archiviazione solo metadati hanno requisiti hardware specifici:

* Quando si utilizzano appliance StorageGRID , i nodi solo metadati possono essere configurati solo su appliance SGF6112 con dodici unità da 1,9 TB o dodici unità da 3,8 TB.
* Quando si utilizzano nodi basati su software, le risorse dei nodi solo metadati devono corrispondere alle risorse dei nodi di archiviazione esistenti. Per esempio:
+
** Se il sito StorageGRID esistente utilizza appliance SG6000 o SG6100, i nodi basati solo su software devono soddisfare i seguenti requisiti minimi:
+
*** 128 GB di RAM
*** CPU a 8 core
*** SSD da 8 TB o spazio di archiviazione equivalente per il database Cassandra (rangedb/0)


** Se il sito StorageGRID esistente utilizza nodi di archiviazione virtuali con 24 GB di RAM, CPU a 8 core e 3 TB o 4 TB di spazio di archiviazione dei metadati, i nodi basati solo su software devono utilizzare risorse simili (24 GB di RAM, CPU a 8 core e 4 TB di spazio di archiviazione dei metadati (rangedb/0).


* Quando si aggiunge un nuovo sito StorageGRID , la capacità totale dei metadati del nuovo sito deve corrispondere almeno ai siti StorageGRID esistenti e le risorse del nuovo sito devono corrispondere ai nodi di archiviazione nei siti StorageGRID esistenti.


Quando si installano nodi solo metadati, la griglia deve contenere anche un numero minimo di nodi per l'archiviazione dei dati:

* Per una griglia a sito singolo, configurare almeno due nodi di archiviazione combinati o solo dati.
* Per una griglia multi-sito, configurare almeno un nodo di archiviazione combinato o solo dati _per sito_.



NOTE: Sebbene i nodi di archiviazione solo metadati contengano<<ldr-service,Servizio LDR>> e può elaborare le richieste del client S3, le prestazioni StorageGRID potrebbero non aumentare.

Nodo di archiviazione solo dati:: Utilizzare un nodo di archiviazione esclusivamente per i dati può avere senso se i nodi di archiviazione hanno caratteristiche prestazionali diverse.  Ad esempio, per aumentare potenzialmente le prestazioni, è possibile disporre di nodi di archiviazione con dischi rotanti ad alta capacità e solo dati, accompagnati da nodi di archiviazione ad alte prestazioni solo metadati.


Quando si installano nodi solo dati, la griglia deve contenere quanto segue:

* Un minimo di due nodi di archiviazione combinati o solo dati _per griglia_
* Almeno un nodo di archiviazione combinato o solo dati _per sito_
* Un minimo di tre nodi di archiviazione combinati o solo metadati _per sito_




== Servizi primari per i nodi di archiviazione

Nella tabella seguente sono riportati i servizi principali per i nodi di archiviazione; tuttavia, questa tabella non elenca tutti i servizi dei nodi.


NOTE: Alcuni servizi, come il servizio ADC e il servizio RSM, in genere sono presenti solo su tre nodi di archiviazione in ogni sito.

[cols="1a,3a"]
|===
| Servizio | Funzione chiave 


 a| 
Conto (account)
 a| 
Gestisce i conti degli inquilini.



 a| 
Controller di dominio amministrativo (ADC)
 a| 
Mantiene la topologia e la configurazione dell'intera griglia.

*Nota*: i nodi di archiviazione solo dati non ospitano il servizio ADC.

.Dettagli
[%collapsible]
====
Il servizio Administrative Domain Controller (ADC) autentica i nodi della griglia e le loro connessioni reciproche.  Il servizio ADC è ospitato su un minimo di tre nodi di archiviazione in un sito.

Il servizio ADC gestisce le informazioni sulla topologia, tra cui la posizione e la disponibilità dei servizi.  Quando un nodo della griglia richiede informazioni da un altro nodo della griglia o un'azione da eseguire da un altro nodo della griglia, contatta un servizio ADC per trovare il nodo della griglia migliore per elaborare la sua richiesta.  Inoltre, il servizio ADC conserva una copia dei bundle di configurazione della distribuzione StorageGRID , consentendo a qualsiasi nodo della griglia di recuperare le informazioni di configurazione correnti.

Per facilitare le operazioni distribuite e in isola, ogni servizio ADC sincronizza certificati, bundle di configurazione e informazioni sui servizi e sulla topologia con gli altri servizi ADC nel sistema StorageGRID .

In generale, tutti i nodi della griglia mantengono una connessione ad almeno un servizio ADC.  Ciò garantisce che i nodi della griglia accedano sempre alle informazioni più recenti.  Quando i nodi della griglia si connettono, memorizzano nella cache i certificati degli altri nodi della griglia, consentendo ai sistemi di continuare a funzionare con i nodi della griglia noti anche quando un servizio ADC non è disponibile.  I nuovi nodi della griglia possono stabilire connessioni solo tramite un servizio ADC.

La connessione di ciascun nodo della griglia consente al servizio ADC di raccogliere informazioni sulla topologia.  Le informazioni sul nodo della griglia includono il carico della CPU, lo spazio disponibile su disco (se dispone di spazio di archiviazione), i servizi supportati e l'ID del sito del nodo della griglia.  Altri servizi richiedono al servizio ADC informazioni sulla topologia tramite query sulla topologia.  Il servizio ADC risponde a ogni query con le informazioni più recenti ricevute dal sistema StorageGRID .

====


 a| 
Cassandra
 a| 
Memorizza e protegge i metadati degli oggetti.

*Nota*: i nodi di archiviazione solo dati non ospitano il servizio Cassandra.



 a| 
Cassandra Reaper
 a| 
Esegue riparazioni automatiche dei metadati degli oggetti.

*Nota*: i nodi di archiviazione solo dati non ospitano il servizio Cassandra Reaper.



 a| 
Pezzo
 a| 
Gestisce i dati codificati in modo cancellabile e i frammenti di parità.



 a| 
Spostamento dati (DMV)
 a| 
Sposta i dati nei pool di archiviazione cloud.



 a| 
Archivio dati distribuito (DDS)
 a| 
Monitora l'archiviazione dei metadati degli oggetti.

.Dettagli
[%collapsible]
====
Ogni nodo di archiviazione include il servizio Distributed Data Store (DDS).  Questo servizio si interfaccia con il database Cassandra per eseguire attività in background sui metadati degli oggetti archiviati nel sistema StorageGRID .

Il servizio DDS tiene traccia del numero totale di oggetti ingeriti nel sistema StorageGRID , nonché del numero totale di oggetti ingeriti tramite ciascuna delle interfacce supportate dal sistema (S3).

====


 a| 
Identità (idnt)
 a| 
Federa le identità utente da LDAP e Active Directory.



 a| 
[[ldr-service]]Router di distribuzione locale (LDR)
 a| 
Elabora le richieste del protocollo di archiviazione degli oggetti e gestisce i dati degli oggetti su disco.

.Dettagli
[%collapsible]
====
Ogni nodo di archiviazione _combinato_, _solo dati_ e _solo metadati_ include il servizio Local Distribution Router (LDR).  Questo servizio gestisce le funzioni di trasporto dei contenuti, tra cui l'archiviazione dei dati, l'instradamento e la gestione delle richieste.  Il servizio LDR svolge la maggior parte del lavoro del sistema StorageGRID gestendo i carichi di trasferimento dati e le funzioni di traffico dati.

Il servizio LDR gestisce le seguenti attività:

* Query
* Attività di gestione del ciclo di vita delle informazioni (ILM)
* Eliminazione dell'oggetto
* Archiviazione dati di oggetti
* Trasferimenti di dati di oggetti da un altro servizio LDR (nodo di archiviazione)
* Gestione dell'archiviazione dei dati
* Interfaccia del protocollo S3


Il servizio LDR mappa inoltre ogni oggetto S3 al suo UUID univoco.

Negozi di oggetti:: L'archiviazione dei dati sottostante di un servizio LDR è suddivisa in un numero fisso di archivi di oggetti (noti anche come volumi di archiviazione).  Ogni archivio di oggetti è un punto di montaggio separato.
+
--
Gli archivi di oggetti in un nodo di archiviazione sono identificati da un numero esadecimale compreso tra 0000 e 002F, noto come ID volume.  Nel primo archivio oggetti (volume 0) viene riservato spazio per i metadati degli oggetti in un database Cassandra; tutto lo spazio rimanente su quel volume viene utilizzato per i dati degli oggetti.  Tutti gli altri archivi di oggetti vengono utilizzati esclusivamente per i dati degli oggetti, che includono copie replicate e frammenti con codice di cancellazione.

Per garantire un utilizzo uniforme dello spazio per le copie replicate, i dati degli oggetti per un dato oggetto vengono archiviati in un archivio oggetti in base allo spazio di archiviazione disponibile.  Quando un archivio oggetti raggiunge la sua capacità massima, gli archivi oggetti rimanenti continuano a memorizzare oggetti finché non c'è più spazio sul nodo di archiviazione.

--
Protezione dei metadati:: StorageGRID memorizza i metadati degli oggetti in un database Cassandra, che si interfaccia con il servizio LDR.
+
--
Per garantire la ridondanza e quindi la protezione contro la perdita, in ogni sito vengono conservate tre copie dei metadati degli oggetti.  Questa replica non è configurabile e viene eseguita automaticamente. Per maggiori dettagli, vedere link:../admin/managing-object-metadata-storage.html["Gestire l'archiviazione dei metadati degli oggetti"] .

--


====


 a| 
Macchina a stati replicati (RSM)
 a| 
Garantisce che le richieste dei servizi della piattaforma S3 vengano inviate ai rispettivi endpoint.



 a| 
Monitoraggio dello stato del server (SSM)
 a| 
Monitora il sistema operativo e l'hardware sottostante.

|===