---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, add node, add site, expand, expansion 
summary: Seguire questa procedura per aggiungere nodi griglia a siti esistenti o per aggiungere un nuovo sito.  È possibile eseguire solo un tipo di espansione alla volta. 
---
= Aggiungi nodi griglia al sito esistente o aggiungi un nuovo sito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seguire questa procedura per aggiungere nodi griglia a siti esistenti o per aggiungere un nuovo sito.  È possibile eseguire solo un tipo di espansione alla volta.

.Prima di iniziare
* Tu hai illink:../admin/admin-group-permissions.html["Accesso root o autorizzazione di manutenzione"] .
* Tutti i nodi esistenti nella griglia sono attivi e funzionanti in tutti i siti.
* Tutte le precedenti procedure di espansione, aggiornamento, dismissione o ripristino sono state completate.
+

NOTE: Non è possibile avviare un'espansione mentre è in corso un'altra procedura di espansione, aggiornamento, ripristino o dismissione attiva.  Tuttavia, se necessario, è possibile sospendere una procedura di dismissione per avviare un'espansione.



.Passi
. link:updating-subnets-for-grid-network.html["Aggiorna le subnet per Grid Network"] .
. link:deploying-new-grid-nodes.html["Distribuisci nuovi nodi della griglia"] .
. link:performing-expansion.html["Eseguire l'espansione"] .

