---
permalink: expand/adding-grid-nodes-to-add-capabilities.html 
sidebar: sidebar 
keywords: grid nodes, expand, expansion, site, add 
summary: È possibile aggiungere ridondanza o funzionalità aggiuntive a un sistema StorageGRID aggiungendo nuovi nodi della griglia ai siti esistenti. 
---
= Aggiungi nodi di griglia per aggiungere funzionalità al tuo sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere ridondanza o funzionalità aggiuntive a un sistema StorageGRID aggiungendo nuovi nodi della griglia ai siti esistenti.

Ad esempio, potresti scegliere di aggiungere nodi gateway da utilizzare in un gruppo ad alta disponibilità (HA) oppure potresti aggiungere un nodo di amministrazione in un sito remoto per consentire il monitoraggio tramite un nodo locale.

È possibile aggiungere uno o più dei seguenti tipi di nodi a uno o più siti esistenti in un'unica operazione di espansione:

* Nodi amministrativi non primari
* Nodi di archiviazione
* Nodi gateway


Quando ci si prepara ad aggiungere nodi alla griglia, tenere presente le seguenti limitazioni:

* Il nodo di amministrazione primario viene distribuito durante l'installazione iniziale.  Non è possibile aggiungere un nodo amministrativo primario durante un'espansione.
* È possibile aggiungere nodi di archiviazione e altri tipi di nodi nella stessa espansione.
* Quando si aggiungono nodi di archiviazione, è necessario pianificare attentamente il numero e la posizione dei nuovi nodi. Vedere link:../expand/guidelines-for-adding-object-capacity.html["Linee guida per l'aggiunta di capacità dell'oggetto"] .
* Se l'opzione *Imposta nuovo nodo predefinito* è *Non attendibile* nella scheda Reti client non attendibili nella pagina Controllo firewall, le applicazioni client che si connettono ai nodi di espansione tramite la rete client devono connettersi tramite una porta endpoint del bilanciatore del carico (*CONFIGURAZIONE* > *Sicurezza* > *Controllo firewall*). Vedi le istruzioni perlink:../admin/configure-firewall-controls.html["modificare le impostazioni di sicurezza per il nuovo nodo"] e alink:../admin/configuring-load-balancer-endpoints.html["configurare gli endpoint del bilanciatore del carico"] .

