---
permalink: expand/index.html 
sidebar: sidebar 
keywords: expand grid 
summary: È possibile espandere la capacità o le funzionalità del sistema StorageGRID senza interrompere le operazioni del sistema. 
---
= Tipi di espansione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile espandere la capacità o le funzionalità del sistema StorageGRID senza interrompere le operazioni del sistema.

Un'espansione StorageGRID consente di aggiungere:

* Volumi di archiviazione su nodi di archiviazione
* Nuovi nodi della griglia in un sito esistente
* Un sito completamente nuovo


Il motivo per cui si esegue l'espansione determina quanti nuovi nodi di ciascun tipo è necessario aggiungere e la posizione di tali nuovi nodi.  Ad esempio, i requisiti dei nodi sono diversi se si esegue un'espansione per aumentare la capacità di archiviazione, aggiungere capacità di metadati o aggiungere ridondanza o nuove funzionalità.

Segui i passaggi per il tipo di espansione che stai eseguendo:

[role="tabbed-block"]
====
.Aggiungere volumi di archiviazione
--
Segui i passaggi perlink:adding-storage-volumes-to-storage-nodes.html["aggiunta di volumi di archiviazione ai nodi di archiviazione"] .

--
.Aggiungi nodi della griglia
--
. Segui i passaggi perlink:adding-grid-nodes-to-existing-site-or-adding-new-site.html["aggiunta di nodi della griglia a un sito esistente"] .
. link:updating-subnets-for-grid-network.html["Aggiorna le subnet"] .
. Distribuisci nodi della griglia:
+
** link:deploying-new-grid-nodes.html#appliances-deploying-storage-gateway-or-non-primary-admin-nodes["Elettrodomestici"]
** link:deploying-new-grid-nodes.html#vmware-deploy-grid-nodes["VMware"]
** link:deploying-new-grid-nodes.html#linux-deploy-grid-nodes["Linux"]
+

NOTE: Con "Linux" si intende una distribuzione Red Hat Enterprise Linux, Ubuntu o Debian. Per un elenco delle versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Strumento matrice di interoperabilità NetApp (IMT)"^] .



. link:performing-expansion.html["Eseguire l'espansione"] .
. link:configuring-expanded-storagegrid-system.html["Configurare il sistema espanso"] .


--
.Aggiungi nuovo sito
--
. Segui i passaggi perlink:adding-grid-nodes-to-existing-site-or-adding-new-site.html["Aggiungere un nuovo sito"] .
. link:updating-subnets-for-grid-network.html["Aggiorna le subnet"] .
. Distribuisci nodi della griglia:
+
** link:deploying-new-grid-nodes.html#appliances-deploying-storage-gateway-or-non-primary-admin-nodes["Elettrodomestici"]
** link:deploying-new-grid-nodes.html#vmware-deploy-grid-nodes["VMware"]
** link:deploying-new-grid-nodes.html#linux-deploy-grid-nodes["Linux"]
+

NOTE: Con "Linux" si intende una distribuzione Red Hat Enterprise Linux, Ubuntu o Debian. Per un elenco delle versioni supportate, vedere https://imt.netapp.com/matrix/#welcome["Strumento matrice di interoperabilità NetApp (IMT)"^] .



. link:performing-expansion.html["Eseguire l'espansione"] .
. link:configuring-expanded-storagegrid-system.html["Configurare il sistema espanso"] .


--
====