---
permalink: expand/linux-adding-direct-attached-or-san-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expansion, Linux, add storage volumes 
summary: Se un nodo di archiviazione include meno di 48 volumi di archiviazione, è possibile aumentarne la capacità aggiungendo nuovi dispositivi di archiviazione a blocchi, rendendoli visibili agli host Linux e aggiungendo i nuovi mapping dei dispositivi a blocchi al file di configurazione StorageGRID utilizzato per il nodo di archiviazione. 
---
= Linux: aggiungi volumi SAN o collegati direttamente al nodo di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se un nodo di archiviazione include meno di 48 volumi di archiviazione, è possibile aumentarne la capacità aggiungendo nuovi dispositivi di archiviazione a blocchi, rendendoli visibili agli host Linux e aggiungendo i nuovi mapping dei dispositivi a blocchi al file di configurazione StorageGRID utilizzato per il nodo di archiviazione.

.Prima di iniziare
* Hai accesso alle istruzioni per installare StorageGRID sulla tua piattaforma Linux.
+
** link:../rhel/index.html["Installa StorageGRID su Red Hat Enterprise Linux"]
** link:../ubuntu/index.html["Installa StorageGRID su Ubuntu o Debian"]


* Tu hai il `Passwords.txt` file.
* Hailink:../admin/admin-group-permissions.html["autorizzazioni di accesso specifiche"] .



CAUTION: Non tentare di aggiungere volumi di archiviazione a un nodo di archiviazione mentre è attivo un aggiornamento software, una procedura di ripristino o un'altra procedura di espansione.

.Informazioni su questo compito
Il nodo di archiviazione non è disponibile per un breve periodo quando si aggiungono volumi di archiviazione.  È necessario eseguire questa procedura su un nodo di archiviazione alla volta per evitare di influire sui servizi di griglia rivolti al client.

.Passi
. Installare il nuovo hardware di archiviazione.
+
Per ulteriori informazioni, consultare la documentazione fornita dal fornitore dell'hardware.

. Creare nuovi volumi di archiviazione a blocchi delle dimensioni desiderate.
+
** Collegare le nuove unità e aggiornare la configurazione del controller RAID secondo necessità oppure allocare le nuove LUN SAN sugli array di archiviazione condivisi e consentire all'host Linux di accedervi.
** Utilizzare lo stesso schema di denominazione persistente utilizzato per i volumi di archiviazione sul nodo di archiviazione esistente.
** Se si utilizza la funzionalità di migrazione del nodo StorageGRID , rendere i nuovi volumi visibili agli altri host Linux che sono destinazioni di migrazione per questo nodo di archiviazione.  Per ulteriori informazioni, consultare le istruzioni per l'installazione di StorageGRID per la piattaforma Linux.


. Accedi all'host Linux che supporta il nodo di archiviazione come root o con un account che dispone dell'autorizzazione sudo.
. Verificare che i nuovi volumi di archiviazione siano visibili sull'host Linux.
+
Potrebbe essere necessario ripetere la scansione dei dispositivi.

. Eseguire il seguente comando per disabilitare temporaneamente il nodo di archiviazione:
+
`sudo storagegrid node stop <node-name>`

. Utilizzando un editor di testo come vim o pico, modificare il file di configurazione del nodo per il nodo di archiviazione, che può essere trovato in `/etc/storagegrid/nodes/<node-name>.conf` .
. Individuare la sezione del file di configurazione del nodo che contiene le mappature dei dispositivi a blocchi di archiviazione degli oggetti esistenti.
+
Nell'esempio, `BLOCK_DEVICE_RANGEDB_00` A `BLOCK_DEVICE_RANGEDB_03` sono le mappature dei dispositivi a blocchi di archiviazione degli oggetti esistenti.

+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
*BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0*
*BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1*
*BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2*
*BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. Aggiungere nuove mappature dei dispositivi a blocchi di archiviazione degli oggetti corrispondenti ai volumi di archiviazione dei blocchi aggiunti per questo nodo di archiviazione.
+
Assicurati di iniziare dal prossimo `BLOCK_DEVICE_RANGEDB_nn` .  Non lasciare spazi vuoti.

+
** Sulla base dell'esempio sopra, inizia da `BLOCK_DEVICE_RANGEDB_04` .
** Nell'esempio seguente, sono stati aggiunti al nodo quattro nuovi volumi di archiviazione a blocchi: `BLOCK_DEVICE_RANGEDB_04` A `BLOCK_DEVICE_RANGEDB_07` .


+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3
*BLOCK_DEVICE_RANGEDB_04 = /dev/mapper/sgws-sn1-rangedb-4*
*BLOCK_DEVICE_RANGEDB_05 = /dev/mapper/sgws-sn1-rangedb-5*
*BLOCK_DEVICE_RANGEDB_06 = /dev/mapper/sgws-sn1-rangedb-6*
*BLOCK_DEVICE_RANGEDB_07 = /dev/mapper/sgws-sn1-rangedb-7*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. Eseguire il seguente comando per convalidare le modifiche al file di configurazione del nodo per il nodo di archiviazione:
+
`sudo storagegrid node validate <node-name>`

+
Correggere eventuali errori o avvisi prima di procedere al passaggio successivo.

+
[NOTE]
====
Se si osserva un errore simile al seguente, significa che il file di configurazione del nodo sta tentando di mappare il dispositivo a blocchi utilizzato da `<node-name>` per `<PURPOSE>` al dato `<path-name>` nel file system Linux, ma non è presente un file speciale valido per il dispositivo a blocchi (o un collegamento simbolico a un file speciale per il dispositivo a blocchi) in quella posizione.

[listing]
----
Checking configuration file for node <node-name>…
ERROR: BLOCK_DEVICE_<PURPOSE> = <path-name>
<path-name> is not a valid block device
----
Verifica di aver inserito il codice corretto `<path-name>` .

====
. Eseguire il seguente comando per riavviare il nodo con le nuove mappature dei dispositivi a blocchi in atto:
+
`sudo storagegrid node start <node-name>`

. Accedi al nodo di archiviazione come amministratore utilizzando la password elencata in `Passwords.txt` file.
. Verificare che i servizi si avviino correttamente:
+
.. Visualizza un elenco dello stato di tutti i servizi sul server: +
`sudo storagegrid-status`
+
Lo stato viene aggiornato automaticamente.

.. Attendi che tutti i servizi siano in esecuzione o verificati.
.. Uscire dalla schermata di stato:
+
`Ctrl+C`



. Configurare il nuovo storage per l'utilizzo da parte del nodo di storage:
+
.. Configurare i nuovi volumi di archiviazione:
+
`sudo add_rangedbs.rb`

+
Questo script trova tutti i nuovi volumi di archiviazione e ti chiede di formattarli.

.. Immettere *y* per formattare i volumi di archiviazione.
.. Se uno qualsiasi dei volumi è stato precedentemente formattato, decidere se riformattarlo.
+
*** Inserisci *y* per riformattare.
*** Immettere *n* per saltare la riformattazione.




+
IL `setup_rangedbs.sh` lo script viene eseguito automaticamente.

. Verificare che lo stato di archiviazione del nodo di archiviazione sia online:
+
.. Sign in a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
.. Selezionare *SUPPORTO* > *Strumenti* > *Topologia griglia*.
.. Selezionare *_sito_* > *_Nodo di archiviazione_* > *LDR* > *Archiviazione*.
.. Selezionare la scheda *Configurazione* e poi la scheda *Principale*.
.. Se l'elenco a discesa *Stato di archiviazione - Desiderato* è impostato su Sola lettura o Offline, selezionare *Online*.
.. Fare clic su *Applica modifiche*.


. Per vedere i nuovi archivi di oggetti:
+
.. Selezionare *NODI* > *_sito_* > *_Nodo di archiviazione_* > *Archiviazione*.
.. Visualizza i dettagli nella tabella *Archivi oggetti*.




.Risultato
Ora è possibile utilizzare la capacità ampliata dei nodi di archiviazione per salvare i dati degli oggetti.
