---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: 'Dopo il completamento di un"operazione di espansione che aggiunge nuovi nodi di archiviazione, il sistema StorageGRID dovrebbe avviarsi automaticamente utilizzando i nuovi nodi di archiviazione.  È necessario utilizzare il sistema StorageGRID per verificare che il nuovo nodo di archiviazione sia attivo.' 
---
= Verificare che il nodo di archiviazione sia attivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo il completamento di un'operazione di espansione che aggiunge nuovi nodi di archiviazione, il sistema StorageGRID dovrebbe avviarsi automaticamente utilizzando i nuovi nodi di archiviazione.  È necessario utilizzare il sistema StorageGRID per verificare che il nuovo nodo di archiviazione sia attivo.

.Passi
. Sign in a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
. Selezionare *NODI* > *_Nodo di archiviazione di espansione_* > *Archiviazione*.
. Posiziona il cursore sul grafico *Spazio di archiviazione utilizzato - Dati oggetto* per visualizzare il valore di *Utilizzato*, ovvero la quantità di spazio utilizzabile totale che è stata utilizzata per i dati oggetto.
. Verifica che il valore di *Usato* aumenti spostando il cursore verso destra sul grafico.

