---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expand, expansion, storage node, add storage volumes, VMware 
summary: Se un nodo di archiviazione include meno di 16 volumi di archiviazione, è possibile aumentarne la capacità utilizzando VMware vSphere per aggiungere volumi. 
---
= VMware: aggiungi volumi di archiviazione al nodo di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se un nodo di archiviazione include meno di 16 volumi di archiviazione, è possibile aumentarne la capacità utilizzando VMware vSphere per aggiungere volumi.

.Prima di iniziare
* È possibile accedere alle istruzioni per l'installazione di StorageGRID per le distribuzioni VMware.
+
** link:../vmware/index.html["Installa StorageGRID su VMware"]


* Tu hai il `Passwords.txt` file.
* Hailink:../admin/admin-group-permissions.html["autorizzazioni di accesso specifiche"] .



CAUTION: Non tentare di aggiungere volumi di archiviazione a un nodo di archiviazione mentre è attivo un aggiornamento software, una procedura di ripristino o un'altra procedura di espansione.

.Informazioni su questo compito
Il nodo di archiviazione non è disponibile per un breve periodo quando si aggiungono volumi di archiviazione.  È necessario eseguire questa procedura su un nodo di archiviazione alla volta per evitare di influire sui servizi di griglia rivolti al client.

.Passi
. Se necessario, installare nuovo hardware di archiviazione e creare nuovi datastore VMware.
. Aggiungere uno o più dischi rigidi alla macchina virtuale da utilizzare come storage (archivi di oggetti).
+
.. Aprire VMware vSphere Client.
.. Modificare le impostazioni della macchina virtuale per aggiungere uno o più dischi rigidi aggiuntivi.


+
I dischi rigidi sono in genere configurati come dischi di macchine virtuali (VMDK).  I VMDK sono più comunemente utilizzati e più facili da gestire, mentre gli RDM potrebbero offrire prestazioni migliori per carichi di lavoro che utilizzano dimensioni di oggetti maggiori (ad esempio, superiori a 100 MB).  Per ulteriori informazioni sull'aggiunta di dischi rigidi alle macchine virtuali, consultare la documentazione di VMware vSphere.

. Riavviare la macchina virtuale utilizzando l'opzione *Riavvia sistema operativo guest* in VMware vSphere Client oppure immettendo il seguente comando in una sessione ssh sulla macchina virtuale:``sudo reboot``
+

NOTE: Non utilizzare *Spegnimento* o *Ripristino* per riavviare la macchina virtuale.

. Configurare il nuovo storage per l'utilizzo da parte del nodo di storage:
+
.. Accedi al nodo della griglia:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Inserisci la password elencata nel `Passwords.txt` file.
... Immettere il seguente comando per passare alla root: `su -`
... Inserisci la password elencata nel `Passwords.txt` file.  Quando si accede come root, il prompt cambia da `$` A `#` .


.. Configurare i nuovi volumi di archiviazione:
+
`sudo add_rangedbs.rb`

+
Questo script trova tutti i nuovi volumi di archiviazione e ti chiede di formattarli.

.. Inserisci *y* per accettare la formattazione.
.. Se uno qualsiasi dei volumi è stato precedentemente formattato, decidere se riformattarlo.
+
*** Inserisci *y* per riformattare.
*** Immettere *n* per saltare la riformattazione.




+
IL `setup_rangedbs.sh` lo script viene eseguito automaticamente.

. Verificare che i servizi si avviino correttamente:
+
.. Visualizza un elenco dello stato di tutti i servizi sul server:
+
`sudo storagegrid-status`

+
Lo stato viene aggiornato automaticamente.

.. Attendi che tutti i servizi siano in esecuzione o verificati.
.. Uscire dalla schermata di stato:
+
`Ctrl+C`



. Verificare che il nodo di archiviazione sia online:
+
.. Sign in a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
.. Selezionare *SUPPORTO* > *Strumenti* > *Topologia griglia*.
.. Selezionare *_sito_* > *_Nodo di archiviazione_* > *LDR* > *Archiviazione*.
.. Selezionare la scheda *Configurazione* e poi la scheda *Principale*.
.. Se l'elenco a discesa *Stato di archiviazione - Desiderato* è impostato su Sola lettura o Offline, selezionare *Online*.
.. Selezionare *Applica modifiche*.


. Per vedere i nuovi archivi di oggetti:
+
.. Selezionare *NODI* > *_sito_* > *_Nodo di archiviazione_* > *Archiviazione*.
.. Visualizza i dettagli nella tabella *Archivi oggetti*.




.Risultato
È possibile utilizzare la capacità estesa dei nodi di archiviazione per salvare i dati degli oggetti.
