---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: 'Gli oggetti possono essere recuperati per diversi motivi, tra cui richieste di lettura da un"applicazione client, verifiche in background dei dati degli oggetti replicati, rivalutazioni ILM e ripristino dei dati degli oggetti durante il ripristino di un nodo di archiviazione.' 
---
= Risolvere i problemi relativi ai dati degli oggetti persi e mancanti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli oggetti possono essere recuperati per diversi motivi, tra cui richieste di lettura da un'applicazione client, verifiche in background dei dati degli oggetti replicati, rivalutazioni ILM e ripristino dei dati degli oggetti durante il ripristino di un nodo di archiviazione.

Il sistema StorageGRID utilizza le informazioni sulla posizione contenute nei metadati di un oggetto per determinare da quale posizione recuperare l'oggetto. Se non viene trovata una copia dell'oggetto nella posizione prevista, il sistema tenta di recuperare un'altra copia dell'oggetto da un'altra posizione nel sistema, presupponendo che la policy ILM contenga una regola per creare due o più copie dell'oggetto.

Se il recupero ha esito positivo, il sistema StorageGRID sostituisce la copia mancante dell'oggetto. In caso contrario, viene attivato l'avviso *Oggetti persi*, come segue:

* Per le copie replicate, se non è possibile recuperarne un'altra copia, l'oggetto viene considerato perso e viene attivato l'avviso.
* Per le copie con codice di cancellazione, se non è possibile recuperare una copia dalla posizione prevista, l'attributo ECOR (Corrupt Copies Detected) viene incrementato di uno prima che venga effettuato un tentativo di recuperare una copia da un'altra posizione.  Se non viene trovata nessun'altra copia, viene attivato l'avviso.


È necessario esaminare immediatamente tutti gli avvisi di *Oggetti persi* per determinare la causa principale della perdita e per stabilire se l'oggetto potrebbe ancora esistere in un nodo di archiviazione offline o altrimenti non disponibile. Vedere link:../troubleshoot/investigating-lost-objects.html["Indagare sugli oggetti smarriti"] .

Nel caso in cui i dati degli oggetti senza copie vengano persi, non esiste alcuna soluzione di recupero. Tuttavia, è necessario reimpostare il contatore degli oggetti persi per evitare che gli oggetti persi noti mascherino nuovi oggetti persi. Vedere link:resetting-lost-and-missing-object-counts.html["Reimposta il conteggio degli oggetti persi e mancanti"] .
