---
permalink: troubleshoot/troubleshooting-syslog-server.html 
sidebar: sidebar 
keywords: how to troubleshoot the external syslog server 
summary: 'Nella tabella seguente vengono descritti i messaggi di errore che potrebbero essere correlati all"utilizzo di un server syslog esterno e vengono elencate le azioni correttive.' 
---
= Risolvere i problemi di un server syslog esterno
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nella tabella seguente vengono descritti i messaggi di errore che potrebbero essere correlati all'utilizzo di un server syslog esterno e vengono elencate le azioni correttive.

Per ulteriori informazioni sull'invio di informazioni di audit a un server syslog esterno, vedere:

* link:../monitor/considerations-for-external-syslog-server.html["Considerazioni sull'utilizzo di un server syslog esterno"]
* link:../monitor/configure-audit-messages.html["Configurare i messaggi di controllo e il server syslog esterno"]


[cols="1a,3a"]
|===
| Messaggio di errore | Descrizione e azioni consigliate 


 a| 
Non è possibile risolvere un indirizzo su un nome host
 a| 
Il nome di dominio completo immesso per il server syslog non può essere risolto in un indirizzo IP.

. Controlla il nome host inserito.  Se hai inserito un indirizzo IP, assicurati che sia un indirizzo IP valido in notazione WXYZ ("decimale puntato").
. Verificare che i server DNS siano configurati correttamente.
. Verificare che ciascun nodo possa accedere agli indirizzi IP del server DNS.




 a| 
Connessione rifiutata
 a| 
Una connessione TCP o TLS al server syslog è stata rifiutata.  Potrebbe non esserci alcun servizio in ascolto sulla porta TCP o TLS per l'host oppure un firewall potrebbe bloccare l'accesso.

. Verificare di aver inserito il nome di dominio completo (FQDN) o l'indirizzo IP, la porta e il protocollo corretti per il server syslog.
. Verificare che l'host per il servizio syslog stia eseguendo un demone syslog in ascolto sulla porta specificata.
. Verificare che un firewall non stia bloccando l'accesso alle connessioni TCP/TLS dai nodi all'IP e alla porta del server syslog.




 a| 
Rete irraggiungibile
 a| 
Il server syslog non si trova su una subnet direttamente collegata.  Un router ha restituito un messaggio di errore ICMP per indicare che non è riuscito a inoltrare i messaggi di prova dai nodi elencati al server syslog.

. Verificare di aver inserito il nome di dominio completo o l'indirizzo IP corretto per il server syslog.
. Per ogni nodo elencato, controllare l'elenco delle subnet della rete Grid, gli elenchi delle subnet delle reti amministrative e i gateway della rete client.  Verificare che siano configurati per instradare il traffico verso il server syslog tramite l'interfaccia di rete e il gateway previsti (Grid, Admin o Client).




 a| 
Host non raggiungibile
 a| 
Il server syslog si trova su una subnet direttamente collegata (subnet utilizzata dai nodi elencati per i loro indirizzi IP Grid, Admin o Client).  I nodi hanno tentato di inviare messaggi di prova, ma non hanno ricevuto risposte alle richieste ARP per l'indirizzo MAC del server syslog.

. Verificare di aver inserito il nome di dominio completo o l'indirizzo IP corretto per il server syslog.
. Verificare che l'host che esegue il servizio syslog sia attivo.




 a| 
Connessione scaduta
 a| 
È stato effettuato un tentativo di connessione TCP/TLS, ma per molto tempo non è stata ricevuta alcuna risposta dal server syslog.  Potrebbe esserci un errore di configurazione del routing oppure un firewall potrebbe interrompere il traffico senza inviare alcuna risposta (una configurazione comune).

. Verificare di aver inserito il nome di dominio completo o l'indirizzo IP corretto per il server syslog.
. Per ogni nodo elencato, controllare l'elenco delle subnet della rete Grid, gli elenchi delle subnet delle reti amministrative e i gateway della rete client.  Verificare che siano configurati per instradare il traffico verso il server syslog utilizzando l'interfaccia di rete e il gateway (Grid, Admin o Client) tramite i quali si prevede di raggiungere il server syslog.
. Verificare che un firewall non stia bloccando l'accesso alle connessioni TCP/TLS dai nodi elencati all'IP e alla porta del server syslog.




 a| 
Connessione chiusa dal partner
 a| 
Una connessione TCP al server syslog è stata stabilita correttamente, ma è stata successivamente chiusa.  Le ragioni potrebbero essere:

* Il server syslog potrebbe essere stato riavviato.
* Il nodo e il server syslog potrebbero avere impostazioni TCP/TLS diverse.
* Un firewall intermedio potrebbe chiudere le connessioni TCP inattive.
* Un server non syslog in ascolto sulla porta del server syslog potrebbe aver chiuso la connessione.


Per risolvere questo problema:

. Verificare di aver inserito il nome di dominio completo (FQDN) o l'indirizzo IP, la porta e il protocollo corretti per il server syslog.
. Se si utilizza TLS, verificare che anche il server syslog utilizzi TLS.  Se si utilizza TCP, verificare che anche il server syslog utilizzi TCP.
. Verificare che non sia configurato un firewall intermedio per chiudere le connessioni TCP inattive.




 a| 
Errore del certificato TLS
 a| 
Il certificato del server ricevuto dal server syslog non era compatibile con il bundle di certificati CA e il certificato client forniti.

. Verificare che il bundle di certificati CA e il certificato client (se presente) siano compatibili con il certificato del server sul server syslog.
. Verificare che le identità nel certificato del server dal server syslog includano i valori IP o FQDN previsti.




 a| 
Inoltro sospeso
 a| 
I record Syslog non vengono più inoltrati al server Syslog e StorageGRID non è in grado di rilevarne il motivo.

Esaminare i log di debug forniti con questo errore per tentare di determinarne la causa principale.



 a| 
Sessione TLS terminata
 a| 
Il server syslog ha terminato la sessione TLS e StorageGRID non è in grado di rilevarne il motivo.

. Esaminare i log di debug forniti con questo errore per tentare di determinarne la causa principale.
. Verificare di aver inserito il nome di dominio completo (FQDN) o l'indirizzo IP, la porta e il protocollo corretti per il server syslog.
. Se si utilizza TLS, verificare che anche il server syslog utilizzi TLS.  Se si utilizza TCP, verificare che anche il server syslog utilizzi TCP.
. Verificare che il pacchetto di certificati CA e il certificato client (se presente) siano compatibili con il certificato del server dal server syslog.
. Verificare che le identità nel certificato del server dal server syslog includano i valori IP o FQDN previsti.




 a| 
Query dei risultati non riuscita
 a| 
Il nodo di amministrazione utilizzato per la configurazione e il test del server syslog non è in grado di richiedere i risultati dei test dai nodi elencati.  Uno o più nodi potrebbero essere inattivi.

. Seguire i passaggi standard per la risoluzione dei problemi per assicurarsi che i nodi siano online e che tutti i servizi previsti siano in esecuzione.
. Riavviare il servizio miscd sui nodi elencati.


|===