---
permalink: ilm/considerations-for-cloud-storage-pools.html 
sidebar: sidebar 
keywords: what is a cloud storage pool, considerations for a cloud storage pool 
summary: 'Se si prevede di utilizzare un Cloud Storage Pool per spostare oggetti fuori dal sistema StorageGRID , è necessario esaminare le considerazioni per la configurazione e l"utilizzo dei Cloud Storage Pool.' 
---
= Considerazioni sui pool di archiviazione cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si prevede di utilizzare un Cloud Storage Pool per spostare oggetti fuori dal sistema StorageGRID , è necessario esaminare le considerazioni per la configurazione e l'utilizzo dei Cloud Storage Pool.



== Considerazioni generali

* In generale, l'archiviazione cloud, come Amazon S3 Glacier o Azure Blob Storage, è un modo economico per archiviare dati di oggetti.  Tuttavia, i costi per recuperare i dati dall'archiviazione cloud sono relativamente elevati.  Per ottenere il costo complessivo più basso, è necessario considerare quando e con quale frequenza si accederà agli oggetti nel Cloud Storage Pool.  Si consiglia di utilizzare un pool di archiviazione cloud solo per i contenuti a cui si prevede di accedere raramente.
* L'utilizzo di Cloud Storage Pool con FabricPool non è supportato a causa della latenza aggiuntiva necessaria per recuperare un oggetto dalla destinazione di Cloud Storage Pool.
* Gli oggetti con S3 Object Lock abilitato non possono essere inseriti nei Cloud Storage Pool.
* Se il bucket S3 di destinazione per un Cloud Storage Pool ha abilitato il blocco degli oggetti S3, il tentativo di configurare la replica del bucket (PutBucketReplication) fallirà con un errore AccessDenied.
* Le seguenti combinazioni di piattaforma, autenticazione e protocollo con blocco oggetto S3 non sono supportate per i pool di archiviazione cloud:
+
** *Piattaforme*: Google Cloud Platform e Azure
** *Tipi di autenticazione*: ruoli IAM ovunque e accesso anonimo
** *Protocollo*: HTTP






== Considerazioni sulle porte utilizzate per i pool di archiviazione cloud

Per garantire che le regole ILM possano spostare oggetti da e verso il Cloud Storage Pool specificato, è necessario configurare la rete o le reti che contengono i nodi di archiviazione del sistema.  È necessario assicurarsi che le seguenti porte possano comunicare con il Cloud Storage Pool.

Per impostazione predefinita, i pool di archiviazione cloud utilizzano le seguenti porte:

* *80*: Per gli URI degli endpoint che iniziano con http
* *443*: Per gli URI degli endpoint che iniziano con https


È possibile specificare una porta diversa quando si crea o si modifica un Cloud Storage Pool.

Se si utilizza un server proxy non trasparente, è necessario anchelink:../admin/configuring-storage-proxy-settings.html["configurare un proxy di archiviazione"] per consentire l'invio di messaggi a endpoint esterni, ad esempio un endpoint su Internet.



== Considerazioni sui costi

Per accedere allo storage nel cloud tramite un Cloud Storage Pool è necessaria la connettività di rete al cloud.  È necessario considerare il costo dell'infrastruttura di rete che verrà utilizzata per accedere al cloud e predisporla in modo appropriato, in base alla quantità di dati che si prevede di spostare tra StorageGRID e il cloud utilizzando il Cloud Storage Pool.

Quando StorageGRID si connette all'endpoint esterno del Cloud Storage Pool, invia varie richieste per monitorare la connettività e garantire che possa eseguire le operazioni richieste.  Sebbene a queste richieste siano associati alcuni costi aggiuntivi, il costo del monitoraggio di un Cloud Storage Pool dovrebbe rappresentare solo una piccola frazione del costo complessivo dell'archiviazione degli oggetti in S3 o Azure.

Potrebbero essere sostenuti costi più significativi se è necessario spostare oggetti da un endpoint Cloud Storage Pool esterno a StorageGRID.  Gli oggetti potrebbero essere spostati nuovamente su StorageGRID in uno dei seguenti casi:

* L'unica copia dell'oggetto si trova in un Cloud Storage Pool e si decide di archiviare l'oggetto in StorageGRID .  In questo caso, è necessario riconfigurare le regole e i criteri ILM.  Quando si verifica la valutazione ILM, StorageGRID invia più richieste per recuperare l'oggetto dal Cloud Storage Pool.  StorageGRID crea quindi localmente il numero specificato di copie replicate o con codice di cancellazione.  Dopo che l'oggetto viene spostato nuovamente su StorageGRID, la copia nel Cloud Storage Pool viene eliminata.
* Gli oggetti vengono persi a causa di un errore del nodo di archiviazione.  Se l'unica copia rimanente di un oggetto si trova in un Cloud Storage Pool, StorageGRID ripristina temporaneamente l'oggetto e crea una nuova copia sul nodo di archiviazione recuperato.



NOTE: Quando gli oggetti vengono spostati nuovamente su StorageGRID da un Cloud Storage Pool, StorageGRID invia più richieste all'endpoint del Cloud Storage Pool per ciascun oggetto.  Prima di spostare un gran numero di oggetti, contattare l'assistenza tecnica per ottenere assistenza nella stima dei tempi e dei costi associati.



== S3: Autorizzazioni richieste per il bucket Cloud Storage Pool

I criteri per il bucket S3 esterno utilizzato per un Cloud Storage Pool devono concedere a StorageGRID l'autorizzazione per spostare un oggetto nel bucket, ottenere lo stato di un oggetto, ripristinare un oggetto dallo storage Glacier quando necessario e altro ancora.  Idealmente, StorageGRID dovrebbe avere accesso completo al bucket(`s3:*` ); tuttavia, se ciò non è possibile, la policy del bucket deve concedere le seguenti autorizzazioni S3 a StorageGRID:

* `s3:AbortMultipartUpload`
* `s3:DeleteObject`
* `s3:GetObject`
* `s3:ListBucket`
* `s3:ListBucketMultipartUploads`
* `s3:ListMultipartUploadParts`
* `s3:PutObject`
* `s3:RestoreObject`




== S3: Considerazioni sul ciclo di vita del bucket esterno

Lo spostamento degli oggetti tra StorageGRID e il bucket S3 esterno specificato nel Cloud Storage Pool è controllato dalle regole ILM e dai criteri ILM attivi in ​​StorageGRID.  Al contrario, la transizione degli oggetti dal bucket S3 esterno specificato nel Cloud Storage Pool ad Amazon S3 Glacier o S3 Glacier Deep Archive (o a una soluzione di archiviazione che implementa la classe di archiviazione Glacier) è controllata dalla configurazione del ciclo di vita di quel bucket.

Se si desidera trasferire oggetti dal Cloud Storage Pool, è necessario creare la configurazione del ciclo di vita appropriata sul bucket S3 esterno e utilizzare una soluzione di archiviazione che implementi la classe di archiviazione Glacier e supporti l'API S3 RestoreObject.

Ad esempio, supponiamo di voler trasferire immediatamente tutti gli oggetti spostati da StorageGRID al Cloud Storage Pool allo storage Amazon S3 Glacier.  Dovresti creare una configurazione del ciclo di vita sul bucket S3 esterno che specifica una singola azione (*Transizione*) come segue:

[listing]
----
<LifecycleConfiguration>
  <Rule>
    <ID>Transition Rule</ID>
    <Filter>
       <Prefix></Prefix>
    </Filter>
    <Status>Enabled</Status>
    <Transition>
      <Days>0</Days>
      <StorageClass>GLACIER</StorageClass>
    </Transition>
  </Rule>
</LifecycleConfiguration>
----
Questa regola trasferirà tutti gli oggetti bucket ad Amazon S3 Glacier il giorno in cui sono stati creati (ovvero il giorno in cui sono stati spostati da StorageGRID al Cloud Storage Pool).


CAUTION: Quando si configura il ciclo di vita del bucket esterno, non utilizzare mai azioni *Scadenza* per definire quando scadono gli oggetti.  Le azioni di scadenza determinano l'eliminazione degli oggetti scaduti da parte del sistema di archiviazione esterno.  Se in seguito si tenta di accedere a un oggetto scaduto da StorageGRID, l'oggetto eliminato non verrà trovato.

Se si desidera trasferire gli oggetti nel Cloud Storage Pool a S3 Glacier Deep Archive (anziché ad Amazon S3 Glacier), specificare `<StorageClass>DEEP_ARCHIVE</StorageClass>` nel ciclo di vita del bucket.  Tuttavia, tieni presente che non puoi utilizzare il `Expedited` livello per ripristinare gli oggetti dall'archivio profondo del ghiacciaio S3.



== Azure: considerazioni sul livello di accesso

Quando si configura un account di archiviazione di Azure, è possibile impostare il livello di accesso predefinito su Accesso frequente o Accesso sporadico.  Quando si crea un account di archiviazione da utilizzare con un Cloud Storage Pool, è consigliabile utilizzare il livello Hot come livello predefinito.  Anche se StorageGRID imposta immediatamente il livello su Archivio quando sposta gli oggetti nel Cloud Storage Pool, l'utilizzo di un'impostazione predefinita su Caldo garantisce che non verrà addebitata alcuna commissione per l'eliminazione anticipata degli oggetti rimossi dal livello Freddo prima del minimo di 30 giorni.



== Azure: gestione del ciclo di vita non supportata

Non utilizzare la gestione del ciclo di vita dell'archiviazione BLOB di Azure per il contenitore utilizzato con un pool di archiviazione cloud.  Le operazioni del ciclo di vita potrebbero interferire con le operazioni del Cloud Storage Pool.

.Informazioni correlate
link:creating-cloud-storage-pool.html["Creare un pool di archiviazione cloud"]
