---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: Un Cloud Storage Pool specifica un singolo bucket Amazon S3 esterno o un altro provider compatibile con S3 oppure un contenitore di archiviazione BLOB di Azure. 
---
= Creare un pool di archiviazione cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un Cloud Storage Pool specifica un singolo bucket Amazon S3 esterno o un altro provider compatibile con S3 oppure un contenitore di archiviazione BLOB di Azure.

Quando si crea un Cloud Storage Pool, si specifica il nome e la posizione del bucket o del contenitore esterno che StorageGRID utilizzerà per archiviare gli oggetti, il tipo di provider cloud (Amazon S3/GCP o Azure Blob Storage) e le informazioni necessarie a StorageGRID per accedere al bucket o al contenitore esterno.

StorageGRID convalida il Cloud Storage Pool non appena lo salvi, quindi devi assicurarti che il bucket o il contenitore specificato nel Cloud Storage Pool esista e sia raggiungibile.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:../admin/admin-group-permissions.html["autorizzazioni di accesso richieste"] .
* Hai esaminato illink:considerations-for-cloud-storage-pools.html["considerazioni per i pool di archiviazione cloud"] .
* Il bucket o contenitore esterno a cui fa riferimento il Cloud Storage Pool esiste già e si dispone di<<service-endpoint-info,informazioni sull'endpoint del servizio>> .
* Per accedere al secchio o al contenitore, hai il<<authentication-account-info,informazioni sull'account per il tipo di autenticazione>> sceglierai tu.


.Passi
. Selezionare *ILM* > *Pool di archiviazione* > *Pool di archiviazione cloud*.
. Seleziona *Crea*, quindi inserisci le seguenti informazioni:
+
[cols="1a,3a"]
|===
| Campo | Descrizione 


 a| 
Nome del pool di archiviazione cloud
 a| 
Un nome che descrive brevemente il Cloud Storage Pool e il suo scopo.  Utilizzare un nome che sia facile da identificare quando si configurano le regole ILM.



 a| 
Tipo di fornitore
 a| 
Quale provider cloud utilizzerai per questo Cloud Storage Pool:

** *Amazon S3/GCP*: seleziona questa opzione per un provider Amazon S3, Commercial Cloud Services (C2S) S3, Google Cloud Platform (GCP) o un altro provider compatibile con S3.
** *Archiviazione BLOB di Azure*




 a| 
Secchio o contenitore
 a| 
Nome del bucket S3 esterno o del contenitore di Azure.  Non è possibile modificare questo valore dopo aver salvato il Cloud Storage Pool.

|===
. [[service-endpoint-info]]In base alla selezione del tipo di provider, immettere le informazioni sull'endpoint del servizio.
+
[role="tabbed-block"]
====
.Amazon S3/GCP
--
.. Per il protocollo, selezionare HTTPS o HTTP.
+

NOTE: Non utilizzare connessioni HTTP per dati sensibili.

.. Inserisci il nome host. Esempio:
+
`s3-_aws-region_.amazonaws.com`

.. Seleziona lo stile URL:
+
[cols="1a,3a"]
|===
| Opzione | Descrizione 


 a| 
Rilevamento automatico
 a| 
Tenta di rilevare automaticamente quale stile URL utilizzare, in base alle informazioni fornite.  Ad esempio, se si specifica un indirizzo IP, StorageGRID utilizzerà un URL in stile percorso.  Seleziona questa opzione solo se non sai quale stile specifico utilizzare.



 a| 
Stile ospitato virtuale
 a| 
Utilizzare un URL in stile virtual-hosted per accedere al bucket.  Gli URL in stile virtual-hosted includono il nome del bucket come parte del nome di dominio.  Esempio: `+https://bucket-name.s3.company.com/key-name+`



 a| 
Stile percorso
 a| 
Utilizzare un URL in stile percorso per accedere al bucket.  Gli URL in stile percorso includono il nome del bucket alla fine.  Esempio: `+https://s3.company.com/bucket-name/key-name+`

*Nota:* l'opzione URL in stile percorso non è consigliata e verrà deprecata in una futura versione di StorageGRID.

|===
.. Facoltativamente, immettere il numero di porta oppure utilizzare la porta predefinita: 443 per HTTPS o 80 per HTTP.


--
.Archiviazione BLOB di Azure
--
.. Utilizzando uno dei seguenti formati, immettere l'URI per l'endpoint del servizio.
+
*** `+https://host:port+`
*** `+http://host:port+`




Esempio: `https://_myaccount_.blob.core.windows.net:443`

Se non si specifica una porta, per impostazione predefinita viene utilizzata la porta 443 per HTTPS e la porta 80 per HTTP.

--
====


. [[authentication-account-info]]Seleziona *Continua*.  Quindi seleziona il tipo di autenticazione e inserisci le informazioni richieste per l'endpoint del Cloud Storage Pool:
+
[role="tabbed-block"]
====
.Chiave di accesso
--
_Per Amazon S3/GCP o altri provider compatibili con S3_

.. *ID chiave di accesso*: immettere l'ID chiave di accesso per l'account proprietario del bucket esterno.
.. *Chiave di accesso segreta*: Inserisci la chiave di accesso segreta.


--
.Ruoli IAM ovunque
--
_Per il servizio AWS IAM Roles Anywhere_

StorageGRID utilizza AWS Security Token Service (STS) per generare dinamicamente un token di breve durata per accedere alle risorse AWS.

.. *Regione AWS IAM Roles Anywhere*: seleziona la regione per il Cloud Storage Pool. Ad esempio,  `us-east-1` .
.. *URN dell'ancora di trust*: immettere l'URN dell'ancora di trust che convalida le richieste di credenziali STS di breve durata.  Può essere una CA radice o intermedia.
.. *URN del profilo*: immettere l'URN del profilo IAM Roles Anywhere che elenca i ruoli che possono essere assunti da chiunque sia considerato attendibile.
.. *URN del ruolo*: immettere l'URN del ruolo IAM che può essere assunto da chiunque sia considerato attendibile.
.. *Durata sessione*: immettere la durata delle credenziali di sicurezza temporanee e della sessione del ruolo.  Inserisci almeno 15 minuti e non più di 12 ore.
.. *Certificato CA del server* (facoltativo): uno o più certificati CA attendibili, in formato PEM, per la verifica del server IAM Roles Anywhere.  Se omesso, il server non verrà verificato.
.. *Certificato dell'entità finale*: la chiave pubblica, in formato PEM, del certificato X509 firmato dal trust anchor.  AWS IAM Roles Anywhere utilizza questa chiave per emettere un token STS.
.. *Chiave privata dell'entità finale*: la chiave privata per il certificato dell'entità finale.


--
.CAP (portale di accesso C2S)
--
_Per il servizio S3 dei servizi cloud commerciali (C2S)_

.. *URL delle credenziali temporanee*: immettere l'URL completo che StorageGRID utilizzerà per ottenere le credenziali temporanee dal server CAP, inclusi tutti i parametri API obbligatori e facoltativi assegnati al proprio account C2S.
.. *Certificato CA del server*: seleziona *Sfoglia* e carica il certificato CA che StorageGRID utilizzerà per verificare il server CAP.  Il certificato deve essere codificato PEM ed emesso da un'autorità di certificazione governativa (CA) appropriata.
.. *Certificato client*: seleziona *Sfoglia* e carica il certificato che StorageGRID utilizzerà per identificarsi sul server CAP.  Il certificato client deve essere codificato PEM, rilasciato da un'autorità di certificazione governativa (CA) appropriata e deve consentire l'accesso al tuo account C2S.
.. *Chiave privata client*: selezionare *Sfoglia* e caricare la chiave privata codificata PEM per il certificato client.
.. Se la chiave privata del client è crittografata, immettere la passphrase per decrittografare la chiave privata del client.  In caso contrario, lasciare vuoto il campo *Passphrase della chiave privata del client*.



NOTE: Se il certificato client verrà crittografato, utilizzare il formato tradizionale per la crittografia.  Il formato crittografato PKCS #8 non è supportato.

--
.Archiviazione BLOB di Azure
--
_Per Azure Blob Storage, solo chiave condivisa_

.. *Nome account*: immettere il nome dell'account di archiviazione proprietario del contenitore esterno
.. *Chiave account*: inserisci la chiave segreta per l'account di archiviazione


È possibile utilizzare il portale di Azure per trovare questi valori.

--
.Anonimo
--
Non sono richieste ulteriori informazioni.

--
====
. Selezionare *Continua*. Quindi scegli il tipo di verifica del server che desideri utilizzare:
+
[cols="1a,2a"]
|===
| Opzione | Descrizione 


 a| 
Utilizzare i certificati CA radice nel sistema operativo Storage Node
 a| 
Utilizzare i certificati Grid CA installati sul sistema operativo per proteggere le connessioni.



 a| 
Utilizza un certificato CA personalizzato
 a| 
Utilizzare un certificato CA personalizzato.  Selezionare *Sfoglia* e caricare il certificato codificato PEM.



 a| 
Non verificare il certificato
 a| 
Selezionando questa opzione le connessioni TLS al Cloud Storage Pool non saranno sicure.

|===
. Seleziona *Salva*.
+
Quando si salva un Cloud Storage Pool, StorageGRID esegue le seguenti operazioni:

+
** Verifica che il bucket o il contenitore e l'endpoint del servizio esistano e che possano essere raggiunti utilizzando le credenziali specificate.
** Scrive un file marcatore nel bucket o nel contenitore per identificarlo come Cloud Storage Pool.  Non rimuovere mai questo file, che si chiama `x-ntap-sgws-cloud-pool-uuid` .
+
Se la convalida del Cloud Storage Pool non riesce, viene visualizzato un messaggio di errore che spiega il motivo per cui la convalida non è riuscita.  Ad esempio, potrebbe essere segnalato un errore se si verifica un errore del certificato o se il bucket o il contenitore specificato non esiste già.



. Se si verifica un errore, vedere illink:troubleshooting-cloud-storage-pools.html["istruzioni per la risoluzione dei problemi dei pool di archiviazione cloud"] , risolvere eventuali problemi e quindi provare a salvare nuovamente il Cloud Storage Pool.

