---
permalink: ilm/manage-ilm-policy-tags.html 
sidebar: sidebar 
keywords: ILM policy tag 
summary: È possibile visualizzare i dettagli dei tag dei criteri ILM, modificare un tag o rimuovere un tag. 
---
= Gestisci i tag dei criteri ILM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare i dettagli dei tag dei criteri ILM, modificare un tag o rimuovere un tag.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:../admin/admin-group-permissions.html["autorizzazioni di accesso richieste"] .




== Visualizza i dettagli del tag della policy ILM

Per visualizzare i dettagli di un tag:

. Selezionare *ILM* > *Tag policy*.
. Selezionare il nome della policy dalla tabella.  Viene visualizzata la pagina dei dettagli del tag.
. Nella pagina dei dettagli, visualizza la cronologia precedente delle policy assegnate.
. Visualizza una policy selezionandola.




== Modifica tag policy ILM


NOTE: I nomi e le descrizioni dei tag sono visibili agli inquilini.  Scegli valori che aiuteranno i tenant a prendere una decisione informata quando selezionano i tag dei criteri da assegnare ai loro bucket.  Ad esempio, se la policy assegnata eliminerà gli oggetti dopo un certo periodo di tempo, è possibile comunicarlo nella descrizione.  Non includere informazioni sensibili in questi campi.

Per modificare la descrizione di un tag esistente:

. Selezionare *ILM* > *Tag policy*.
. Seleziona la casella di controllo per il tag, quindi seleziona *Modifica*.
+
In alternativa, seleziona il nome del tag.  Viene visualizzata la pagina dei dettagli del tag, in cui puoi selezionare *Modifica*.

. Modificare la descrizione del tag secondo necessità
. Seleziona *Salva*.




== Rimuovi il tag della policy ILM

Quando si rimuove un tag di policy, a tutti i bucket a cui è assegnato quel tag verrà applicata la policy predefinita.

Per rimuovere un tag:

. Selezionare *ILM* > *Tag policy*.
. Seleziona la casella di controllo per il tag, quindi seleziona *Rimuovi*.  Viene visualizzata una finestra di dialogo di conferma.
+
In alternativa, seleziona il nome del tag.  Viene visualizzata la pagina dei dettagli del tag, in cui puoi selezionare *Rimuovi*.

. Selezionare *Sì* per eliminare il tag.

