---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: In qualità di amministratore della griglia, puoi abilitare S3 Object Lock per il tuo sistema StorageGRID e implementare una policy ILM conforme per garantire che gli oggetti in bucket S3 specifici non vengano eliminati o sovrascritti per un periodo di tempo specificato. 
---
= Gestisci gli oggetti con S3 Object Lock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In qualità di amministratore della griglia, puoi abilitare S3 Object Lock per il tuo sistema StorageGRID e implementare una policy ILM conforme per garantire che gli oggetti in bucket S3 specifici non vengano eliminati o sovrascritti per un periodo di tempo specificato.



== Che cos'è S3 Object Lock?

La funzionalità StorageGRID S3 Object Lock è una soluzione di protezione degli oggetti equivalente a S3 Object Lock in Amazon Simple Storage Service (Amazon S3).

Quando l'impostazione globale S3 Object Lock è abilitata per un sistema StorageGRID , un account tenant S3 può creare bucket con o senza S3 Object Lock abilitato.  Se in un bucket è abilitato S3 Object Lock, è necessario il controllo delle versioni del bucket, che viene abilitato automaticamente.

*Un bucket senza S3 Object Lock* può contenere solo oggetti per i quali non sono specificate impostazioni di conservazione.  Nessun oggetto ingerito avrà impostazioni di conservazione.

*Un bucket con S3 Object Lock* può contenere oggetti con e senza impostazioni di conservazione specificate dalle applicazioni client S3.  Alcuni oggetti acquisiti avranno impostazioni di conservazione.

*Un bucket con S3 Object Lock e conservazione predefinita configurata* può contenere oggetti caricati con impostazioni di conservazione specificate e nuovi oggetti senza impostazioni di conservazione.  I nuovi oggetti utilizzano l'impostazione predefinita, perché l'impostazione di conservazione non è stata configurata a livello di oggetto.

Di fatto, tutti gli oggetti appena acquisiti hanno impostazioni di conservazione quando è configurata la conservazione predefinita.  Gli oggetti esistenti senza impostazioni di conservazione degli oggetti rimangono inalterati.



=== Modalità di conservazione

La funzionalità StorageGRID S3 Object Lock supporta due modalità di conservazione per applicare diversi livelli di protezione agli oggetti.  Queste modalità sono equivalenti alle modalità di conservazione di Amazon S3.

* In modalità conformità:
+
** L'oggetto non può essere eliminato finché non viene raggiunta la data di conservazione.
** La data di conservazione dell'oggetto può essere aumentata, ma non diminuita.
** La data di conservazione dell'oggetto non può essere rimossa finché non viene raggiunta tale data.


* In modalità di governance:
+
** Gli utenti con autorizzazioni speciali possono utilizzare un'intestazione di bypass nelle richieste per modificare determinate impostazioni di conservazione.
** Questi utenti possono eliminare una versione di un oggetto prima che venga raggiunta la data di conservazione.
** Questi utenti possono aumentare, diminuire o rimuovere la data di conservazione di un oggetto.






=== Impostazioni di conservazione per le versioni degli oggetti

Se viene creato un bucket con S3 Object Lock abilitato, gli utenti possono utilizzare l'applicazione client S3 per specificare facoltativamente le seguenti impostazioni di conservazione per ciascun oggetto aggiunto al bucket:

* *Modalità di conservazione*: conformità o governance.
* *Retain-until-date*: se la retain-until-date di una versione di un oggetto è futura, l'oggetto può essere recuperato, ma non eliminato.
* *Sospensione legale*: l'applicazione di una sospensione legale a una versione di un oggetto blocca immediatamente quell'oggetto.  Ad esempio, potrebbe essere necessario applicare un blocco legale a un oggetto correlato a un'indagine o a una controversia legale.  Una sospensione legale non ha una data di scadenza, ma rimane in vigore finché non viene rimossa esplicitamente.  Le sospensioni legali sono indipendenti dalla data di conservazione fino alla data di scadenza.
+

NOTE: Se un oggetto è sottoposto a conservazione legale, nessuno può eliminarlo, indipendentemente dalla sua modalità di conservazione.

+
Per i dettagli sulle impostazioni dell'oggetto, vederelink:../s3/use-s3-api-for-s3-object-lock.html["Utilizzare l'API REST S3 per configurare S3 Object Lock"] .





=== Impostazione di conservazione predefinita per i bucket

Se viene creato un bucket con S3 Object Lock abilitato, gli utenti possono facoltativamente specificare le seguenti impostazioni predefinite per il bucket:

* *Modalità di conservazione predefinita*: conformità o governance.
* *Periodo di conservazione predefinito*: per quanto tempo devono essere conservate le nuove versioni degli oggetti aggiunte a questo bucket, a partire dal giorno in cui vengono aggiunte.


Le impostazioni predefinite del bucket si applicano solo ai nuovi oggetti che non dispongono di impostazioni di conservazione proprie.  Gli oggetti bucket esistenti non vengono modificati quando si aggiungono o si modificano queste impostazioni predefinite.

Vederelink:../tenant/creating-s3-bucket.html["Crea un bucket S3"] Elink:../tenant/update-default-retention-settings.html["Aggiorna la conservazione predefinita del blocco degli oggetti S3"] .



== Confronto tra S3 Object Lock e la conformità legacy

S3 Object Lock sostituisce la funzionalità Compliance disponibile nelle versioni precedenti StorageGRID .  Poiché la funzionalità S3 Object Lock è conforme ai requisiti di Amazon S3, essa rende obsoleta la funzionalità proprietaria StorageGRID Compliance, ora denominata "legacy Compliance".


NOTE: L'impostazione Conformità globale è obsoleta.  Se hai abilitato questa impostazione utilizzando una versione precedente di StorageGRID, l'impostazione Blocco oggetto S3 viene abilitata automaticamente.  È possibile continuare a utilizzare StorageGRID per gestire le impostazioni dei bucket conformi esistenti; tuttavia, non è possibile creare nuovi bucket conformi.  Per i dettagli, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Knowledge Base di NetApp : come gestire i bucket Compliant legacy in StorageGRID 11.5"^] .

Se hai utilizzato la funzionalità Conformità legacy in una versione precedente di StorageGRID, fai riferimento alla tabella seguente per scoprire come si confronta con la funzionalità Blocco oggetti S3 in StorageGRID.

[cols="1a,1a,1a"]
|===
|  | Blocco oggetto S3 | Conformità (legacy) 


 a| 
Come viene abilitata la funzionalità a livello globale?
 a| 
Da Grid Manager, seleziona *CONFIGURAZIONE* > *Sistema* > *Blocco oggetto S3*.
 a| 
Non più supportato.



 a| 
Come si abilita la funzionalità per un bucket?
 a| 
Gli utenti devono abilitare S3 Object Lock quando creano un nuovo bucket utilizzando Tenant Manager, Tenant Management API o S3 REST API.
 a| 
Non più supportato.



 a| 
È supportato il controllo delle versioni dei bucket?
 a| 
Sì. Il controllo delle versioni del bucket è obbligatorio e viene abilitato automaticamente quando S3 Object Lock è abilitato per il bucket.
 a| 
NO.



 a| 
Come viene impostata la conservazione degli oggetti?
 a| 
Gli utenti possono impostare una data di conservazione per ogni versione dell'oggetto oppure possono impostare un periodo di conservazione predefinito per ogni bucket.
 a| 
Gli utenti devono impostare un periodo di conservazione per l'intero bucket.  Il periodo di conservazione si applica a tutti gli oggetti nel bucket.



 a| 
È possibile modificare il periodo di conservazione?
 a| 
* In modalità di conformità, la data di conservazione per una versione di un oggetto può essere aumentata ma mai diminuita.
* In modalità di governance, gli utenti con autorizzazioni speciali possono ridurre o addirittura rimuovere le impostazioni di conservazione di un oggetto.

 a| 
Il periodo di conservazione di un bucket può essere aumentato, ma mai diminuito.



 a| 
Dove viene controllata la conservazione legale?
 a| 
Gli utenti possono applicare o rimuovere una sospensione legale per qualsiasi versione dell'oggetto nel bucket.
 a| 
Viene applicata una sospensione legale al bucket che interessa tutti gli oggetti al suo interno.



 a| 
Quando è possibile eliminare gli oggetti?
 a| 
* In modalità di conformità, una versione dell'oggetto può essere eliminata dopo aver raggiunto la data di conservazione, a condizione che l'oggetto non sia soggetto a conservazione legale.
* In modalità di governance, gli utenti con autorizzazioni speciali possono eliminare un oggetto prima che venga raggiunta la data di conservazione, a condizione che l'oggetto non sia soggetto a conservazione legale.

 a| 
Un oggetto può essere eliminato dopo la scadenza del periodo di conservazione, a condizione che il bucket non sia sottoposto a conservazione legale.  Gli oggetti possono essere eliminati automaticamente o manualmente.



 a| 
La configurazione del ciclo di vita del bucket è supportata?
 a| 
SÌ
 a| 
NO

|===