---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure-coding scheme 
summary: Gli schemi di codifica di cancellazione controllano quanti frammenti di dati e quanti frammenti di parità vengono creati per ciascun oggetto. 
---
= Cosa sono gli schemi di codifica di cancellazione?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli schemi di codifica di cancellazione controllano quanti frammenti di dati e quanti frammenti di parità vengono creati per ciascun oggetto.

Quando si crea o si modifica una regola ILM, si seleziona uno schema di codifica di cancellazione disponibile.  StorageGRID crea automaticamente schemi di codifica di cancellazione in base al numero di nodi di archiviazione e siti che compongono il pool di archiviazione che si intende utilizzare.



== Protezione dei dati

Il sistema StorageGRID utilizza l'algoritmo di codifica della cancellazione Reed-Solomon.  L'algoritmo divide un oggetto in `k` frammenti di dati e calcoli `m` frammenti di parità.

IL `k + m = n` i frammenti sono sparsi `n` Nodi di archiviazione per garantire la protezione dei dati come segue:

* Per recuperare o riparare un oggetto, `k` sono necessari frammenti.
* Un oggetto può sostenere fino a `m` frammenti persi o corrotti.  Più alto è il valore di `m` , maggiore è la tolleranza al guasto.


La migliore protezione dei dati è fornita dallo schema di codifica di cancellazione con la più alta tolleranza ai guasti del nodo o del volume all'interno di un pool di archiviazione.



== Spese di archiviazione generali

Il sovraccarico di archiviazione di uno schema di codifica di cancellazione viene calcolato dividendo il numero di frammenti di parità(`m` ) dal numero di frammenti di dati(`k` ).  È possibile utilizzare il sovraccarico di archiviazione per calcolare la quantità di spazio su disco richiesta da ciascun oggetto con codice di cancellazione:

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

Ad esempio, se si archivia un oggetto da 10 MB utilizzando lo schema 4+2 (che ha un overhead di archiviazione del 50%), l'oggetto consuma 15 MB di spazio di archiviazione della griglia.  Se si memorizza lo stesso oggetto da 10 MB utilizzando lo schema 6+2 (che ha un overhead di archiviazione del 33%), l'oggetto consuma circa 13,3 MB.

Selezionare lo schema di codifica di cancellazione con il valore totale più basso di `k+m` che soddisfa le tue esigenze.  Gli schemi di codifica di cancellazione con un numero inferiore di frammenti sono più efficienti dal punto di vista computazionale perché:

* Vengono creati e distribuiti (o recuperati) meno frammenti per oggetto
* Hanno prestazioni migliori perché la dimensione del frammento è maggiore
* Possono richiedere che vengano aggiunti meno nodi in unlink:../expand/index.html["espansione quando è necessario più spazio di archiviazione"]




== Linee guida per i pool di stoccaggio

Quando si seleziona il pool di archiviazione da utilizzare per una regola che creerà una copia con codice di cancellazione, attenersi alle seguenti linee guida per i pool di archiviazione:

* Il pool di archiviazione deve includere tre o più siti oppure esattamente un sito.
+

NOTE: Non è possibile utilizzare la codifica di cancellazione se il pool di archiviazione include due siti.

+
** <<Schemi di codifica di cancellazione per pool di archiviazione contenenti tre o più siti,Schemi di codifica di cancellazione per pool di archiviazione contenenti tre o più siti>>
** <<Schemi di codifica di cancellazione per pool di archiviazione monosito,Schemi di codifica di cancellazione per pool di archiviazione monosito>>


* Non utilizzare un pool di archiviazione che includa il sito Tutti i siti.
* Il pool di archiviazione dovrebbe includere almeno `_k+m_ +1` Nodi di archiviazione in grado di archiviare dati di oggetti.
+

NOTE: Durante l'installazione, è possibile configurare i nodi di archiviazione in modo che contengano solo metadati degli oggetti e non dati degli oggetti. Per ulteriori informazioni, consultare link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipi di nodi di archiviazione"] .

+
Il numero minimo di nodi di archiviazione richiesti è `k+m` .  Tuttavia, avere almeno un nodo di archiviazione aggiuntivo può aiutare a prevenire errori di acquisizione o arretrati ILM se un nodo di archiviazione necessario non è temporaneamente disponibile.





== Schemi di codifica di cancellazione per pool di archiviazione contenenti tre o più siti

Nella tabella seguente vengono descritti gli schemi di codifica di cancellazione attualmente supportati da StorageGRID per i pool di archiviazione che includono tre o più siti.  Tutti questi schemi garantiscono una protezione contro le perdite del sito.  Anche se un sito può andare perso, l'oggetto sarà comunque accessibile.

Per gli schemi di codifica di cancellazione che forniscono protezione contro la perdita del sito, il numero consigliato di nodi di archiviazione nel pool di archiviazione supera `_k+m_ +1` perché ogni sito richiede un minimo di tre nodi di archiviazione.

[cols="1a,1a,1a,1a,1a,1a"]
|===
| Schema di codifica di cancellazione (_k+m_) | Numero minimo di siti distribuiti | Numero consigliato di nodi di archiviazione in ogni sito | Numero totale consigliato di nodi di archiviazione | Protezione contro le perdite del sito? | Spese di archiviazione generali 


 a| 
4+2
 a| 
3
 a| 
3
 a| 
9
 a| 
SÌ
 a| 
50%



 a| 
6+2
 a| 
4
 a| 
3
 a| 
12
 a| 
SÌ
 a| 
33%



 a| 
8+2
 a| 
5
 a| 
3
 a| 
15
 a| 
SÌ
 a| 
25%



 a| 
6+3
 a| 
3
 a| 
4
 a| 
12
 a| 
SÌ
 a| 
50%



 a| 
9+3
 a| 
4
 a| 
4
 a| 
16
 a| 
SÌ
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
3
 a| 
9
 a| 
SÌ
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
3
 a| 
15
 a| 
SÌ
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
3
 a| 
21
 a| 
SÌ
 a| 
17%



 a| 
7+5
 a| 
3
 a| 
5
 a| 
15
 a| 
SÌ
 a| 
71%

|===

NOTE: StorageGRID richiede un minimo di tre nodi di archiviazione per sito.  Per utilizzare lo schema 7+5, ogni sito richiede un minimo di quattro nodi di archiviazione.  Si consiglia di utilizzare cinque nodi di archiviazione per sito.

Quando si seleziona uno schema di codifica di cancellazione che garantisca la protezione del sito, è necessario valutare l'importanza relativa dei seguenti fattori:

* *Numero di frammenti*: le prestazioni e la flessibilità di espansione sono generalmente migliori quando il numero totale di frammenti è inferiore.
* *Tolleranza ai guasti*: la tolleranza ai guasti aumenta avendo più segmenti di parità (ovvero, quando `m` ha un valore più alto.)
* *Traffico di rete*: durante il ripristino da guasti, utilizzando uno schema con più frammenti (ovvero, un totale più elevato per `k+m` ) crea più traffico di rete.
* *Sovraccarico di archiviazione*: gli schemi con sovraccarico più elevato richiedono più spazio di archiviazione per oggetto.


Ad esempio, quando si decide tra uno schema 4+2 e uno schema 6+3 (entrambi con un overhead di archiviazione del 50%), selezionare lo schema 6+3 se è richiesta una tolleranza agli errori aggiuntiva.  Selezionare lo schema 4+2 se le risorse di rete sono limitate.  Se tutti gli altri fattori sono uguali, seleziona 4+2 perché ha un numero totale di frammenti inferiore.


NOTE: Se non sei sicuro di quale schema utilizzare, seleziona 4+2 o 6+3 oppure contatta l'assistenza tecnica.



== Schemi di codifica di cancellazione per pool di archiviazione monosito

Un pool di archiviazione con un solo sito supporta tutti gli schemi di codifica di cancellazione definiti per tre o più siti, a condizione che il sito disponga di un numero sufficiente di nodi di archiviazione.

Il numero minimo di nodi di archiviazione richiesti è `k+m` , ma un pool di archiviazione con `k+m +1` Si consiglia l'uso di Storage Nodes.  Ad esempio, lo schema di codifica di cancellazione 2+1 richiede un pool di archiviazione con un minimo di tre nodi di archiviazione, ma si consigliano quattro nodi di archiviazione.

[cols="1a,1a,1a,1a"]
|===
| Schema di codifica di cancellazione (_k+m_) | Numero minimo di nodi di archiviazione | Numero consigliato di nodi di archiviazione | Spese di archiviazione generali 


 a| 
4+2
 a| 
6
 a| 
7
 a| 
50%



 a| 
6+2
 a| 
8
 a| 
9
 a| 
33%



 a| 
8+2
 a| 
10
 a| 
11
 a| 
25%



 a| 
6+3
 a| 
9
 a| 
10
 a| 
50%



 a| 
9+3
 a| 
12
 a| 
13
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
4
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
6
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
8
 a| 
17%



 a| 
7+5
 a| 
12
 a| 
13
 a| 
71%

|===