---
permalink: ilm/workflow-for-s3-object-lock.html 
sidebar: sidebar 
keywords: object lock workflow 
summary: In qualità di amministratore della griglia, devi coordinarti strettamente con gli utenti tenant per garantire che gli oggetti siano protetti in modo da soddisfare i loro requisiti di conservazione. 
---
= Attività di blocco degli oggetti S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In qualità di amministratore della griglia, devi coordinarti strettamente con gli utenti tenant per garantire che gli oggetti siano protetti in modo da soddisfare i loro requisiti di conservazione.


NOTE: L'applicazione delle impostazioni del tenant sulla griglia potrebbe richiedere 15 minuti o più, a seconda della connettività di rete, dello stato del nodo e delle operazioni di Cassandra.

Gli elenchi seguenti per gli amministratori della griglia e gli utenti tenant contengono le attività di alto livello per l'utilizzo della funzionalità S3 Object Lock.

Amministratore di rete::
+
--
* Abilita l'impostazione globale di blocco degli oggetti S3 per l'intero sistema StorageGRID .
* Garantire che le politiche di gestione del ciclo di vita delle informazioni (ILM) siano _conformi_; ovvero, che soddisfino ilink:../ilm/managing-objects-with-s3-object-lock.html["requisiti dei bucket con S3 Object Lock abilitato"] .
* Se necessario, consentire a un tenant di utilizzare Conformità come modalità di conservazione.  In caso contrario, è consentita solo la modalità Governance.
* Se necessario, impostare un periodo massimo di conservazione per un tenant.


--
Utente inquilino::
+
--
* Esaminare le considerazioni relative a bucket e oggetti con S3 Object Lock.
* Se necessario, contattare l'amministratore della griglia per abilitare l'impostazione globale di blocco degli oggetti S3 e impostare le autorizzazioni.
* Crea bucket con S3 Object Lock abilitato.
* Facoltativamente, configura le impostazioni di conservazione predefinite per un bucket:
+
** Modalità di conservazione predefinita: Governance o Conformità, se consentita dall'amministratore della rete.
** Periodo di conservazione predefinito: deve essere inferiore o uguale al periodo di conservazione massimo impostato dall'amministratore della griglia.


* Utilizzare l'applicazione client S3 per aggiungere oggetti e, facoltativamente, impostare la conservazione specifica dell'oggetto:
+
** Modalità di conservazione.  Governance o conformità, se consentito dall'amministratore della rete.
** Conserva fino alla data: deve essere inferiore o uguale a quanto consentito dal periodo di conservazione massimo impostato dall'amministratore della griglia.




--

