---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, active interface, backup interface 
summary: 'Quando si configura StorageGRID per l"utilizzo con FabricPool, è possibile creare facoltativamente uno o più gruppi ad alta disponibilità (HA).  Un gruppo HA è una raccolta di nodi, ognuno dei quali contiene il servizio StorageGRID Load Balancer.  Un gruppo HA può contenere nodi gateway, nodi amministrativi o entrambi.' 
---
= Creare un gruppo ad alta disponibilità (HA) per FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura StorageGRID per l'utilizzo con FabricPool, è possibile creare facoltativamente uno o più gruppi ad alta disponibilità (HA).  Un gruppo HA è una raccolta di nodi, ognuno dei quali contiene il servizio StorageGRID Load Balancer.  Un gruppo HA può contenere nodi gateway, nodi amministrativi o entrambi.

È possibile utilizzare un gruppo HA per mantenere disponibili le connessioni dati FabricPool .  Un gruppo HA utilizza indirizzi IP virtuali (VIP) per fornire un accesso altamente disponibile al servizio Load Balancer.  Se l'interfaccia attiva nel gruppo HA fallisce, un'interfaccia di backup può gestire il carico di lavoro con un impatto minimo sulle operazioni FabricPool .

Per i dettagli su questa attività, vederelink:../admin/managing-high-availability-groups.html["Gestire gruppi ad alta disponibilità"] .  Per utilizzare la procedura guidata di configurazione FabricPool per completare questa attività, andare alink:use-fabricpool-setup-wizard-steps.html["Accedi e completa la procedura guidata di configurazione FabricPool"] .

.Prima di iniziare
* Hai esaminato illink:best-practices-for-high-availability-groups.html["best practice per gruppi ad alta disponibilità"] .
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:../admin/admin-group-permissions.html["Permesso di accesso root"] .
* Se si prevede di utilizzare una VLAN, è stata creata l'interfaccia VLAN. Vedere link:../admin/configure-vlan-interfaces.html["Configurare le interfacce VLAN"] .


.Passi
. Selezionare *CONFIGURAZIONE* > *Rete* > *Gruppi ad alta disponibilità*.
. Seleziona *Crea*.
. Per la fase *Inserisci dettagli*, compila i seguenti campi.
+
[cols="1a,2a"]
|===
| Campo | Descrizione 


 a| 
Nome del gruppo HA
 a| 
Un nome visualizzato univoco per questo gruppo HA.



 a| 
Descrizione (facoltativa)
 a| 
Descrizione di questo gruppo HA.

|===
. Per il passaggio *Aggiungi interfacce*, seleziona le interfacce del nodo che desideri utilizzare in questo gruppo HA.
+
Utilizzare le intestazioni di colonna per ordinare le righe oppure immettere un termine di ricerca per individuare più rapidamente le interfacce.

+
È possibile selezionare uno o più nodi, ma è possibile selezionare solo un'interfaccia per ciascun nodo.

. Per il passaggio *Assegna priorità alle interfacce*, determinare l'interfaccia primaria e tutte le interfacce di backup per questo gruppo HA.
+
Trascinare le righe per modificare i valori nella colonna *Ordine di priorità*.

+
La prima interfaccia nell'elenco è l'interfaccia primaria.  L'interfaccia primaria è l'interfaccia attiva, a meno che non si verifichi un errore.

+
Se il gruppo HA include più di un'interfaccia e l'interfaccia attiva non funziona, gli indirizzi IP virtuali (VIP) vengono spostati sulla prima interfaccia di backup in ordine di priorità.  Se tale interfaccia non funziona, gli indirizzi VIP vengono spostati alla successiva interfaccia di backup e così via.  Una volta risolti i guasti, gli indirizzi VIP tornano all'interfaccia con la priorità più alta disponibile.

. Per il passaggio *Inserisci indirizzi IP*, compila i seguenti campi.
+
[cols="1a,2a"]
|===
| Campo | Descrizione 


 a| 
CIDR di sottorete
 a| 
L'indirizzo della subnet VIP in notazione CIDR: un indirizzo IPv4 seguito da una barra e dalla lunghezza della subnet (0-32).

L'indirizzo di rete non deve avere alcun bit host impostato. Ad esempio,  `192.16.0.0/22` .



 a| 
Indirizzo IP del gateway (facoltativo)
 a| 
Opzionale.  Se gli indirizzi IP ONTAP utilizzati per accedere a StorageGRID non si trovano sulla stessa subnet degli indirizzi VIP StorageGRID , immettere l'indirizzo IP del gateway locale VIP StorageGRID .  L'indirizzo IP del gateway locale deve essere all'interno della subnet VIP.



 a| 
Indirizzo IP virtuale
 a| 
Inserire almeno uno e non più di dieci indirizzi VIP per l'interfaccia attiva nel gruppo HA.  Tutti gli indirizzi VIP devono trovarsi all'interno della subnet VIP.

Almeno un indirizzo deve essere IPv4.  Facoltativamente, è possibile specificare indirizzi IPv4 e IPv6 aggiuntivi.

|===
. Selezionare *Crea gruppo HA* e quindi selezionare *Fine*.

