---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure coding, replication, cloud storage pool, glacier 
summary: È possibile utilizzare questo semplice esempio di policy come punto di partenza per le proprie regole e policy ILM. 
---
= Configurare ILM per i dati FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare questo semplice esempio di policy come punto di partenza per le proprie regole e policy ILM.

In questo esempio si presuppone che si stiano progettando le regole ILM e una policy ILM per un sistema StorageGRID dotato di quattro nodi di archiviazione in un unico data center a Denver, Colorado.  I dati FabricPool in questo esempio utilizzano un bucket denominato `fabricpool-bucket` .


CAUTION: Le seguenti regole e policy ILM sono solo esempi.  Esistono molti modi per configurare le regole ILM.  Prima di attivare una nuova policy, simulala per verificare che funzioni come previsto per proteggere i contenuti dalla perdita.  Per saperne di più, vederelink:../ilm/index.html["Gestire gli oggetti con ILM"] .


CAUTION: Per evitare la perdita di dati, non utilizzare una regola ILM che farà scadere o eliminerà i dati del livello cloud FabricPool .  Impostare il periodo di conservazione su *per sempre* per garantire che gli oggetti FabricPool non vengano eliminati da StorageGRID ILM.

.Prima di iniziare
* Hai esaminato illink:best-practices-ilm.html["best practice per l'utilizzo di ILM con dati FabricPool"] .
* Hai effettuato l'accesso a Grid Manager utilizzando unlink:../admin/web-browser-requirements.html["browser web supportato"] .
* Tu hai illink:../admin/admin-group-permissions.html["Autorizzazione di accesso ILM o Root"] .
* Se hai eseguito l'aggiornamento a StorageGRID 11.9 da una versione precedente StorageGRID , hai configurato il pool di archiviazione che utilizzerai. In generale, dovresti creare un pool di archiviazione per ogni sito StorageGRID che utilizzerai per archiviare i dati.
+

NOTE: Questo prerequisito non si applica se inizialmente è stato installato StorageGRID 11.7 o 11.8.  Quando si installa inizialmente una di queste versioni, vengono creati automaticamente dei pool di archiviazione per ogni sito.



.Passi
. Creare una regola ILM che si applica solo ai dati in `fabricpool-bucket` Questa regola di esempio crea copie con codice di cancellazione.
+
[cols="1a,2a"]
|===
| Definizione della regola | Valore di esempio 


 a| 
Nome della regola
 a| 
Codifica di cancellazione 2 + 1 per i dati FabricPool



 a| 
Nome del bucket
 a| 
`fabricpool-bucket`

È anche possibile filtrare in base all'account tenant FabricPool .



 a| 
Filtri avanzati
 a| 
Dimensione dell'oggetto superiore a 0,2 MB.

*Nota:* FabricPool scrive solo oggetti da 4 MB, ma è necessario aggiungere un filtro per le dimensioni degli oggetti perché questa regola utilizza la codifica di cancellazione.



 a| 
Tempo di riferimento
 a| 
Tempo di ingestione



 a| 
Periodo di tempo e collocamenti
 a| 
Dal giorno 0 conservalo per sempre

Memorizzare gli oggetti tramite codifica di cancellazione utilizzando lo schema EC 2+1 a Denver e conservare tali oggetti in StorageGRID per sempre.


CAUTION: Per evitare la perdita di dati, non utilizzare una regola ILM che farà scadere o eliminerà i dati del livello cloud FabricPool .



 a| 
Comportamento di ingestione
 a| 
Equilibrato

|===
. Crea una regola ILM predefinita che creerà due copie replicate di tutti gli oggetti non corrispondenti alla prima regola.  Non selezionare un filtro di base (account tenant o nome bucket) né filtri avanzati.
+
[cols="1a,2a"]
|===
| Definizione della regola | Valore di esempio 


 a| 
Nome della regola
 a| 
Due copie replicate



 a| 
Nome del bucket
 a| 
_nessuno_



 a| 
Filtri avanzati
 a| 
_nessuno_



 a| 
Tempo di riferimento
 a| 
Tempo di ingestione



 a| 
Periodo di tempo e collocamenti
 a| 
Dal giorno 0 conservalo per sempre

Conserva gli oggetti replicandone 2 copie a Denver.



 a| 
Comportamento di ingestione
 a| 
Equilibrato

|===
. Creare una policy ILM e selezionare le due regole.  Poiché la regola di replica non utilizza alcun filtro, può essere la regola predefinita (ultima) per il criterio.
. Inserire gli oggetti di prova nella griglia.
. Simulare la policy con gli oggetti di prova per verificarne il comportamento.
. Attiva la policy.


Quando questa policy è attivata, StorageGRID posiziona i dati degli oggetti come segue:

* I dati suddivisi in livelli da FabricPool in `fabricpool-bucket` verrà codificato con cancellazione utilizzando lo schema di codifica 2+1.  Due frammenti di dati e un frammento di parità verranno posizionati su tre nodi di archiviazione diversi.
* Tutti gli oggetti in tutti gli altri bucket verranno replicati.  Verranno create due copie e posizionate su due nodi di archiviazione diversi.
* Le copie verranno conservate in StorageGRID per sempre.  StorageGRID ILM non eliminerà questi oggetti.

